### ISSUE TITLE
use flask's instance_path

### ISSUE THREAD

**Issue by ThomasWaldmann** [moinwiki/moin#102]
**[Original report](https://bitbucket.org/thomaswaldmann/moin-2.0/issue/102) by Thomas Waldmann (Bitbucket: [thomaswaldmann](https://bitbucket.org/thomaswaldmann), GitHub: [thomaswaldmann](https://github.com/thomaswaldmann)).**

----------------------------------------

See there: http://flask.pocoo.org/docs/api/

* instance_path
* instance_relative_config = True
* open_instance_resource()

Looks like stuff we need for wiki instances. :)

TODO: refactor moin to use this Flask stuff, so admins can just give the instance path to create_app and, by default, everything will be computed relative to that path.

**Comment by ThomasWaldmann** [comment]
A real world scenario could look like this:

- moin is installed, somewhere, somehow (venv, pip, apt, rpm, ...).
- `import moin` and the `moin` cli command work.
- we can not expect anything else at specific (relative) pathes like when working in a repo checkout.
- we need a directory that holds a moin `instance` (meaning: config, wiki data, other resources related to one moin wiki website)
- the template for this instance dir needs to be prepared by moin development. could be just part of the moin python package.
- we could have a `create instance` cli command that takes data from this template and copies them to some desired place.
- the created instance dir would then be customized (configuration, adding icons/images, ...)
- the instance dir needs to be given to the moin app (via environment var?)
- flask/moin loads the config from `instance_dir/wikiconfig.py`
- maybe we could also use instance-relative pathes elsewhere (e.g. to load interwiki list or other stuff)
- file-based data storage would be also in the instance dir

**Comment by RogerHaase** [comment]
Can this issue be closed?

`moin create-instance --path <mywiki>` creates this structure (using CWD if path is omitted)

    mywiki/                 # wikiconfig dir, use this as CWD for moin commands
        wiki/               # the wiki instance; created by `moin create-instance`
            data/           # wiki data and metadata
            index/          # wiki indexes
            preview/        # backups created when user clicks edit Preview button
            sql/            # sqlite database used for edit locking
        wikiconfig.py       # main configuration file, modify this to add or change features
        wiki-local          # use this to store custom CSS, Javascript, templates, logos, etc.
        intermap.txt        # list of external wikis used in wikilinks: [[MeatBall:InterWiki]]

Where imho, mywiki/ should be described as the "instance". But the code describes wiki/ as the instance.

    wikiconfig_dir = os.path.abspath(os.path.dirname(__file__))
    instance_dir = os.path.join(wikiconfig_dir, 'wiki')

The `moin create-instance` works for both clone and pip installations. Multiple instances can be created in multiple locations. By default, the `moin run` command uses the instance (wikiconfig dir) at the CWD, but this can be overridden by setting the OS environment MOINCFG=<path>.
