### ISSUE TITLE
first startup should build index if not given

### ISSUE THREAD

**Issue by ThomasWaldmann** [moinwiki/moin#103]
**[Original report](https://bitbucket.org/thomaswaldmann/moin-2.0/issue/103) by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

At least on the desktop system a first call of moin should initialize the index
if it was not done beforehand.

Instead of 
raise IOError("Directory %s does not exist" % path)

We should offer a request question to build the index by:

e.g.

No index found! Do you want to build the index now? 

If yes:
moin index-create -s -i

if no:

you have to manually create the index, e.g. moin index-create -s -i

**Comment by RogerHaase** [comment]
This is similar to #272 auto-create storage / index if they do not exist.  

Closing this in favor of showing warning messages in stead of tracebacks if wiki admin tries to do steps out of order. See #824 Issue a warning if user forgets to create wiki before running moin.
