### ISSUE TITLE
hierachical acls

### ISSUE THREAD

**Issue by ThomasWaldmann** [moinwiki/moin#107]
**[Original report](https://bitbucket.org/thomaswaldmann/moin-2.0/issue/107) by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

For hierarchical acls it is important to know what a subitem of an item is.
This is only based on the name currently. Is that correct?
Because at setting up hacl it is done on items uuid mapping to the names in the hierarchy. If the item has more than one name, which are the valid rights? 
How does it work if an item has a name and a subitem name?

That looks rather complex now. May be we should replace hacl by something like range acls? By that we could setup in meta the ids of the items which have same rights as the item where we have acls defined.

**Comment by RogerHaase** [comment]
If we removed the alias names feature and just used the transclusion feature to simulate an item having multiple names do we do we solve this issue but lose some required feature?

What is a use case that requires multiple item names that cannot be satisfied with transclusions?

Where A and B appear the same because B's content is "{{A}}".

**Comment by ThomasWaldmann** [comment]
transclusions are asymetric: there is one "original" item and other items transclude that.
having multiple names (and there is no "main name" and "aliases") is a symetric approach.

kind of hardlinks vs. symlinks.

**Comment by RogerHaase** [comment]
Is there something left to do here? 

The only behavior that seems odd is when the parents have conflicting permissions, allow always wins; even when the deny parent is first in the list.
