### ISSUE TITLE
Search and Lookup have limit of 100 hits

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#1072]
In /frontend/views.py the limit number of search and lookup hits is hard coded to 100 within the query.

At a minimum, this should be defined somewhere in the constants directory. Or, it should be defined within the wiki defaults, or even user options

**Comment by ThomasWaldmann** [comment]
We could do that or not, IMHO.

The initial idea was that if there are more than 100 results, likely noone will look through them all anyway (or even want more than 100), but rather will do another search with more specific terms, yielding less results.

**Comment by RogerHaase** [comment]
Fixing the scoring issue, #1073, is more important and would eliminate the need for this issue. Closing
