### ISSUE TITLE
reverting an item should verify that the item parent chain is intact

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#1080]
Create and item `a` and a subitem `a/b`. Delete item `a`; item `a/b` will be deleted as well. 

View global history and restore subitem `a/b`. This succeeds but is should fail with MissingParentError.

**Comment by ThomasWaldmann** [comment]
In moin-1.9, if you had an item `a/b`, that did not require that you also have an item `a`.

It is of course structurally not very nice to have children without parents, but possible.

**Comment by RogerHaase** [comment]
While reports, etc. will work when there are orphan subitems, editors should appreciate an error message that highlights the inconsistency. 

Import19 silently tolerates orphan subitems, but should log an error message. The Global Index view has links to correct these issues.

**Comment by RogerHaase** [comment]
After working on Delete/Destroy with alias names and subitems, and trying to delete all subitems when a parent is deleted; having orphan items can be useful in some circumstances. One use case is when an editor wants to change the content type of a parent item.

Closing issue.
