### ISSUE TITLE
whoosh index fields defined in wrong dict - trivial

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#1087]
Within IndexingMiddleware there are blog-only and ticket-only fields defined within common_fields.

PTIME should be moved to blog_entry_fields.

REFERS_TO, ELEMENT, and REPLY_TO should be moved to ticket_fields.

**Comment by abaruchi** [comment]
Hi Roger, 
I'm interested in contribute with moin project. Hope to give relevant inputs to the code. I worked in this issue yesterday and I would like to know if it is okay to create a PR with the fix. The commits are:

https://github.com/moinwiki/moin/commit/471097bb38ed16ca51837e078b7816a02ecd7d2e
https://github.com/moinwiki/moin/commit/5354865079a3231394dcd9c94dfc002e9ad8ac06

**Comment by RogerHaase** [comment]
Hi Artur,

Help is much needed and appreciated.  The change looks OK to me.

Did you test for unexpected side effects by doing ./m sample; ./m index,
./m import19 (if you have a moin 1.9x wiki)?

I am thinking the change can just be pulled by existing users without
having to rebuild the index.

Roger

**Comment by abaruchi** [comment]
Hi Roger,
I run the tests before and after the change and both reported the same results, so I assumed it was fine. I did't test with import19 cause I didn't installed moin 1.9. The output was the following:

```bash
$ ./m tests

Running tests... output written to m-tox.txt.
Important messages from m-tox.txt are shown below. Do "./m log tests" to see complete log.
12 /Users/abaruchi/Projects/moin/.tox/py37/lib/python3.7/site-packages/pep8.py:110: FutureWarning: Possible nested set at position 1
219 =========== 1666 passed, 18 skipped, 1 xfailed in 479.27s (0:07:59) ============
227 flake8 installdeps: flake8
Tests run time (h:mm:ss) 0:09:23
```
I recreated the sample and the indexes to make sure it is working fine and looks fine too.

```bash
$ ./m sample
Creating a new wiki populated with sample data...
Output messages redirected to m-new-wiki.txt.

Success: a new wiki has been created... working...
Output messages redirected to m-new-wiki.txt.

Success: the index has been created for the sample wiki... working...
29 items were added to wiki
Sample run time (h:mm:ss) 0:00:54

$ ./m index
Rebuilding indexes...

Important messages from m-rebuild-index.txt are shown below. Do "./m log index" to see complete log.
Rebuild index run time (h:mm:ss) 0:00:05
```

**Comment by RogerHaase** [comment]
Hi Artur,

I committed your pull request and pulled to my local repo, works fine.
