### ISSUE TITLE
html parsing fix. 

### ISSUE THREAD

**Issue by montarion** [moinwiki/moin#1089]
the html parser ``emeraldtree`` uses mimetools, which is incompatible python python3.x

To fix this, emeraldtree can be patched like this:

replacing ``mimetools.message(StringIO.StringIO(...))`` with ``email.message_from_string(str(...))``

because of the loss of mimetools, ``encoding`` was hardcoded to "utf-8".

emeraldtree can be found in ``/usr/local/python3.x/dist-packages/emeraldtree-x.x.x-py3.x.egg``

``.egg`` files are just .zip files, so you need to unzip the archive, edit the resulting ``emeraldtree/html.py`` file, zip it up again, and then restore it. 

I hope this helps someone. Devs, sorry if this is the wrong place.

Errors that might've gotten people here:

no module named mimetools
no module named stringio

**Comment by RogerHaase** [comment]
montarion,

Please provide a diff of your changes, or attach the file containing your changes, or a pull request on https://github.com/moinwiki/emeraldtree
