### ISSUE TITLE
AssertionError: Can't parse version moin20-repo-reboot

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#1091]
This happened after installing python 3.8.3, downloading a fresh clone of moin, and executing `python quickinstall.py` on an old PC running Windows 10.

This issue not present on another PC running Windows 10 with python 3.8.3.

    Obtaining file:///C:/git/moin
        ERROR: Command errored out with exit status 1:
         command: 'c:\git\moin-venv-python\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\git\\moin\\setup.py'"'"'; __file__='"'"'C:\\git\\moin\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info
             cwd: C:\git\moin\
        Complete output (33 lines):
        C:\Python38\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'message_extractors'
          warnings.warn(msg)
        c:\git\moin\.eggs\setuptools_scm-5.0.1-py3.8.egg\setuptools_scm\version.py:88: UserWarning: tag 'moin20-repo-reboot' no version found
          warnings.warn("tag {!r} no version found".format(tag))
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "C:\git\moin\setup.py", line 141, in <module>
            setup(**setup_args)
          File "c:\git\moin-venv-python\lib\site-packages\setuptools\__init__.py", line 145, in setup
            return distutils.core.setup(**attrs)
          File "C:\Python38\lib\distutils\core.py", line 108, in setup
            _setup_distribution = dist = klass(attrs)
          File "c:\git\moin-venv-python\lib\site-packages\setuptools\dist.py", line 445, in __init__
            _Distribution.__init__(self, {
          File "C:\Python38\lib\distutils\dist.py", line 292, in __init__
            self.finalize_options()
          File "c:\git\moin-venv-python\lib\site-packages\setuptools\dist.py", line 734, in finalize_options
            ep.load()(self, ep.name, value)
          File "c:\git\moin\.eggs\setuptools_scm-5.0.1-py3.8.egg\setuptools_scm\integration.py", line 26, in version_keyword
            dist.metadata.version = _get_version(config)
          File "c:\git\moin\.eggs\setuptools_scm-5.0.1-py3.8.egg\setuptools_scm\__init__.py", line 173, in _get_version
            parsed_version = _do_parse(config)
          File "c:\git\moin\.eggs\setuptools_scm-5.0.1-py3.8.egg\setuptools_scm\__init__.py", line 127, in _do_parse
            version = _version_from_entrypoints(config) or _version_from_entrypoints(
          File "c:\git\moin\.eggs\setuptools_scm-5.0.1-py3.8.egg\setuptools_scm\__init__.py", line 65, in _version_from_entrypoints
            version = _call_entrypoint_fn(root, config, ep.load())
          File "c:\git\moin\.eggs\setuptools_scm-5.0.1-py3.8.egg\setuptools_scm\__init__.py", line 46, in _call_entrypoint_fn
            return fn(root, config=config)
          File "c:\git\moin\.eggs\setuptools_scm-5.0.1-py3.8.egg\setuptools_scm\git.py", line 133, in parse
            return meta(
          File "c:\git\moin\.eggs\setuptools_scm-5.0.1-py3.8.egg\setuptools_scm\version.py", line 212, in meta
            assert parsed_version is not None, "Can't parse version %s" % tag
        AssertionError: Can't parse version moin20-repo-reboot
        ----------------------------------------
    ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    WARNING: You are using pip version 19.2.3, however version 20.3.3 is available.
    You should consider upgrading via the 'python -m pip install --upgrade pip' command.

**Comment by ThomasWaldmann** [comment]
Did you checkout master branch?

**Comment by RogerHaase** [comment]
Did not checkout master branch.

Uninstalled python 3.8.3, installed 3.9.1 - could not reproduce.

Uninstalled 3.9.1, installed 3.8.3 - could not reproduce.

Closing.

**Comment by RogerHaase** [comment]
Updated main Windows PC to Python 3.9.1, deleted virtualenv, m.bat, activate, deactivate, ran "python quickinstall.py" to recreate virtualenv; got same error as above.

git branch is master. Uninstalled 3.9.1, repeated installation, same error.

Tried renaming moin20-repo-reboot to moin-2.0.0, works!

**Comment by RogerHaase** [comment]
Fresh clone of moinwiki repo works.

Fresh clone of my repo fails.

**Comment by ThomasWaldmann** [comment]
That's strange... - not sure why setuptools_scm insists on being able to parse that tag - not all tags can be expected to be version numbers...

@RonnyPfannschmidt can you help, please?

**Comment by RonnyPfannschmidt** [comment]
this may be related to loosening the constraints on version parsing a bit quite a while back, so it may be a regression, let me check

**Comment by RonnyPfannschmidt** [comment]
https://github.com/pypa/setuptools_scm/blob/master/src/setuptools_scm/git.py#L15 seems to trigger the regression, i think i have to tighten it again

**Comment by RonnyPfannschmidt** [comment]
i believe this happened in the 3 series so trying a early one may fix, im tied up today and cant take a look at the details soon

**Comment by RogerHaase** [comment]
To clarify, the only known failing repo is https://github.com/RogerHaase/moin.git. This repo *should* be the same as the moinwiki master.

After a fresh clone, `python quickinstall.py` fails with the above error. The failure occurs on Windows 10 and Ubuntu 20.4 with various python 3 versions.

As of today's tests, the failure seems consistent. But I am not sure it is always consistent.

**Comment by RogerHaase** [comment]
If I do:

    git clone https://github.com/moinwiki/moin.git
    cd moin
    git tag

There are 2 tags:

    2.0.0dev0
    moin20-repo-reboot

But when I do:

    git clone https://github.com/RogerHaase/moin.git
    cd moin
    git tag

There is only one tag:

    moin20-repo-reboot

If I do:

    git tag 2.0.0dev0 moin20-repo-reboot
    git tag

There are 2 tags:

    2.0.0dev0
    moin20-repo-reboot

And `python quickinstall.py` runs successfully. I suspect setuptools_scm wants at least 1 tag that looks like a version number.

The 2.0.0dev0 tag was created 2018-08-29. I cannot tell when my github repo was created, but my windows clone was created a few hours after the tag was created. Per https://git-scm.com/book/en/v2/Git-Basics-Tagging

    Now, when someone else clones or pulls from your repository, they will get all your tags as well.

which does not appear to be true, because the 2.0.0dev0 tag is not copied after a pull from moinwiki master.

**Comment by RogerHaase** [comment]
"git pull --tags moinwiki master" pulls the missing tag

**Comment by RonnyPfannschmidt** [comment]
Thanks for the outline of the context, that explains a lot more about the issue, i believe some support code may be needed

**Comment by RogerHaase** [comment]
Used git pull/push --tags to fix tags with repos. Nothing further to do here.

**Comment by MatPoliquin** [comment]
Seems there is the same problem with this repo:
[https://github.com/openai/retro](https://github.com/openai/retro)

```
pip3 install -e .
```
Error log:
```
File "/home/tu106/github/stable-retro/.eggs/setuptools_scm-6.0.1-py3.8.egg/setuptools_scm/version.py", line 195, in meta
        assert parsed_version is not None, "Can't parse version %s" % tag
    AssertionError: Can't parse version f347d7e
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

**Comment by RonnyPfannschmidt** [comment]
creating a new issue
