### ISSUE TITLE
freenode -> libera

### ISSUE THREAD

**Issue by ThomasWaldmann** [moinwiki/moin#1114]
### irc
seems like there was kind of a hostile takeover of freenode and everybody is moving to libera.chat now.

i personally did not investigate this much, but there are some details: https://anarc.at/blog/2021-05-24-leaving-freenode/

so i'ld suggest we just also move to libera. maybe a single channel `#moin` is enough these days.

### matrix
switching to a matrix channel would be also a good option, but would require a switch of clients, too.

i personally run `irssi` on a `screen`/`tmux` on a server (so the client is permanently connected to the chat network), is there something similar for matrix?

**Comment by ThomasWaldmann** [comment]
registration email sent, let's see when it gets processed.

**Comment by ThomasWaldmann** [comment]
no reply yet to my email, but noticed i got admin on #moin libera channel and so i registered it.

also updated the MoinMoinChat wiki page about the channel moving from freenode to libera.

**Comment by Dreamsorcerer** [comment]
> i personally run `irssi` on a `screen`/`tmux` on a server (so the client is permanently connected to the chat network), is there something similar for matrix?

No idea what irssi is like, but there are CLI clients for Matrix, check this list of available clients:
https://matrix.org/clients/

Also worth remembering that you can bridge the Matrix chat into IRC and Libera.chat, rather than having to choose one or the other.
