### ISSUE TITLE
valid interwiki links fail if first character is lower-case or there is an embedded number

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#1118]
On moin2, interwiki names that start with a lower-case letter or contain a number fail.

Examples from interwiki.map:

* `py2exe http://www.py2exe.org/index.cgi/`
* `hg https://www.mercurial-scm.org/wiki/`
* `h2g2 http://h2g2.com/dna/h2g2/`

Attempts to use the above generate links to non-existent items.

    <p data-lineno="15">
    <a class="moin-nonexistent" href="/py2exe:http://www.py2exe.org/index.cgi/">py2exe:http://www.py2exe.org/index.cgi/
    </a>
    </p>

A correct link [[WikiPedia:Cat]] would be similar to:

    <p data-lineno="21">
    <a class="moin-interwiki" href="https://en.wikipedia.org/wiki/Cat">Cat
    </a>
    </p>

Transclusions also fail.

**Comment by RogerHaase** [comment]
Moin 1.9 has same bug in /parser/text_moin_wiki.py near line 78:

            (?P<interwiki_wiki>[A-Z][a-zA-Z]+)  # interwiki wiki name

Could not find a definitive source of rules for a valid interwiki name. Best I could find was an example from https://en.wikipedia.org/wiki/MediaWiki#Interwiki_links where the example `wikiquote:Jimbo Wales` begins with a lowercase character.

"""

Interwiki links

Interwiki links function much the same way as namespaces. A set of interwiki prefixes can be configured to cause, for instance, a page title of wikiquote:Jimbo Wales to direct the user to the Jimbo Wales article on Wikiquote.[66] Unlike internal wikilinks, interwiki links lack page existence detection functionality, and accordingly there is no way to tell whether a blue interwiki link is broken or not.

"""

**Comment by ThomasWaldmann** [comment]
For free standing interwiki links like `MoinMoin:SomePage` it likely was intended that only wikinames that are similar to camelcase trigger interwiki markup.

IIRC we had an old ticket at some time where somebody pointed out that some languages have the colon `:` inside normal words.

When changing the rules we need to be careful that old content does not suddenly show semantics. So if foo:bar was not a link, it shall not suddenly become one.

**Comment by RogerHaase** [comment]
A manual scan of intermap.txt yields 5 affected wikis:

        py2exe
        hg
        C2find
        h2g2
        SL4Wiki

Prior to the bug fix, `[[py2exe:Home]]` created a link to a local missing page, now it creates an interwiki link.

`[[foo:bar]]` will continue to create a local link because `foo`  is not listed in intermap.txt.

**Comment by ThomasWaldmann** [comment]
The cases with link markup like `[[foo:bar]]` are no problem, they can't cause unintended links.

But we need to check whether `foo:bar` creates unintended links, esp. in 1.9.

**Comment by RogerHaase** [comment]
I have no intent to fix the bug in moin 1.9.

Colons are allowed in page names in both 1.9 and 2.

The 1.9 HelpOnLinking docs imply numbers and lower case wikilinks are allowed.

<html><body>


Description|Syntax|comment
-- | -- | --
interwiki link | Otherwiki:somepage | requires uppercase wikiname
interwiki free link | [[otherwiki:somepage]] | any wikiname in the map works


</body>
</html>

But, as mentioned above, the re code requires leading cap, no digits:

        (?P<interwiki_wiki>[A-Z][a-zA-Z]+)  # interwiki wiki name
