### ISSUE TITLE
creation of local docs yields random `failed to import` messages

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#1145]
Running `./m docs` multiple times yields different failed to import messages. This does not seem to change the number of bytes in the _build directory, nor number of files and directories created.

Try 1 on pythonanywhere.com:

    Creating file docs/devel/api/moin.rst.
    Creating file docs/devel/api/moin.apps.rst.
    Creating file docs/devel/api/moin.apps.admin.rst.
    Creating file docs/devel/api/moin.apps.feed.rst.
    Creating file docs/devel/api/moin.apps.frontend.rst.
    Creating file docs/devel/api/moin.apps.misc.rst.
    Creating file docs/devel/api/moin.apps.serve.rst.
    Creating file docs/devel/api/moin.auth.rst.
    Creating file docs/devel/api/moin.config.rst.
    Creating file docs/devel/api/moin.constants.rst.
    Creating file docs/devel/api/moin.converters.rst.
    Creating file docs/devel/api/moin.datastructures.rst.
    Creating file docs/devel/api/moin.datastructures.backends.rst.
    Creating file docs/devel/api/moin.i18n.rst.
    Creating file docs/devel/api/moin.items.rst.
    Creating file docs/devel/api/moin.macros.rst.
    Creating file docs/devel/api/moin.mail.rst.
    Creating file docs/devel/api/moin.scripts.rst.
    Creating file docs/devel/api/moin.scripts.account.rst.
    Creating file docs/devel/api/moin.scripts.maint.rst.
    Creating file docs/devel/api/moin.scripts.migration.rst.
    Creating file docs/devel/api/moin.scripts.migration.moin19.rst.
    Creating file docs/devel/api/moin.search.rst.
    Creating file docs/devel/api/moin.security.rst.
    Creating file docs/devel/api/moin.signalling.rst.
    Creating file docs/devel/api/moin.storage.rst.
    Creating file docs/devel/api/moin.storage.backends.rst.
    Creating file docs/devel/api/moin.storage.middleware.rst.
    Creating file docs/devel/api/moin.storage.stores.rst.
    Creating file docs/devel/api/moin.themes.rst.
    Creating file docs/devel/api/moin.utils.rst.
    Creating file docs/devel/api/modules.rst.
    sphinx-build -b html -d _build/doctrees   . _build/html
    Running Sphinx v4.3.0
    WARNING: logo file 'Logo_MoinMoin.png' does not exist
    WARNING: favicon file 'favicon.ico' does not exist
    loading pickled environment... done
    [autosummary] generating autosummary for: admin/backup.rst, admin/changes.rst, admin/configure.rst, admin/index.rst, admin/install.rst, admin/password-reset.rst, admin/requirements.rst, admin/serve.rst, admin/upgrade.rst, devel/api/modules.rst, ..., user/markdown.rst, user/markups.rst, user/mediawiki.rst, user/moinwiki.rst, user/namespaces.rst, user/rest.rst, user/search.rst, user/subscriptions.rst, user/templates_metadata.rst, user/upload.rst
    2021-11-20 19:16:55,720 ERROR moin.auth.ldap_login:31 You need to have python-ldap installed (No module named 'ldap').
    Failed to import 'moin.macros.Anchor': no module named moin.macros.Anchor
    Failed to import 'moin.macros.Date': no module named moin.macros.Date
    Failed to import 'moin.macros.DateTime': no module named moin.macros.DateTime
    Failed to import 'moin.macros.FontAwesome': no module named moin.macros.FontAwesome
    Failed to import 'moin.macros.GetText': no module named moin.macros.GetText
    Failed to import 'moin.macros.GetVal': no module named moin.macros.GetVal
    Failed to import 'moin.macros.HighlighterList': no module named moin.macros.HighlighterList
    Failed to import 'moin.macros.Icon': no module named moin.macros.Icon
    Failed to import 'moin.macros.ItemList': no module named moin.macros.ItemList
    Failed to import 'moin.macros.MailTo': no module named moin.macros.MailTo
    Failed to import 'moin.macros.RandomItem': no module named moin.macros.RandomItem
    Failed to import 'moin.macros.ShowIcons': no module named moin.macros.ShowIcons
    Failed to import 'moin.macros.Verbatim': no module named moin.macros.Verbatim
    Failed to import 'moin.items.blog': no module named moin.items.blog
    Failed to import 'moin.items.content': no module named moin.items.content
    Failed to import 'moin.items.ticket': no module named moin.items.ticket
    Failed to import 'moin.items': no module named moin.items
    Failed to import 'moin.apps.frontend.views': no module named moin.apps.frontend.views
    Failed to import 'moin.apps.frontend': no module named moin.apps.frontend
    Failed to import 'moin.apps.feed.views': no module named moin.apps.feed.views
    Failed to import 'moin.apps.feed': no module named moin.apps.feed
    Failed to import 'moin.auth.ldap_login': no module named moin.auth.ldap_login
    Failed to import 'moin.apps.admin.views': no module named moin.apps.admin.views
    Failed to import 'moin.apps.admin': no module named moin.apps.admin
    Failed to import 'moin.config.moin2wsgi': no module named moin.config.moin2wsgi
    Failed to import 'moin.utils.SubProcess': no module named moin.utils.SubProcess

    Build finished. The HTML pages are in _build/html.

Try 2 on pythonanywhere.com:

    Creating file docs/devel/api/moin.rst.
    Creating file docs/devel/api/moin.apps.rst.
    Creating file docs/devel/api/moin.apps.admin.rst.
    Creating file docs/devel/api/moin.apps.feed.rst.
    Creating file docs/devel/api/moin.apps.frontend.rst.
    Creating file docs/devel/api/moin.apps.misc.rst.
    Creating file docs/devel/api/moin.apps.serve.rst.
    Creating file docs/devel/api/moin.auth.rst.
    Creating file docs/devel/api/moin.config.rst.
    Creating file docs/devel/api/moin.constants.rst.
    Creating file docs/devel/api/moin.converters.rst.
    Creating file docs/devel/api/moin.datastructures.rst.
    Creating file docs/devel/api/moin.datastructures.backends.rst.
    Creating file docs/devel/api/moin.i18n.rst.
    Creating file docs/devel/api/moin.items.rst.
    Creating file docs/devel/api/moin.macros.rst.
    Creating file docs/devel/api/moin.mail.rst.
    Creating file docs/devel/api/moin.scripts.rst.
    Creating file docs/devel/api/moin.scripts.account.rst.
    Creating file docs/devel/api/moin.scripts.maint.rst.
    Creating file docs/devel/api/moin.scripts.migration.rst.
    Creating file docs/devel/api/moin.scripts.migration.moin19.rst.
    Creating file docs/devel/api/moin.search.rst.
    Creating file docs/devel/api/moin.security.rst.
    Creating file docs/devel/api/moin.signalling.rst.
    Creating file docs/devel/api/moin.storage.rst.
    Creating file docs/devel/api/moin.storage.backends.rst.
    Creating file docs/devel/api/moin.storage.middleware.rst.
    Creating file docs/devel/api/moin.storage.stores.rst.
    Creating file docs/devel/api/moin.themes.rst.
    Creating file docs/devel/api/moin.utils.rst.
    Creating file docs/devel/api/modules.rst.
    sphinx-build -b html -d _build/doctrees   . _build/html
    Running Sphinx v4.3.0
    WARNING: logo file 'Logo_MoinMoin.png' does not exist
    WARNING: favicon file 'favicon.ico' does not exist
    loading pickled environment... failed
    failed: 'str' object has no attribute '__dict__'
    [autosummary] generating autosummary for: admin/backup.rst, admin/changes.rst, admin/configure.rst, admin/index.rst, admin/install.rst, admin/password-reset.rst, admin/requirements.rst, admin/serve.rst, admin/upgrade.rst, devel/api/modules.rst, ..., user/markdown.rst, user/markups.rst, user/mediawiki.rst, user/moinwiki.rst, user/namespaces.rst, user/rest.rst, user/search.rst, user/subscriptions.rst, user/templates_metadata.rst, user/upload.rst
    2021-11-20 19:09:47,013 ERROR moin.auth.ldap_login:31 You need to have python-ldap installed (No module named 'ldap').
    Failed to import 'moin.apps.feed.views': no module named moin.apps.feed.views
    Failed to import 'moin.apps.feed': no module named moin.apps.feed
    Failed to import 'moin.macros.Anchor': no module named moin.macros.Anchor
    Failed to import 'moin.macros.Date': no module named moin.macros.Date
    Failed to import 'moin.macros.DateTime': no module named moin.macros.DateTime
    Failed to import 'moin.macros.FontAwesome': no module named moin.macros.FontAwesome
    Failed to import 'moin.macros.GetText': no module named moin.macros.GetText
    Failed to import 'moin.macros.GetVal': no module named moin.macros.GetVal
    Failed to import 'moin.macros.HighlighterList': no module named moin.macros.HighlighterList
    Failed to import 'moin.macros.Icon': no module named moin.macros.Icon
    Failed to import 'moin.macros.ItemList': no module named moin.macros.ItemList
    Failed to import 'moin.macros.MailTo': no module named moin.macros.MailTo
    Failed to import 'moin.macros.RandomItem': no module named moin.macros.RandomItem
    Failed to import 'moin.macros.ShowIcons': no module named moin.macros.ShowIcons
    Failed to import 'moin.macros.Verbatim': no module named moin.macros.Verbatim
    Failed to import 'moin.scripts.maint.dump_html': no module named moin.scripts.maint.dump_html
    Failed to import 'moin.auth.ldap_login': no module named moin.auth.ldap_login
    Failed to import 'moin.utils.SubProcess': no module named moin.utils.SubProcess
    Failed to import 'moin.config.moin2wsgi': no module named moin.config.moin2wsgi

    Build finished. The HTML pages are in _build/html.

Try 3 on Windows:

        Creating file docs/devel/api\moin.rst.
        Creating file docs/devel/api\moin.apps.rst.
        Creating file docs/devel/api\moin.apps.admin.rst.
        Creating file docs/devel/api\moin.apps.feed.rst.
        Creating file docs/devel/api\moin.apps.frontend.rst.
        Creating file docs/devel/api\moin.apps.misc.rst.
        Creating file docs/devel/api\moin.apps.serve.rst.
        Creating file docs/devel/api\moin.auth.rst.
        Creating file docs/devel/api\moin.config.rst.
        Creating file docs/devel/api\moin.constants.rst.
        Creating file docs/devel/api\moin.converters.rst.
        Creating file docs/devel/api\moin.datastructures.rst.
        Creating file docs/devel/api\moin.datastructures.backends.rst.
        Creating file docs/devel/api\moin.i18n.rst.
        Creating file docs/devel/api\moin.items.rst.
        Creating file docs/devel/api\moin.macros.rst.
        Creating file docs/devel/api\moin.mail.rst.
        Creating file docs/devel/api\moin.scripts.rst.
        Creating file docs/devel/api\moin.scripts.account.rst.
        Creating file docs/devel/api\moin.scripts.maint.rst.
        Creating file docs/devel/api\moin.scripts.migration.rst.
        Creating file docs/devel/api\moin.scripts.migration.moin19.rst.
        Creating file docs/devel/api\moin.search.rst.
        Creating file docs/devel/api\moin.security.rst.
        Creating file docs/devel/api\moin.signalling.rst.
        Creating file docs/devel/api\moin.storage.rst.
        Creating file docs/devel/api\moin.storage.backends.rst.
        Creating file docs/devel/api\moin.storage.middleware.rst.
        Creating file docs/devel/api\moin.storage.stores.rst.
        Creating file docs/devel/api\moin.themes.rst.
        Creating file docs/devel/api\moin.utils.rst.
        Creating file docs/devel/api\modules.rst.
        Running Sphinx v3.4.3
        making output directory... done
        WARNING: logo file 'Logo_MoinMoin.png' does not exist
        WARNING: favicon file 'favicon.ico' does not exist
        [autosummary] generating autosummary for: admin\backup.rst, admin\changes.rst, admin\configure.rst, admin\index.rst, admin\install.rst, admin\password-reset.rst, admin\requirements.rst, admin\serve.rst, admin\upgrade.rst, devel\api\modules.rst, ..., user\markdown.rst, user\markups.rst, user\mediawiki.rst, user\moinwiki.rst, user\namespaces.rst, user\rest.rst, user\search.rst, user\subscriptions.rst, user\templates_metadata.rst, user\upload.rst
        Failed to import 'moin.apps.admin.views': no module named moin.apps.admin.views
        Failed to import 'moin.apps.admin': no module named moin.apps.admin
        Failed to import 'moin.config.moin2wsgi': no module named moin.config.moin2wsgi
        Failed to import 'moin.utils.SubProcess': no module named moin.utils.SubProcess
        2021-11-20 10:27:05,823 ERROR moin.auth.ldap_login:31 You need to have python-ldap installed (No module named 'ldap').
        Failed to import 'moin.auth.ldap_login': no module named moin.auth.ldap_login
        2021-11-20 10:27:12,248 ERROR moin.auth.ldap_login:31 You need to have python-ldap installed (No module named 'ldap').

        Build finished. The HTML pages are in _build/html.

**Comment by UlrichB22** [comment]
On a Debian 11 I had similar failures. This can be suppressed by setting 
autosummary_generate = False 
at the end of docs/conf.py
I'm not sure if anyone needs the output. It would be more effort to fix.
