### ISSUE TITLE
MonthCalendar macro for moin2

### ISSUE THREAD

**Issue by abirke** [moinwiki/moin#1174]
Hi everyone,

we are currently looking into migrating to moin-2.0 and checking what
functionality might be missing.

We'd like to continue using the MonthCalendar macro from version 1.9
which we have ported locally and it runs fine for the basics. There are
a few question marks however on how to continue on the integration.

**Backwards compatibility of the macro syntax**
The macro syntax so far is a bit bulky with unnamed parameters.
```
<<MonthCalendar(,2023,7,,,1)>>
```
Is there any consent on how to deal with this when migrating? Should a
new version of the macro support the previous syntax while offering
named parameters for improved readibility in the future? Or would you
prefer breaking backwards compatibility and implementing a migration of
the old syntax to something new within the migration scripts?

**Next/previous month links**
In a first attempt, we thought of not porting the "Next month" and
"Previous month" links which can get complicated especially with
multiple calendars on one page. Would that be okay?

**Setting style attributes**
Building tables in version 2.0 seems to be done through DOM rather than
manual assembly of the HTML tags which is nice. Can we assign some
useful CSS classes through the `attrib` fields of the objects or have we
missed any templating engine or alike that is supposed to take care of
the HTML and CSS output?

Happy to hear your thoughts on this.

Best regards
André

**Comment by RogerHaase** [comment]
If you can improve the syntax and handle the changes in the import19
conversion, that would be ideal. However, there is currently no code to
support macro conversion. There is one other macro that would benefit
from macro conversion: moin1.9 <<PageList>> to moin2 <<ItemList>>.

Second best would be to support the old syntax and some variety of named
parameters.

Third way is to just keep the old parameters as is.

It is OK for early versions of the macro to miss some features. Moin2
converters/include.py misses some features of moin1.9 macro/include.py.

Adding classes through the attrib fields is the usual way to add styling.

As I have never used the MonthCalendar macro, I would defer to you for the
design of named parameters. ThomasWaldmann may have some ideas.

Roger Haase

**Comment by abirke** [comment]
Great, thanks for the advice. I'll give it a few more thoughts and try to see whether there's a solution to macro migration that I'd feel comfortable with implementing.

I'll keep you posted.

Thanks again,
André

**Comment by RogerHaase** [comment]
I looked at import19.py. I think you want to insert the macro conversion
code (or probably a call to new code) between these 2 lines near ~139.

            dom = self.conv_in(data_in, CONTENTTYPE_MOINWIKI)
            out = self.conv_out(dom)

Look at the bottom of converters/macro.py (where dom is renamed tree). You
want to create something similar to the `__call__` and `recurse` methods
where you walk the tree, find the macro of interest, and replace the node
with the new parameters.

That's my best guess.

Roger Haase

**Comment by abirke** [comment]
Hi Roger,

cool, thanks. This is reassuring. I've been looking into this for a bit tonight and I have narrowed it down to that same spot.

I'll try find a rather generic way of introducing migrations for the different macros, so the functionality can be used equally for different macros. As soon as I have a better idea of the solution, I'll upload something to review. It'll take me a few moments to use the existing macro parsing for conversion in the right way, but I'll get there ;)

Thanks again for helping me get started on this.

André

**Comment by RogerHaase** [comment]
Forgot - assuming the conversion code will work someday, then you could
write the new MonthCalendar macro with the preferred syntax first, and
leave the conversion step for later.

Roger Haase

**Comment by RogerHaase** [comment]
Documentation for macros is currently in 3 places:

    moin/docs/user/moinwiki.rst near line 779
    moin/docs/user/creolewiki.rst near line 346

The duplication of the 2 tables and notes should someday be eliminated

The 3rd copy is in moin/src/moin/contrib/sample-backup.moin

To update, from an empty wiki instance

    ./m sample
    ./m run

make changes, then back to terminal

    ctrl-c
    moin --maint-reduce-revisions
    ./m backup src/moin/contrib/sample-backup.moin

commit, push

**Comment by UlrichB22** [comment]
Update of sample backup will follow.
