### ISSUE TITLE
Remove all support for IE browsers, including IE11

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#1193]
Per https://techcommunity.microsoft.com/t5/windows-it-pro-blog/internet-explorer-11-desktop-app-retirement-faq/ba-p/2366549 on May 19 2021.

"""
As announced today, Microsoft Edge with IE mode is officially replacing the Internet Explorer 11 desktop application on Windows 10. As a result, the Internet Explorer 11 desktop application will go out of support and be retired on June 15, 2022 for certain versions of Windows 10.
"""

Per https://kinsta.com/browser-market-share/, IE has a market share of appx 2%, mostly businesses.

The most tedious task will be dropping all explicit color references in common.css and using variables.css instead. Change all attributes similar to:

    color: #ff2727; color: var(--error);

with:

    color: var(--error);

variables.css defines 'error' as:

        --error: #FF2727;  /* syntax error messages generated by converters */

**Comment by ThomasWaldmann** [comment]
Finally, one less PITA. :-)
