### ISSUE TITLE
quickinstall.py fails for setuptools 44.1.1 with setuptools_scm 6.x

### ISSUE THREAD

**Issue by UlrichB22** [moinwiki/moin#1219]
The installation of a development environment on Debian 11 (bullseye) according to 
https://moin-20.readthedocs.io/en/latest/admin/install.html#installation-for-developers
fails in quickinstall.py with message

```
<installpath>/moin/.eggs/setuptools_scm-6.4.2-py3.9.egg/setuptools_scm/integration.py:17: RuntimeWarning: 
ERROR: setuptools==44.1.1 is used in combination with setuptools_scm>=6.x
```

**Comment by RogerHaase** [comment]
Is there more to do or can this be closed?
