### ISSUE TITLE
Slow response for non existing items 

### ISSUE THREAD

**Issue by UlrichB22** [moinwiki/moin#1225]
On a migrated wiki with about 1300 items / 7500 revisions it takes 10 seconds to get the 'create new item named ...' page response for an invalid url / nonexisting item. 

The problem is caused by find_matches() in moin/items/__init__.py . The runtime depends on the total number of wiki items. The function should be replaced by an index search.

**Comment by RogerHaase** [comment]
Nice, I can notice the difference with my test wiki of 70 items
