### ISSUE TITLE
item-put makes cousin with same name disappear from default namespace

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#1233]
Loading 10 help items into the help-en namespace will make items with the same name in the default namespace "disappear". 22 other items in the default namespace are not affected.

To reproduce:

Pull recent updates that add help files for editors and follow the instructions near the bottom of #1155.

Create a wiki instance and load sample items into the default namespace.

Use moin item-put to load a specific help file

    moin item-put -m /<path>/moin/src/moin/help/en/OtherTextItems.meta -d /<path>/moin/src/moin/help/en/OtherTextItems.data 

The item OtherTextItems will be loaded into the /wiki/data/help-en namespace; but the item with the same name will disappear from the default namespace.  This can be verified by starting the built-in server and displaying the index of all items:

    http://127.0.0.1:8080/+index/all

Performing an index build will make the item reappear in the default namespace:

    moin index-build -i

The error was discovered by loading a wiki instance with the usual sample data, and then loading the help-common and help-en namespaces

    moin load-help -n common
    moin load-help -n en

The above made 10 items in the default namespace disappear. The disappearing items are always the same 10 items. The items do not seem to have any unique attributes.

The 10 items are:

* OtherTextItems
* OtherTextItems/CSV
* OtherTextItems/Diff
* OtherTextItems/IRC
* OtherTextItems/PlainText
* OtherTextItems/Python
* MoinWikiMacros/MonthCalendar
* TemplateSample
* mediawiki
* moin/HighlighterList

The problem occurs on both windows and ubuntu.

**Comment by UlrichB22** [comment]
These items have the same revid in the meta data. E.g.
moin/HighlighterList has `"revid": "09275f9c15164432a819b665f2f2362e" ` 
in the sample data and in help/en/moin%252fHighlighterList.meta

The overwrite option should be set to False here to generate a new revid:

https://github.com/moinwiki/moin/blob/9adb237989107d53faa5a007d2e7bda355c01726/src/moin/scripts/maint/modify_item.py#L135

**Comment by RogerHaase** [comment]
Thanks for the help!
