### ISSUE TITLE
sphinx 4.3.0 requires docutils<0.18,>=0.14

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#1240]
From the log:

    ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
    sphinx 4.3.0 requires docutils<0.18,>=0.14, but you have docutils 0.18.1 which is incompatible.
    sphinx-rtd-theme 1.0.0 requires docutils<0.18, but you have docutils 0.18.1 which is incompatible.
    Successfully installed Babel-2.9.1 moin-2.0.0a11.dev133+g919bbf40.d20220507

**Comment by RogerHaase** [comment]
Running "./m extras" now updates Sphinx to 4.5.0, but issue remains the same.

**Comment by RogerHaase** [comment]
Must wait for sphinx-rtd-theme > 1.0.0

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sphinx-rtd-theme 1.0.0 requires docutils<0.18, but you have docutils 0.19 which is incompatible.

**Comment by UlrichB22** [comment]
This is fixed with #1338. We are now using 

- Babel 2.10.3
- docutils 0.18.1
- sphinx 6.1.3
- sphinx-rtd-theme 1.2.0rc3
