### ISSUE TITLE
test_indexing.py runs more than 60 secs 

### ISSUE THREAD

**Issue by UlrichB22** [moinwiki/moin#1246]
The tests with src/moin/storage/middleware/_tests/test_indexing.py and test_protecting.py are very slow and always need more than 60 seconds.

E.g. the following statement need 20 seconds:

https://github.com/moinwiki/moin/blob/69af2b991a0aa962d1b33b147623eec5e1f3c6ce/src/moin/storage/middleware/_tests/test_indexing.py#L99

The reason is that this function is called with a non-existent revision, which triggers the timeout function

https://github.com/moinwiki/moin/blob/69af2b991a0aa962d1b33b147623eec5e1f3c6ce/src/moin/storage/middleware/indexing.py#L99

I have no idea how to fix this, please help.

**Comment by RogerHaase** [comment]
Good catch!  I can reproduce the error. 

Looks like the bug was introduced as a fix to #479 and #480 back in 2019-04-08 and 09.

**Comment by RogerHaase** [comment]
UlrichB22 - does this issue affect only tests?  Any relation to #1225?

I am thinking one solution is to pass the problem on to wiki admins by adding the timeout duration and number of retries to wikiconfig.py.

**Comment by UlrichB22** [comment]
I think this is only related to testing, as the function is not normally used for non-existent revisions. Is there another easy way to check if the revision of the item was deleted successfully? 

#1225 is a different problem.
