### ISSUE TITLE
Wrong itemlinks if using relative path in namespaces

### ISSUE THREAD

**Issue by UlrichB22** [moinwiki/moin#1258]
Relative link paths are not converted correctly in meta data.

E.g. the item help-en/Home uses following link

` * [[../moin|Moin Wiki markup item]]`
 
In metadata this is shown as moin instead of help-en/moin. 
As a result, the help-en/moin element is included in the list of orphans:

http://localhost:8080/+orphans

The Code is around this block:

https://github.com/moinwiki/moin/blob/136ee26cb16f00d6965cce278e80d1a39f2b9eaa/src/moin/storage/middleware/indexing.py#L324

Need some help to fix.

**Comment by RogerHaase** [comment]
The metadata for help-en/moin has a name "moin" and a Namespace "help-en" so it is correct.

I think the problem is in apps/frontend/views.py ~1740. "def orphaned_items" and its helpers does not support namespaces.

**Comment by UlrichB22** [comment]
To reproduce I used a new empty wiki with only help-en and help-common loaded. If you look at meta data http://localhost:8080/+meta/help-en/Home you will see a lot of invalid links in the list of Item Links.

According to http://localhost:8080/help-en/moin every link with a simple itemname without slashes is located in default namespace. Every item link for the same namespace is preceded with the namespace name. This implies, that relative paths to siblings need to be translated to namespace/itemname within metadata.  

The list of orphans uses the itemlink meta data from index only, this is perfect.

**Comment by RogerHaase** [comment]
I misunderstood, agree the metadata for Item Links and Item Transclusions is incorrect - each link should have the complete path.

**Comment by RogerHaase** [comment]
I think a possible fix for Item Links is in /storage/middleware/indexing.py near line 1159.  But still testing. Also finding doc errors in moin help page.

    def preprocess(self, meta, data):
        """
        preprocess a revision before it gets stored and put into index.
        """
        # ~ content = convert_to_indexable(meta, data, self.name, is_new=True)
        content = convert_to_indexable(meta, data, self.fqname.fullname, is_new=True)
        return meta, data, content

**Comment by RogerHaase** [comment]
The above fix creates another problem. After loading the help-en namespace in a new wiki, the show meta for +meta/help-en/moin displays Item Links as:

Item Links: help-en/@itemid/0eb80a06571748cd9ca07668681e34df/HighlighterList, help-en/@itemid/creole, help-en/@itemid/Home, help-en/@itemid/moin/HighlighterList, help-en/@itemid/MoinWikiMacros, help-en/creole, help-en/Home, help-en/Home/subitem, help-en/moin/MissingSubitem, Home, MissingPage

Editing and saving help-en/moin returns Item Links in +meta/help-en/moin to normal:

Item Links: help-en/creole, help-en/Home, help-en/Home/subitem, help-en/moin/HighlighterList, help-en/moin/MissingSubitem, help-en/MoinWikiMacros, Home, MissingPage

The above occurs after both `moin item-put` and `moin load-help` are run.

**Comment by UlrichB22** [comment]
#1260 should fix the problems with itemids in ItemLinks. I will also add a test function and correct the help links.
Some questions to discuss:

- I would like to remove the item_name parm from convert_to_indexable definition. This is only used in apps/views.py at `@frontend.route('/+indexable`. Can we remove this route as it is marked as temporary? 

- Is the try block with applying `item_name = 'DoesNotExist'` in convert_to_indexable still needed? The name value in meta should always be valid at this stage.

**Comment by RogerHaase** [comment]
I am thinking the whole try block:

        try:
            if NAMESPACE in meta and meta[NAMESPACE] is not None:
                item_name = meta[NAMESPACE] + '/' + meta[NAME][0]
            else:
                item_name = meta[NAME][0]
        except IndexError:
            item_name = 'DoesNotExist'

can just be replaced with:

        item_name = meta[NAMESPACE] + '/' + meta[NAME][0]

where the leading / when the NAMESPACE == "" seems wrong but I cannot make it fail. This is what your 1260 pull request does because the NAMESPACE is never None.

If you agree, cancel the 1260 pull request and push the above.

===
OK to remove the item_name parm as a separate pull request.

===
I have several changes to the moin and creole help pages, will push them in a few hours.

**Comment by UlrichB22** [comment]
I had to add the `if NAMESPACE in meta` because most of the tests in test_indexing.py failed.
Otherwise we need to extend the dict in all the store_revision() calls there as follows 
`item.store_revision(dict(name=[item_name, ], namespace=''), ...)`

Still looking for a better solution.
