### ISSUE TITLE
remove get_names procedure from storage/middleware/indexing.py

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#1262]
Obsolete code that was useful when meta[NAME]  was being converted from a string to list of strings. Near line 122.

**Comment by coryfink** [comment]
I can look into this

**Comment by coryfink** [comment]
I see the `get_names` procedure is being called in the `convert_to_indexable` procedure- can both be removed?

**Comment by RogerHaase** [comment]
#1268 will likely remove get_names from convert_to_indexable.  So wait for that patch.

In the meantime, near line 1045 there is:

    @property
    def names(self):
        return get_names(self.meta)

Make that return the equivalent of get_names and get tests to run successfully.

Then wait for #1268, pull the changes, remove get_names(), run tests, commit, push

Thanks for helping!

**Comment by UlrichB22** [comment]
Usage of get_names has been removed from convert_to_indexable in #1263.
