### ISSUE TITLE
Quickinstall not working on Ubuntu 22.04 Lts Desktop

### ISSUE THREAD

**Issue by JanHoefelmeyer** [moinwiki/moin#1311]
I've tried setting up Moin2 on Windows 10 and Ubuntu 20.04 (lts) with no problems. Trying to set it up on Ubuntu 22.04 (lts) fails with no error messages given. The venv is supposedly created, but trying to use any further commands (e.g. sample) just leads to an error telling me that there is no such command.

Edit: I should mention that the entire log is empty. Even the messages indicating a successful creation are not present.

**Comment by UlrichB22** [comment]
I tested with a fresh installed Ubuntu 22.04 Server version. 
quickinstall.py has complained about missing packages, you find the full log output in a file called m-quickinstall.txt.
After running
```
sudo apt-get install python3.10-venv
sudo apt-get install python3-pip
```
quickinstall was running successful. Afterwards you need to activate the venv and can proceed with instance creation and more as described in https://moin-20.readthedocs.io/en/latest/admin/install.html?highlight=venv#creating-a-wiki-instance .

**Comment by UlrichB22** [comment]
I can reproduce with the desktop version. Can be further analysed using pycharm ->   https://moinmo.in/MoinMoin2/IdeSetup .

**Comment by JanHoefelmeyer** [comment]
Weirdly enough, trying to execute the script with pycharm seems to work differently. I got the error message of ensurepip not being enabled. After running 
```sudo apt-get install python3-venv```
trying to run quickinstall.py still did not seem to work, as it was once again completed without logs in 0:00:00.

However, running it through the debugger apparently did work, as it took 30 seconds and finished with the correct messages. After that, I am now able to create and run a wiki.

**Comment by UlrichB22** [comment]
Problem seems to be related to recursively opening the logfile and redirecting stdout/stderr a 2nd time. Can you check this fix:
https://github.com/UlrichB22/moin/commit/917a3e332e12ee60c26861a91983f573f0a5362f

Works for me on Ubuntu 22.04 desktop. Need to be also tested on Windows, I have no such environment.

**Comment by JanHoefelmeyer** [comment]
Works on Windows. Need to test it on Ubuntu still, but I seem to have a problem with venv atm (unrelated to moin, since I can't create a venv even without the skript at the moment.) ((Error when creating venv, Error: Command '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1) despite venv and pip being installed. Will try to fix this error and then ammend or edit this comment.)

**Comment by RogerHaase** [comment]
Works  on Windows 10 for me.

**Comment by JanHoefelmeyer** [comment]
Works for me on Windows 10, Ubuntu 20.04 lts Desktop and Ubuntu 22.04 lts Desktop.
So this issue seems to be fixed. Tyvm for the help-
