### ISSUE TITLE
deprecation warnings after running "m quickinstall" to update packages.

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#1320]
These packages were updated:  pytz, setuptools, pycryptodome, lxml, greenlet, chardet, sqlalchemy by running "m quickinstall".

These warning were logged after running tests:

 C:\GIT\moin\.tox\py310\lib\site-packages\flask_caching\__init__.py:158: DeprecationWarning: Using the initialization functions in flask_caching.backend is deprecated.  Use the a full path to backend classes directly.
    warnings.warn(

.tox/py310/lib/site-packages/moin/apps/frontend/_tests/test_frontend.py: 124 warnings
  C:\GIT\moin\.tox\py310\lib\site-packages\moin\themes\topside\templates\layout.html:153: DeprecationWarning: 'soft_unicode' has been renamed to 'soft_str'. The old name will be removed in MarkupSafe 2.1.

.tox/py310/lib/site-packages/moin/storage/stores/_tests/test_fs.py::test_create[BytesStore]
  C:\GIT\moin\.tox\py310\lib\site-packages\_pytest\python.py:199: PytestReturnNotNoneWarning: Expected None, but .tox/py310/lib/site-packages/moin/storage/stores/_tests/test_fs.py::test_create[BytesStore] returned <moin.storage.stores.fs.BytesStore object at 0x0000011279CA3610>, which will be an error in a future version of pytest.  Did you mean to use `assert` instead of `return`?
    warnings.warn(

.tox/py310/lib/site-packages/moin/storage/stores/_tests/test_fs.py::test_create[FileStore]
  C:\GIT\moin\.tox\py310\lib\site-packages\_pytest\python.py:199: PytestReturnNotNoneWarning: Expected None, but .tox/py310/lib/site-packages/moin/storage/stores/_tests/test_fs.py::test_create[FileStore] returned <moin.storage.stores.fs.FileStore object at 0x0000011279D6B400>, which will be an error in a future version of pytest.  Did you mean to use `assert` instead of `return`?
    warnings.warn(

.tox/py310/lib/site-packages/moin/storage/stores/_tests/test_memory.py::test_create[BytesStore]
  C:\GIT\moin\.tox\py310\lib\site-packages\_pytest\python.py:199: PytestReturnNotNoneWarning: Expected None, but .tox/py310/lib/site-packages/moin/storage/stores/_tests/test_memory.py::test_create[BytesStore] returned <moin.storage.stores.memory.BytesStore object at 0x0000011279A92B00>, which will be an error in a future version of pytest.  Did you mean to use `assert` instead of `return`?
    warnings.warn(

.tox/py310/lib/site-packages/moin/storage/stores/_tests/test_memory.py::test_create[FileStore]
  C:\GIT\moin\.tox\py310\lib\site-packages\_pytest\python.py:199: PytestReturnNotNoneWarning: Expected None, but .tox/py310/lib/site-packages/moin/storage/stores/_tests/test_memory.py::test_create[FileStore] returned <moin.storage.stores.memory.FileStore object at 0x00000112799E9AE0>, which will be an error in a future version of pytest.  Did you mean to use `assert` instead of `return`?
    warnings.warn(

.tox/py310/lib/site-packages/moin/storage/stores/_tests/test_sqla.py::test_create[BytesStore]
  C:\GIT\moin\.tox\py310\lib\site-packages\_pytest\python.py:199: PytestReturnNotNoneWarning: Expected None, but .tox/py310/lib/site-packages/moin/storage/stores/_tests/test_sqla.py::test_create[BytesStore] returned <moin.storage.stores.sqla.BytesStore object at 0x000001127860C670>, which will be an error in a future version of pytest.  Did you mean to use `assert` instead of `return`?
    warnings.warn(

.tox/py310/lib/site-packages/moin/storage/stores/_tests/test_sqla.py::test_create[FileStore]
  C:\GIT\moin\.tox\py310\lib\site-packages\_pytest\python.py:199: PytestReturnNotNoneWarning: Expected None, but .tox/py310/lib/site-packages/moin/storage/stores/_tests/test_sqla.py::test_create[FileStore] returned <moin.storage.stores.sqla.FileStore object at 0x0000011279C32D10>, which will be an error in a future version of pytest.  Did you mean to use `assert` instead of `return`?
    warnings.warn(

.tox/py310/lib/site-packages/moin/storage/stores/_tests/test_sqlite.py::test_create[bytes_uncompressed]
  C:\GIT\moin\.tox\py310\lib\site-packages\_pytest\python.py:199: PytestReturnNotNoneWarning: Expected None, but .tox/py310/lib/site-packages/moin/storage/stores/_tests/test_sqlite.py::test_create[bytes_uncompressed] returned <moin.storage.stores.sqlite.BytesStore object at 0x0000011279C33C40>, which will be an error in a future version of pytest.  Did you mean to use `assert` instead of `return`?
    warnings.warn(

.tox/py310/lib/site-packages/moin/storage/stores/_tests/test_sqlite.py::test_create[bytes_compressed]
  C:\GIT\moin\.tox\py310\lib\site-packages\_pytest\python.py:199: PytestReturnNotNoneWarning: Expected None, but .tox/py310/lib/site-packages/moin/storage/stores/_tests/test_sqlite.py::test_create[bytes_compressed] returned <moin.storage.stores.sqlite.BytesStore object at 0x00000112798B82E0>, which will be an error in a future version of pytest.  Did you mean to use `assert` instead of `return`?
    warnings.warn(

.tox/py310/lib/site-packages/moin/storage/stores/_tests/test_sqlite.py::test_create[file_uncompressed]
  C:\GIT\moin\.tox\py310\lib\site-packages\_pytest\python.py:199: PytestReturnNotNoneWarning: Expected None, but .tox/py310/lib/site-packages/moin/storage/stores/_tests/test_sqlite.py::test_create[file_uncompressed] returned <moin.storage.stores.sqlite.FileStore object at 0x0000011279BB85E0>, which will be an error in a future version of pytest.  Did you mean to use `assert` instead of `return`?
    warnings.warn(

.tox/py310/lib/site-packages/moin/storage/stores/_tests/test_sqlite.py::test_create[file_compressed]
  C:\GIT\moin\.tox\py310\lib\site-packages\_pytest\python.py:199: PytestReturnNotNoneWarning: Expected None, but .tox/py310/lib/site-packages/moin/storage/stores/_tests/test_sqlite.py::test_create[file_compressed] returned <moin.storage.stores.sqlite.FileStore object at 0x0000011279798970>, which will be an error in a future version of pytest.  Did you mean to use `assert` instead of `return`?
    warnings.warn(

**Comment by UlrichB22** [comment]
There are 3 different types of warnings:

1. `flask_caching_init_.py:158: DeprecationWarning: Using the initialization functions in flask_caching.backend is deprecated.` This is related to flask-caching 1.9.1 and changes to the CACHE_TYPE values, see [flask-caching.readthedocs.io](https://flask-caching.readthedocs.io/en/latest/index.html#simplecache)

2. `moin\themes\topside\templates\layout.html:153: DeprecationWarning: 'soft_unicode' has been renamed to 'soft_str'. `

3. `PytestReturnNotNoneWarning: Expected None ... will be an error in a future version of pytest.` e.g. in  moin/storage/stores/_tests/test_fs.py::test_create[BytesStore]. This is related to pytest 7.2.0, see [docs.pytest.org](https://docs.pytest.org/en/stable/deprecations.html#returning-non-none-value-in-test-functions)

I will submit a PR for number 1 and 3. No idea for number 2 yet.
