### ISSUE TITLE
`moin load-help -n en ` yields bad output

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#1356]
To reproduce, load sample data, then do `moin load-help -n en`.

The loaded help-en meta data lacks the size attribute. This causes tracebacks in searches, help-en index, perhaps other places.

Bug is probably in my recent change to storage/backend/stores.py

**Comment by UlrichB22** [comment]
Is it an option to keep the values of SIZE and HASH_ALGORITHM from input file here:
https://github.com/moinwiki/moin/blob/c8614c7a6dc6fba721c989acb389eddbd9e0f526/src/moin/scripts/maint/modify_item.py#L75

**Comment by RogerHaase** [comment]
yes, your way is better. Thanks for hint.
