### ISSUE TITLE
Add cli command to create an initial welcome page on a newly created wiki

### ISSUE THREAD

**Issue by UlrichB22** [moinwiki/moin#1381]
After creating a new wiki, there should be a welcome page called 'Home'.

For users who want to try MoinMoin for the first time, there could be a simple command to create the instance, index and load the help pages and the welcome page. 

Maybe an option can be added to `moin create-instance` command to setup all the rest.

**Comment by UlrichB22** [comment]
The new command is `moin welcome`

Do we need to check if Home exists in default namespace before loading? What would be the easiest way to check?

**Comment by RogerHaase** [comment]
Checking for existing Home would be nice to have, in case wiki admin accidently runs create-instance on top of a existing wiki instance. Not sure how to check.

**Comment by UlrichB22** [comment]
Check added and tested for `moin welcome`.
Unfortunately this does not help when running `moin create-instance --full`.

While testing the CLI I found several commands that should get additional checks to prevent destroying items or an existing wiki. I will create a separate issue.
