### ISSUE TITLE
use namespaceid, not namespace name

### ISSUE THREAD

**Issue by ThomasWaldmann** [moinwiki/moin#139]
**[Original report](https://bitbucket.org/thomaswaldmann/moin-2.0/issue/139) by Thomas Waldmann (Bitbucket: [thomaswaldmann](https://bitbucket.org/thomaswaldmann), GitHub: [thomaswaldmann](https://github.com/thomaswaldmann)).**

----------------------------------------

this issue is for the namespace branch

we currently use namespace NAMES there, but for the same reasons we have all those other *ID things (e.g. USERID not user name), we should also use a NAMESPACEID (NSID) there, so that namespace renames are painlessly possible, because internally we only use the ID and also store only that NSID into the metadata of revisions, not the ns name.

**Comment by RogerHaase** [comment]
This needs more analysis:

* what are the changes to wikiconfig.py?
* what do URLs look like?
* what does the directory structure under /wiki/data/ look like?
* when is the NSID to namespace mapping created and where is it stored?
* what are the changes to whoosh searching

Is the intent to have a web page that would rename a namespace similar to renaming an item? 

An alternative to implementing NSID could be:
* add a command `moin dump-namespace --dest <filename>`
* add a command `moin restore-namespace --source <filename> --nsname <new ns name>`
* add a command `moin remove-namespace --nsname <old name>`

Then the process could be:
* stop server
* run `moin dump-namespace`
* run `moin remove-namespace`
* edit wikiconfig deleting old ns, adding new ns
* run `moin restore-namespace`
* run `moin index-build`
* restart server

**Comment by RogerHaase** [comment]
Agree this issue does not deserve milestone 2.0.0a1; but I want to do #1155 and fixing this will help.

Looking at code, an easier solution is to add options to `moin load`, no need for additional commands:
* `moin load --file <filename> --new-ns <new namespace> --old-ns <old namespace> --kill-ns <remove namespace>`

And the process becomes:
* stop server
* run `moin save`
* edit wikiconfig deleting old ns, adding new ns
* delete the data and index directories under wiki/
* run `moin index-create -s -i`
* run `moin load --file <filename> --new-ns <new namespace> --old-ns <old namespace> --kill-ns <remove ns>`
* run `moin index-build`
* restart server
