### ISSUE TITLE
extract_messages ignores javascript

### ISSUE THREAD

**Issue by UlrichB22** [moinwiki/moin#1427]
After running 
`python setup.py extract_messages` 
the messages from `templates/dictionary.js` are not included in `translations/MoinMoin.pot`.
If manually added to `translations/MoinMoin.pot` and `translations/de/LC_MESSAGES/messages.po` translations are displayed.

**Comment by RogerHaase** [comment]
`m coding_std` should detect those kinds of problems.

**Comment by UlrichB22** [comment]
In setup.py the type of templates/dictionary.js needs to be jinja2.
