### ISSUE TITLE
`moin create-instance --full --path <new-directory>` fails

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#1436]
The welcome page and the help pages are written (over) the directories in the CWD, not in the `<new-directory>`.

To create a new instance, one must do:

    moin create-instance --path <new-directory>
    cd <new-directory>
    moin welcome
    moin load-help -n en
    moin load-help -n common

**Comment by UlrichB22** [comment]
Tried to add in create_instance.py:88
```
        cwd_path = os.getcwd()
        if path != cwd_path:
            os.chdir(path)
```
But the index and storage still gets created in `src/moin/config`. The cause of this behavior seems to be that the config is read at the beginning of the command, before the instance is created.

Maybe we should just check and disallow using --full and --path together. The `create-instance`  is the only command with a path option. The docstring in wikiconfig.py advises to use the wikiconfig dir as CWD for all other commands:

https://github.com/moinwiki/moin/blob/94c665fdb72409f12a64dcf94c191e8e6acf4ac9/src/moin/config/wikiconfig.py#L64

Please advise.

**Comment by RogerHaase** [comment]
Maybe changing the CWD and starting a subprocess would work.  If not, disallow --full and --path.
