### ISSUE TITLE
drop support for TwickiDraw and AnyWikiDraw

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#1467]
Because TwickiDraw and AnyWikiDraw are written in Java and all modern browsers have dropped support for Java due to security concerns, there is no point in trying to support these obsolete drawing tools.

Attempts to create a new item results in an error:

    NOTE: You need a Java enabled browser to edit the drawing.

**Comment by UlrichB22** [comment]
I will work on this issue if it's OK.

**Comment by RogerHaase** [comment]
Great, I have not worked on this issue
