### ISSUE TITLE
GitHub has test failure after merge

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#1471]
Seems random, only Ubuntu has failure.

https://github.com/moinwiki/moin/actions/runs/5501625909/jobs/10025342573

    ...
    -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html   
    =========================== short test summary info ============================
    FAILED src/moin/cli/_tests/test_modify_item.py::test_validate_metadata_missing_rev_num - KeyError: 'rev_number'
    = 1 failed, 1725 passed, 20 skipped, 2 xfailed, 1440 warnings in 342.44s (0:05:42) =
    Error: Process completed with exit code 1.

**Comment by RogerHaase** [comment]
Failed a second time in a row. Ubuntu or Python 3.11 issue caused by recent change?

https://github.com/RogerHaase/moin/actions/runs/5522655708/jobs/10072550427

**Comment by UlrichB22** [comment]
In .github/workflows/ci.yml we can try to change the Python version for Ubuntu to 3.10 and use 3.11 on Windows. If the problem is related to 3.11, it will show up in the Windows tests.

**Comment by RogerHaase** [comment]
Swapped python versions per above, now have different failure on ubuntu prior to merge;

    =========================== short test summary info ============================
    FAILED src/moin/cli/_tests/test_modify_item.py::test_item_rev - AssertionError: assert 'MyPage version 1\r\n' == 'MyPage 
    version 2\r\n'
      - MyPage version 2
      ?                ^
      + MyPage version 1
      ?                ^
    = 1 failed, 1725 passed, 20 skipped, 2 xfailed, 1440 warnings in 375.17s (0:06:15) =

https://github.com/moinwiki/moin/actions/runs/5547582042/jobs/10129423062?pr=1475

Will merge to see what happens next.

**Comment by RogerHaase** [comment]
No failures after merge. Back to random failure, but a clue may be that when the tests for macos, windows, and ubuntu start, ubuntu frequently/always finishes first. If there is a lagging I/O maybe the ubuntu test is likely to fail more often.

**Comment by RogerHaase** [comment]
Ubuntu only failure again:  https://github.com/moinwiki/moin/actions/runs/5579775538/jobs/10195787767?pr=1477

    =========================== short test summary info ============================
    FAILED src/moin/cli/_tests/test_modify_item.py::test_item_rev - AssertionError: assert 'MyPage version 1\r\n' == 'MyPage version 2\r\n'
      - MyPage version 2
      ?                ^
      + MyPage version 1
      ?                ^
    FAILED src/moin/cli/_tests/test_modify_item.py::test_validate_metadata_missing_rev_num - KeyError: 'rev_number'
    = 2 failed, 1724 passed, 20 skipped, 2 xfailed, 1440 warnings in 348.86s (0:05:48) =
    Error: Process completed with exit code 1.

**Comment by RogerHaase** [comment]
Sometimes it breaks on windows:  https://github.com/RogerHaase/moin/actions/runs/5603630779/jobs/10250518035

    =========================== short test summary info ===========================
    FAILED src/moin/cli/_tests/test_modify_item.py::test_item_rev - AssertionError: assert 'MyPage version 1\r\n' == 'MyPage version 2\r\n'
      - MyPage version 2

      ?                ^
      + MyPage version 1

      ?                ^
    = 1 failed, 1725 passed, 20 skipped, 2 xfailed, 1440 warnings in 429.79s (0:07:09) =
    Error: Process completed with exit code 1.

**Comment by UlrichB22** [comment]
I am always getting these failures now on my debian system: 

```
src/moin/cli/_tests/test_modify_item.py ..F...FF  
FAILED src/moin/cli/_tests/test_modify_item.py::test_dump_help - AssertionError: assert {'archive.tar...vg.data', ...} == {'archive.tar...ng.data', ...}
FAILED src/moin/cli/_tests/test_modify_item.py::test_validate_metadata - AssertionError: assert 'parentid_err...ion_number: 2' == 'parentid_err...ion_number: 1'
FAILED src/moin/cli/_tests/test_modify_item.py::test_validate_metadata_missing_rev_num - KeyError: 'rev_number'
```
My recommendation is to deactivate the failing tests for now. It will need some time to find the real cause.

**Comment by RogerHaase** [comment]
A new variation, test cancelled after running more than 1 hour:

https://github.com/RogerHaase/moin/actions/runs/5834185500/job/15823191015

Sometimes a similar problem occurs on Windows 10. Tests sometimes take over 3 hours to complete. By monitoring the size of the test log, the tests continue to run because every minute or so the log size increases by a few bytes. A new "." is added to:

    src\moin\converters\_tests\test_creole_in.py ........................... [ 13%]
    .....................

A workaround is to cancel the sluggish terminal window and restart the tests in a new terminal window.
