### ISSUE TITLE
Cannot update moin2 on test.pypi.org

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#1473]
Any volunteers to update moin packaging? I think we need a pyproject.tml file as described in https://pypi.org/project/setuptools-scm/.  Or is there is a minor procedure update to get around this error?

My old procedure to install moin2 on https://test.pypi.org/project/moin/ no longer works.

    pip install --upgrade setuptools wheel
    pip install --upgrade twine
    pip install --upgrade build
    # Switch to a release branch, make it current, generate a release tag on release branch
    git tag 2.0.0a14
    py -m build
    py -m twine upload --repository testpypi dist/*

Current Result:

    (moin-venv-python) C:\git\moin>py -m twine upload --repository testpypi dist/* --verbose
    INFO     Using configuration from C:\Users\haase\.pypirc
    Uploading distributions to https://test.pypi.org/legacy/
    INFO     dist\moin-2.0.0a15.dev0+g5ba605ea.d20230711-py3-none-any.whl (2.1 MB)
    INFO     dist\moin-2.0.0a15.dev0+g5ba605ea.d20230711.tar.gz (2.2 MB)
    INFO     Querying keyring for username
    Enter your username: RogerHaase
    INFO     Querying keyring for password
    Enter your password:
    INFO     username: RogerHaase
    INFO     password: <hidden>
    Uploading moin-2.0.0a15.dev0+g5ba605ea.d20230711-py3-none-any.whl
    100% ---------------------------------------- 2.2/2.2 MB • 00:00 • 3.2 MB/s
    INFO     Response from https://test.pypi.org/legacy/:
             400 '2.0.0a15.dev0+g5ba605ea.d20230711' is an invalid value for Version. Error: Can't use PEP 440 local
             versions. See https://packaging.python.org/specifications/core-metadata for more information.
    INFO     <html>
              <head>
               <title>400 '2.0.0a15.dev0+g5ba605ea.d20230711' is an invalid value for Version. Error: Can't use PEP 440
             local versions. See https://packaging.python.org/specifications/core-metadata for more information.</title>
              </head>
              <body>
               <h1>400 '2.0.0a15.dev0+g5ba605ea.d20230711' is an invalid value for Version. Error: Can't use PEP 440 local
             versions. See https://packaging.python.org/specifications/core-metadata for more information.</h1>
               The server could not comply with the request since it is either malformed or otherwise incorrect.<br/><br/>
             &#x27;2.0.0a15.dev0+g5ba605ea.d20230711&#x27; is an invalid value for Version. Error: Can&#x27;t use PEP 440
             local versions. See https://packaging.python.org/specifications/core-metadata for more information.

              </body>
             </html>
    ERROR    HTTPError: 400 Bad Request from https://test.pypi.org/legacy/
             '2.0.0a15.dev0+g5ba605ea.d20230711' is an invalid value for Version. Error: Can't use PEP 440 local versions.
             See https://packaging.python.org/specifications/core-metadata for more information.

**Comment by ThomasWaldmann** [comment]
@RogerHaase something is going wrong there.

If you tag the current changeset as `2.0.0a14`, then setuptools_scm should not come up with `2.0.0a15.dev0+g5ba605ea.d20230711`.

Can you check with `git status` of the workdir is somehow dirty maybe?

**Comment by RogerHaase** [comment]
Thank you! The problem was an uncommitted change.
