### ISSUE TITLE
svgdraw creates wrong item

### ISSUE THREAD

**Issue by ThomasWaldmann** [moinwiki/moin#149]
**[Original report](https://bitbucket.org/thomaswaldmann/moin-2.0/issue/149) by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

by some change svgdraw (may be this counts for all drawing items)
now saves to item name "undefined" and not to the given one.

**Comment by RogerHaase** [comment]
closing as dup of #355 

svgdraw is very broken, needs newer version of https://github.com/SVG-Edit/svgedit
