### ISSUE TITLE
'werkzeug.urls.url_quote_plus' is deprecated

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#1496]
'werkzeug.urls.url_quote_plus' is deprecated and will be removed in Werkzeug 2.4. Use 'urllib.parse.quote_plus' instead.

'werkzeug.urls.url_quote' is deprecated and will be removed in Werkzeug 3.0. Use 'urllib.parse.quote' instead.

Also werkzeug.urls.url_unquote

**Comment by RogerHaase** [comment]
In /src/moin/wikiutil.py near line 240 there is:

        def anchor_name_from_text(text):
        """
        Generate an anchor name from the given text.
        This function generates valid HTML IDs matching: [A-Za-z][A-Za-z0-9:_.-]*

Where the trailing "-" was not true, "-" was converted to ".2D" by this code (5 lines below the above):

    quoted = werkzeug.urls.url_quote_plus(text, charset='utf-7', safe=':')

The trailing "-" will become true after this revised code is implemented:

    quoted = urllib.parse.quote_plus(text, safe=':', encoding='utf-7', )

In /src/moin/_tests/test_wikiutil.py near line 30 there will be a revised test documenting the change:

    class TestAnchorNames:
        @pytest.mark.parametrize('text,expected', [
            # old note: recent werkzeug encodes a "+" to "%2B", giving ".2B" in the end,
            #       also "-" to "%2D", giving ".2D".
            # ('\xf6\xf6ll\xdf\xdf', 'A.2BAPYA9g.2Dll.2BAN8A3w.2D'),
            #                                   ^^^           ^^^
            # -----------
            # newer note:
            # see #1496 'werkzeug.urls.url_quote_plus' is deprecated. Use 'urllib.parse.quote' instead.
            # Contrary to werkzeug, urllib does not do: 'also "-" to "%2D", giving ".2D".'
            ('\xf6\xf6ll\xdf\xdf', 'A.2BAPYA9g-ll.2BAN8A3w-'),
            #                                 ^           ^
            ('level 2', 'level_2'),
            ('level_2', 'level_2'),
            ('', 'A'),
            ('123', 'A123'),
            # make sure that a valid anchor is not modified:
            ('ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789:_.',
             'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789:_.')
        ])

**Comment by UlrichB22** [comment]
Still found 3 errors when trying to run with Werkzeug 3.0:

- in auth/__init__.py: `import url_quote, url_quote_plus`
- in converters/image_in.py: `import url_decode`
- in utils/send_file.py: `import url_quote`
