### ISSUE TITLE
rst docs need section on how to update help-en items

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#1519]
per title

**Comment by wagner-intevation** [comment]
Could it be auto-generated from the docs, so that we don't have a manual sync issue? I actually assumed (without looking closer), that I actually also edited the built-in docs (help-en), not just the docs at moin-20.readthedocs.io in my PRs

**Comment by RogerHaase** [comment]
The easiest way is to load the help-en files: `moin load-help -n en`

Edit  the target item

If you have a test wiki, run `moin maint-reduce-revisions` (updates all namespaces)

Dump all the help files: `moin dump-help -n en`

Commit only the target data and meta files.

Auto-generating docs from the code sounds hard given the state of the code.
