### ISSUE TITLE
"moin dump-help -n en" updates all meta files

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#1533]
The mtime field in the meta file is updated even though the corresponding data file is not changed.

The order of entries within externallinks, itemlinks, and itemtransclusions is random so these fields may be updated.

Update `Updating the Help docs` within development.rst when fixed.

**Comment by UlrichB22** [comment]
During testing, I made 2 beginner's mistakes:

- Using an empty directory as path parameter gives a `FileNotFoundError: [Errno 2] No such file or directory`. IMO we should create the subdirectory en or common if missing.

- The namespace parameter does not allow 'help-en', only 'en'. IMO 'help-en' should additionally be accepted as a synonym, as this is the true name for the namespace. 

I can make the adaption sometime later after your changes if you agree.

**Comment by RogerHaase** [comment]
The help-en vs. en has bothered me also. I think it is better to just drop en (bad choice on my part) and require help-en / help-common everywhere. 

Plese make the changes.

**Comment by RogerHaase** [comment]
nothing left to do here
