### ISSUE TITLE
Flash with "Access Denied" has no category

### ISSUE THREAD

**Issue by cintek** [moinwiki/moin#1543]
When a flash is shown with the title "Access Denied" it has no category. I would expect that is has the category `error`. I got the message when I tried to create a page using a template.

**Comment by RogerHaase** [comment]
Cannot reproduce. 

1. Using supereditor, created a template with ACL of `All:`
2. logged out
3. logged in with ordinary user id using Modernized theme
4. tried to create page using new template
5. new template was not listed as a template (because of ACL)

Need more info.

**Comment by cintek** [comment]
Don't know if the behaviour has changed in the meantime but I couldn't reproduce it now. I just took moin2 with a sample wiki created a new page by selecting `MoinMoin` as item type and then chose `TemplateSample`. When I'm saving the new page I get the message
> Access Denied
> You are not allowed to access this resource.

As I can see now it is not part of `moin-flash` so it's no wonder that the flash has no category.
