### ISSUE TITLE
Meaning of "SuperUser" in Docs and ACL

### ISSUE THREAD

**Issue by wagner-intevation** [moinwiki/moin#1555]
The [docs](https://moin-20.readthedocs.io/en/latest/admin/configure.html#acls-for-contents) and default wikiconfig include the following "before" ACL:
```
SuperUser:read,write,create,destroy,admin
```

The user account `SuperUser` does not exist by default, thus anyone can create an account named `SuperUser` or rename an existing account to this special account name, gaining destroy- and admin-privileges.

Or is the `SuperUser` meant for a different purpose? I don't see a relevant mention of the name in the source code.

**Comment by ThomasWaldmann** [comment]
Guess the docs should change `SuperUser:` to `YourSuperUser:` to make clear that should be replaced by a username. And also that this account should be created immediately, so it can't be taken by someone else.
