### ISSUE TITLE
ACL: questions and issues

### ISSUE THREAD

**Issue by UlrichB22** [moinwiki/moin#1561]
While testing the migration of a real moin wiki from 1.9 to 2.0, I have some problems and questions about ACLs.

1. the modernized theme does not allow to change ACLs in `+admin/item_acl_report`. There is no flash message about success or failure. With the topside theme this is fine.

2. what is the meaning of the '+' sign in the following wikiconfig line?

`    acl_functions = '+YourName:superuser'
`

3. the name 'SuperUser' in the following wikiconfig line seems to be an example, but this is not clearly stated
 
`    NAMESPACE_DEFAULT: dict(before='SuperUser:read,write,create,destroy,admin',
`

IMO it would be easier for wiki admins to have a standard builtin group, e.g. 'superuser'. Then the default wikiconfig entry does not need to be changed.

4. it is possible to change or add an ACL value of 'all:read' with lowercase. This will result in permission denied when trying to access the item. In moin 1.9 this seems to be a valid ACL, but after importing wiki data with lowercase ACL, access to these items fails.

5. I have not found a way to view or change the ACL for a newly created item. IMO, the owner or creator of an item should have the ability to restrict access to their items, even if not a superuser.

Please check and give some advice. I will split the issue into separate issues if needed.

**Comment by RogerHaase** [comment]
(1) is obvious bug (maybe CSS), on left mousedown, the Save buttton moves to left. If left mousedown is held down and mouse moved over Save and released then ACL is updated.

(2) https://moin-20.readthedocs.io/en/latest/admin/configure.html#acls-entry-prefixes

The leading + is same as no leading + and opposite of leading -

(3) agree it is confusing. Also docs seem to miss that in wikiconfig.py, the left side of : can be a list", an alternative to a ...Group item

    acl_functions = 'JaneDoe,JoeDoe:superuser'

(4) will try import later

(5) No way I know of to give extra admin power to the creator (last editor) of an item. Closest way is for wiki admin to set `hierarchic=True` on a namespace and then create an item with admin auth for a specific user(s). The user could then create subpages with ACL rules or change the ACLs of the parent item.

A way to implement this is for a wiki admin to create a home page for new users in the `users` namespace.

**Comment by UlrichB22** [comment]
> (1) is obvious bug (maybe CSS), on left mousedown, the Save buttton moves to left. If left mousedown is held down and mouse moved over Save and released then ACL is updated.

Thanks, I didn't realize the jumping button. It is related to this line in modernized theme.css:
https://github.com/moinwiki/moin/blob/c6686ab41d4b77144309be7454b43f4fa4c3899f/src/moin/themes/modernized/static/css/theme.css#L55

Removing this line partially fixes the problem. Hopefully someone with more css experience can assist.

**Comment by RogerHaase** [comment]
I was wrong about the leading + in `acl_functions = '+YourName:superuser'` above.  The leading + is not the same as no leading +

 I updated docs:

https://moin-20.readthedocs.io/en/latest/admin/configure.html#acls-entry-prefixes

And removed the leading + in wikiconfig.py as it is probably rarely used.

**Comment by RogerHaase** [comment]
Finally got around to trying import19. Per my tests, both moin 1.x and moin2 allow lowercase `all:` to be saved as an ACL rule and both moin 1.x and moin2 ignore the rule as `all` is not a username. Note `all` can be a username.

The docs for both moin 1.x and moin2 correctly use uppercase `All:` in all examples and moin2 docs state the need for capitulation. 

import19 converts ACL rules with lowercase `all:` correctly.

Created #1595

Thought about opening an issue to create a flash warning message when an ACL rule with all, known, trusted is saved.

I think this issue can be closed as there is nothing more to do.
