### ISSUE TITLE
Missing moin-script.py

### ISSUE THREAD

**Issue by cmedcoff** [moinwiki/moin#1563]
According to the docs at:

https://moin-20.readthedocs.io/en/latest/devel/development.html#debug-a-transaction

in order to debug locally using PyCharm one sets up "moin-script.py" as the script to run, but this script does not exist.  Either the docs need an update or the script is missing.

**Comment by RogerHaase** [comment]
Correct, the docs need an update.

For *nix replace `...scripts\moin-script.py` with `...bin/moin`

**Comment by cmedcoff** [comment]
And I see bin/moin on *nix, is in fact a python script.  On Windows, which I run locally, is moin.exe, not a python script, and pycharm won't debug that.  What's the alternative for windows?

**Comment by RogerHaase** [comment]
The screenshot is from Windows and I use Windows 3.10 most of the time (99%).

If you are saying you have a moin.exe and not a moin-script.py then a guess is your run of `<python> quickinstall.py` failed. There is no moin code that creates either moin.exe nor moin-script.py; these are created somewhere in the python venv creation process.

A suggestion is to delete the entire `moin-venv-python` directory, and delete activate.bat, deactivate.bat, and m.bat from the root moin directory. Then start over following https://moin-20.readthedocs.io/en/latest/admin/install.html#installation-for-developers

If you are running Python 3.12 then you are probably the first to do so.  3.12 is not yet added to the github CI.

**Comment by RogerHaase** [comment]
On second thought, if moin is running well and your only issue is with pycharm, then the above recommendation to reinstall is probably of no value. 

I just noticed the PyCharm screen has changed, and the run parameters only fully appear in full screen `run --no-debug --no-reload`

![pycharm2023-2](https://github.com/moinwiki/moin/assets/844190/769b9ee9-1fc7-4f95-a83b-e46bd7c89b3c)

**Comment by cmedcoff** [comment]
I really appreciate your time.   

I'm on Windows 11 Home with the most recent patch.

Python --version reports 3.11.5.  I have a local instance that runs that I created using the "developer install" directions.  I believe that I used quickinstall.py. and the virtual environment it created, does in fact have a moin.exe in the env/scripts directory.  Image attached.

![moindotexe](https://github.com/moinwiki/moin/assets/3218788/4cd621c3-ce0e-417f-8006-7bf90243bdc9)

That aside, I cloned a 2nd time to a differrent default folder (the first time I cloned to 'moin2').  Next ran "python quickinstall.py".  After this I checked the newly created scripts directory in the new virtual environment and once again found a moin.exe.  It's not a text, but a binary file.  I do see "python" in it when I open it in a text editor e.g "vim".  Makes me thing that something like "py2exe" or a similar tool must have been used to create it.  If I try to use this moin.exe, PyCharm seems to attemp to read it rather than just execute it when using it in a setting up a run/debug configuration and an exception is thrown.

![moindotexe_rundebug](https://github.com/moinwiki/moin/assets/3218788/f2ffb394-90e4-4440-97c6-bf346680bf33)

In your latest screen shot from your update about "PyCharm" your run/debug config still points to a "moin-script.py".  Are you sure this wasn't created by hand?  Re-creating a totally new clone and virtual environment does not yield that file.

**Comment by cmedcoff** [comment]
I appreciate this script.  I'll use it for now in order to get started on learning more about moin2 code, structure, design, etc.  My goal is to understand enough to write customizations for themes, custom macro's, etc.  For example I'd like to use moin2 more as a CMS with both page and blog support.  I know there's a blog content item in the code, but have no idea how to use it.  If I learn enough perhaps I can make contributions: code, documentation, fixes.  I've used pip plenty but don't know much abou easy install.

**Comment by RogerHaase** [comment]
afaik all the magic happens in quickinstall.py near line 567

    def do_venv(self):
        venv.create(self.dir_venv, system_site_packages=False, clear=False, symlinks=False, with_pip=True, prompt=None)

and this page says venv.create hasn't changed since python 3.9:

https://docs.python.org/3/library/venv.html

**Comment by RogerHaase** [comment]
Same issue with Python 3.12.

With PyCharm 2023.3.2 running the server was a success using

    Script:            <path/to>moin.exe
    Script Parameters: run

But debug failed on unicode errors.

With Python 3.10, same version of PyCharm, attempts to run failed on unicode errors.

A wild guess is we need a PyCharm shell script.

**Comment by UlrichB22** [comment]
This problem only seems to occur under Windows. I have searched the internet and found several possible solutions.
One of them is to run the flask module instead of a script.

First, you can try running the following command from inside a valid wiki (e.g. after running `moin create-instance --full`):
`flask --app moin.cli run`

If this was successful, you can try to change the config of pycharm as follows:

![Moin2_Pycharm_ debug_2024-01-18_16-03](https://github.com/moinwiki/moin/assets/97119703/9bfe5975-47c2-4e83-a4f9-f3ff0244bfa3)

For me this worked fine on Debian 12 (bookworm).

**Comment by RogerHaase** [comment]
Thanks, works perfectly on Windows 10, Python 3.12, PyCharm 2023.3.2

**Comment by cmedcoff** [comment]
Just quick test, that works on Windows 11, Python 3.11 and PyCharm 2023.2.1 Community Edition.  I know it's a separate issue, but I'd love to know how/why moin.exe is produced on Windows and why this is different than my Linux VM in Azure with the same installation steps.

Noticed I'm behind on PyCharm so updated to 2023.3.2, that also works.

**Comment by RogerHaase** [comment]
When you `activate`, `<venv>/Scripts` is added to the start of path, so doing `moin run`  is same as `moin.exe run`

**Comment by UlrichB22** [comment]
The script is generated by setuptools based on the entry_points/console_scripts settings in setup.py, please see [setuptools.pypa.io/en/latest/userguide](https://setuptools.pypa.io/en/latest/userguide/entry_point.html#).

In my Linux environment I removed the script <venv>/bin/moin and run `./m quickinstall`. Afterwards the script was recreated. 
The script is the same as reported by Roger above except for the first line with the location of the python module.

**Comment by cmedcoff** [comment]
Thanks for this.  I'm far from expert on python packaging at thispoint, but I was searching around and ran across this:

https://github.com/pypa/pip/issues/6652

Which seems to suggest that some tooling does indeed generate executable files on Windows (only).  I find it strange that any packaging tools would, nor do I think they should, exhibit different behavior on one platforms versus another, but that's just my 2 cents from the peanut gallery.

I do like the "flask --app moin.cli run" approach being included in the docs as moin2 IS a flask app and it removes any mystery about starting up a flask app any other way, while I understand there is convenience of "moin" or "./m".
