### ISSUE TITLE
Adapt python versions supported and used for tests

### ISSUE THREAD

**Issue by UlrichB22** [moinwiki/moin#1570]
I am using Debian 12 (Bookworm) for my development environment and this contains Python 3.11.

The current stable Python versions are 3.11 and 3.12 according to https://devguide.python.org/versions.

Which versions do we want to support and use for testing?
3.11 is missing in

- tox.ini: `envlist = py{38,39,310},pypy3,flake8`
- setup.py

In addition, the versions in .github/workflows/ci.yml should be raised.
Please recommend.

**Comment by ThomasWaldmann** [comment]
I recently looked into this for `borg`:

For a "soon to be released sw", I would:
- drop py38
- add py311 and py312

If release is more far in the future, I'ld also consider dropping py39 also.

BTW, I also replaced flake8 by `ruff` - it integrates better into `pyproject.toml`.

**Comment by UlrichB22** [comment]
I tried the module check-python-versions to check the consistency of different configuration files.

Output of check-python-versions **before** change:

```
setup.py says:                 3.8, 3.9, 3.10
tox.ini says:                  3.8, 3.9, 3.10, PyPy3
.github/workflows/ci.yml says: 3.8, 3.10, 3.11

mismatch!
```

Output of check-python-versions **after** change:

```
setup.py says:                 3.9, 3.10, 3.11, 3.12
tox.ini says:                  3.9, 3.10, 3.11, 3.12
.github/workflows/ci.yml says: 3.9, 3.10, 3.11, 3.12

```

PyPy3 has been removed from tox.ini in the PR above, it needs further testing and should also be included in setup.py and the Github workflow if it is useful.

**Comment by ThomasWaldmann** [comment]
Hint: guess you don't need FUSE for moin, so you should remove the fuse2/fuse3 stuff from the ci.yml github workflow. Guess you could just remove these "toxenv:" lines.

I
