### ISSUE TITLE
adopt pyproject.toml

### ISSUE THREAD

**Issue by ThomasWaldmann** [moinwiki/moin#1571]
Can be done in 2 steps:

- there should be a minimal `pyproject.toml` in any case, giving build system requirements and backend
- even better, move all metadata from setup.cfg / .py to pyproject.toml (for moin as well as for the misc. other tools used for development)

https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/

Example PR from borg: https://github.com/borgbackup/borg/pull/7997

**Comment by ThomasWaldmann** [comment]
flake8 is a bit of a troublemaker here as its settings can't live in `pyproject.toml`, but there is `ruff` as a nice replacement.

as this tends to be a slightly bigger change, it is best done as a separate PR, as seen there:

https://github.com/borgbackup/borg/pull/7808

**Comment by UlrichB22** [comment]
Recommendation from Thomas in #1570: 

> Replace flake8 by ruff - it integrates better into pyproject.toml.
