### ISSUE TITLE
readthedocs does not provide access to /docs/examples/*

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#1578]
In /docs/examples/config, /docs/examples/deployment, /docs/examples/password-reset there are several example files with names not ending in .rst.

There are some references to these files within https://moin-20.readthedocs.io but afaik there is no way to view these files. 

Wiki admins installing moinmoin from pypi have no means of viewing these files because the docs directory is not included in the distribution.

Preferred solution is for readthedocs to have working links to the files.

**Comment by UlrichB22** [comment]
There is a feature in sphinx to view extra files using the ':download': role, see [referencing-downloadable-files in www.sphinx-doc.org](https://www.sphinx-doc.org/en/master/usage/referencing.html#referencing-downloadable-files) .

Maybe this can help.

**Comment by RogerHaase** [comment]
The file download works well, but my current thinking is to move all the 'useful' files in moin/docs/examples/* to moin/src/moin/contrib/ and to update the .rst files to have useful pointers (no working links) to the example files.

The other contrib directory in /moin/contrib will be ignored for now.

**Comment by ReimarBauer** [comment]
Hmm,

Usually None rst files can be downloaded 

There is a navid.py for me downloading works

https://mss.readthedocs.io/en/stable/plugins.html#installation

**Comment by ReimarBauer** [comment]
Ah I misunderstood you want to list all None linked files?

You can add to conf.py some code for e.g. a table or Index for such directories. You have also compute time on rtfd. We create there for example our gallery. 

Add then to html_static_path your new static path.

**Comment by RogerHaase** [comment]
My guess is that the admin who is interested in logging, password reset, or wsgi details has already installed moin2. So it will be more helpful to the admin to point to files they already have; than to offer a download or copy and paste.
