### ISSUE TITLE
update docs change log for moin2 beta release

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#1616]
url: https://moin-20.readthedocs.io/en/latest/admin/changes.html

Current files:

* docs/admin/changes.rst
* docs/changes/CHANGES
* plus 2 SoC files in docs/changes/*

TODO:
* ignore 2 SoC files for now
* add mini description of Fixes, Features, Other changes
* add more detail for beta
* the moin1.x changelog can be easily copied over, but do it later (if wanted)

suggestions?

**Comment by UlrichB22** [comment]
I think we can remove the 2 SoC documents, they are just about adding support for markup languages: html, restructured text, docbook, mediawiki and moinwiki. 

As mentioned in https://github.com/moinwiki/moin/issues/941#issuecomment-1960432184 we should just start with an initial empty change document. For the next releases we need to document major changes and bugfixes.

**Comment by UlrichB22** [comment]
We can use automatically generated release notes generated from pull requests in the future:

https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

PRs can be tagged to be included or excluded. Structuring with tagging for bug fixes and new features is also possible.

**Comment by ThomasWaldmann** [comment]
I suspect that automatically generated release notes are nowhere nearly good content as manually created ones. This is especially true if commit comments tend to be a bit sloppy.

For my other projects I usually do "update CHANGES" manual commits now and then, based on the output of `git log COMMITHASH..` (COMMITHASH being the previous manual "update CHANGES" commit), which I edit and rearrange manually into fixes, new features and other changes.

**Comment by ThomasWaldmann** [comment]
This is the last issue in the still open 2.0.0a1 milestone.

Is it done, close?

Close the milestone?

@RogerHaase ^^

**Comment by RogerHaase** [comment]
I was lazy and changed the title and milestone with the intent of doing a better job on the changelog for a1 and b1. 

I closed the a1 milestone just now.
