### ISSUE TITLE
readthedocs build failed

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#1634]
https://readthedocs.org/projects/moin-20/builds/23606652/

Build #23606652
latest ([5e6f856b46c0a57e1bbd60016c8d4a31736f0a89](https://github.com/moinwiki/moin/commit/5e6f856b46c0a57e1bbd60016c8d4a31736f0a89))
Build failed
Error
We encountered a problem with a command while building your project. To resolve this error, double check your project configuration and installed dependencies are correct and have not changed recently.

git clone --depth 1 https://github.com/moinwiki/moin .
git fetch origin --force --prune --prune-tags --depth 50 refs/heads/master:refs/remotes/origin/master
git checkout --force origin/master
git clean -d -f -f
cat .readthedocs.yaml
asdf global python 3.12.0
python -mvirtualenv $READTHEDOCS_VIRTUALENV_PATH
python -m pip install --upgrade --no-cache-dir pip setuptools
python -m pip install --upgrade --no-cache-dir sphinx readthedocs-sphinx-ext
python -m pip install --exists-action=w --no-cache-dir -r docs/requirements.txt
python ./setup.py install --force
/home/docs/checkouts/readthedocs.org/user_builds/moin-20/envs/latest/bin/python: can't open file '/home

**Comment by UlrichB22** [comment]
Probably changing the method to pip in the following line will fix the build:

https://github.com/moinwiki/moin/blob/5e6f856b46c0a57e1bbd60016c8d4a31736f0a89/.readthedocs.yaml#L25

**Comment by RogerHaase** [comment]
thanks for clue, but I beat you by 1 minute.
