### ISSUE TITLE
Add option to TableOfContents to not show leading H1

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#1648]
Many wiki pages have a single H1 at the top of the page.  Add an option to omit the H1 from the TOC.

Maybe:

    <<TableOfContents(2,5)>>

to not show any H1 headings, or

    <<TableOfContents(-1)>>

to omit only the first H1 from the TOC.

**Comment by buhtz** [comment]
Thanks for opening this Issue. The use case was to have a page title. Conceptual a title is not a heading.
So using a h1-heading as page title and ommiting it from the TOC is a workaround and not solution.

Offer a real title (not relevant for TOC) or just offer a big-and-bold-font-formatting.

Or make the <<TableOfContents(-1)>> take care only of that headings appearing after itself and not before it.

```
= Page title =
Introduction bla bla

<<TableOfContents()>>
= first heading appearing in TOC =
This section appears as "1. first heading appearing in TOC" in the TOC
```

**Comment by RogerHaase** [comment]
An easy solution would be a new macro that would look like an H1. Would this suit your needs? 

    <<PageTitle(My Page Title)>>

**Comment by buhtz** [comment]
> ```
> <<PageTitle(My Page Title)>>
> ```

This would suit my needs.
