### ISSUE TITLE
updated emeraldtree library

### ISSUE THREAD

**Issue by ThomasWaldmann** [moinwiki/moin#1657]
Maybe somebody could test master branch from there, whether it works fine for moin:

https://github.com/moinwiki/emeraldtree

I mainly did packaging, CI, python updates, see the commit comments - there should be no functional changes.

**Comment by UlrichB22** [comment]
Tested the emeraldtree from https://github.com/moinwiki/emeraldtree/archive/refs/tags/0.11.0a1.tar.gz and also from a git clone containing some newer commits.

The tests were done 
- using `moin run` on a wiki with loaded help-en docs and
- using `./m tests`

The only issue I found was the missing _version module in the git clone version. This file will hopefully be created by setuptools_scm. I created a dummy _version.py manually as a workaround.

**Comment by ThomasWaldmann** [comment]
`_version.py` is intentionally excluded via `.gitignore`, but will be contained in a sdist.

it is also available after `pip install` of the package.

**Comment by ThomasWaldmann** [comment]
Just released emeraldtree 0.11.0 on pypi.

Also: sent a pypi invite to @RogerHaase to increase bus factor there.

**Comment by ThomasWaldmann** [comment]
Closing this. In case there is any issue related to this, file it in the emeraldtree issue tracker.
