### ISSUE TITLE
macros with editing errors should not fill the log with tracebacks

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#1687]
Remove code similar to:

    raise ValueError("Bad timestamp %r: %s" % (args, err))

that fills the log with  entries similar to:

    Traceback (most recent call last):
      File "C:\GIT\moin\src\moin\macros\Date.py", line 69, in macro
        tm = self.parse_time(tm)
      File "C:\GIT\moin\src\moin\macros\Date.py", line 53, in parse_time
        tm = float(args)
    ValueError: could not convert string to float: 'qqq'

and replace it with code that creates an error message so the editor can fix the problem.

**Comment by ThomasWaldmann** [comment]
Guess these are the options:
- reject invalid page content (e.g. when containing macros that throw ValueErrors) and do not save such pages, but give a error msg to use and they MUST fix it before it is accepted and saved.
- accept invalid page content (could be also existing page content migration from moin 1.9.x) - in that case I guess we'll still need the logging or we won't be able to find such pages?

**Comment by RogerHaase** [comment]
I view the issue as a trivial editing error, similar to a misspelled word. We can show the error in bold text on Preview or Save. It is the editor's task to correct the error. No need to create and log tracebacks.

**Comment by UlrichB22** [comment]
The `moin import19` command may also add items with invalid macros. IMO we should not reject them.

What do you think about adding a meta field of type bool to mark items with invalid macros. This would allow a wiki admin to get a list of items to check and correct.
