### ISSUE TITLE
Duplicate files in smileys or admonitions and icons directories

### ISSUE THREAD

**Issue by UlrichB22** [moinwiki/moin#1696]
In static/img there are directories smileys and admonitions, all their content can also be found in the icons directory.
These directories are only used by css/common.css. The icons directory is used by macros ShowSmileys and ShowIcons and by the smiley converter.

Is there a reason that I have missed? Can we remove the smileys and admonitions directories and adjust common.css?

**Comment by RogerHaase** [comment]
The files in the admonition directory are not duplicated in the icons directory, some of the mime-type files are duplicated.

OK to combine the directories and eliminate the duplicate files.

**Comment by UlrichB22** [comment]
Thanks for your feedback. The admonition files have an "admon-" prefix in the icons directory.
