### ISSUE TITLE
improve validation when saving items

### ISSUE THREAD

**Issue by ThomasWaldmann** [moinwiki/moin#17]
**[Original report](https://bitbucket.org/thomaswaldmann/moin-2.0/issue/17) by Thomas Waldmann (Bitbucket: [thomaswaldmann](https://bitbucket.org/thomaswaldmann), GitHub: [thomaswaldmann](https://github.com/thomaswaldmann)).**

----------------------------------------

if a new revision gets stored into the storage, we should do some validation steps:
* for text data, try to decode it to unicode - if it fails, do not accept it
(use content-type metadata)
* check meta fields for correctness

some checks are already in place, see storage validation layer, but just giving warnings, not raising exceptions.

**Comment by RogerHaase** [comment]
Validation issues related to JFU will be addressed by #1279
