### ISSUE TITLE
github release missing for 2.0.0b1

### ISSUE THREAD

**Issue by ThomasWaldmann** [moinwiki/moin#1723]
see there: https://github.com/moinwiki/moin/releases

**Comment by RogerHaase** [comment]
Installing gpg on Windows was rather confusing. I seem to have lost my secret key. Do I just create a new one or try to reload the old one?

(moin-venv-python) C:\GIT\moin\dist>gpg --detach-sign -a moin-2.0.0b1.tar.gz
gpg: no default secret key: No secret key
gpg: signing failed: No secret key

**Comment by RogerHaase** [comment]
The problem is there are 2 versions of gpg.exe installed on my Windows:

    C:\Program Files (x86)\GnuPG\bin\gpg.exe is version 2.4.4
    C:\Program Files\Git\usr\bin\gpg.exe is version 2.2.41

The older version works, easiest way to access it is to use Git-Bash. 

PowerShell runs newer version 2.4.4, cannot find a command to load the secret key.
