### ISSUE TITLE
Links to usemod[.]com, redirects to vietnamese online gambling websites

### ISSUE THREAD

**Issue by sebix** [moinwiki/moin#1729]
There are four links in moin to httpX://usemod[.]com:

https://github.com/moinwiki/moin/blob/fbcd6cc03b6c7d4b1446bfedbe2c7f89a508d1fa/src/moin/contrib/intermap.txt#L43
https://github.com/moinwiki/moin/blob/fbcd6cc03b6c7d4b1446bfedbe2c7f89a508d1fa/src/moin/contrib/intermap.txt#L78
https://github.com/moinwiki/moin/blob/fbcd6cc03b6c7d4b1446bfedbe2c7f89a508d1fa/src/moin/contrib/intermap.txt#L99
https://github.com/moinwiki/moin/blob/fbcd6cc03b6c7d4b1446bfedbe2c7f89a508d1fa/src/moin/themes/__init__.py#L492

That page redirects to httpsX://bvml[.]org/, which promotes a Vietnamese online gambling portal for football.

**Comment by UlrichB22** [comment]
Apparently the domain has expired and has been changed to usemod.org, see 
https://github.com/mlude/usemod/commit/512fa3bf507a2df14b39bcc1773a710190fb047d

We should also warn wiki admins on the moin-user list to update intermap.txt and check their wiki contents.

If you want to fix the issue, you can assign it to yourself. Thanks for reporting it.

**Comment by sebix** [comment]
> We should also warn wiki admins on the moin-user list to update intermap.txt and check their wiki contents.

I can do so after a fix as been merged/released by the moin team

> If you want to fix the issue

-> https://github.com/moinwiki/moin/pull/1731

> you can assign it to yourself.

I can't, I'm not a member of this project.

**Comment by UlrichB22** [comment]
Thanks for your support.
