### ISSUE TITLE
Deviating ACL of built-in help-en/TemplateSample

### ISSUE THREAD

**Issue by sebix** [moinwiki/moin#1733]
The page `help-en/TemplateSample` (`src/moin/help/help-en/TemplateSample.meta`) has a custom ACL
```json
  "acl": "BadGuy: All:read,write",
```

Therefore, setting a default ACL on the help pages (for example, preventing access for anonymous users) works for all help pages, except for this one page.

What is the reason for setting `All:read,write` for this help page in particular, deviating from all other help pages?

Can this custom ACL be removed, so that this help page uses the default ACL as all the other help pages?

For me, as a user, it is confusing that the software sets an unrestrictive ACL for a built-in page.

**Comment by UlrichB22** [comment]
Thanks for reporting the issue. IMO the idea behind the special ACL was to show that ACLs from the template are copied to the new item. But the help-en namespace is no sandbox and it is nearly impossible to remove the ACL using the GUI. Please check the above fix.

**Comment by sebix** [comment]
Thanks for the fix!
