### ISSUE TITLE
Slideshow start/exit links are broken when wiki directory served not as '/'

### ISSUE THREAD

**Issue by gvlat** [moinwiki/moin#1745]
I run moin 2.0.0b1 as wsgi application using apache. It is configured to serve wiki from "/wiki" directory. \<\<SlideShow\>\> macro generates invalid links to start and exit slideshow. They direct to "/+slideshow/page_with_slideshow"  and "/page_with_slideshow" instead of "/wiki/+slideshow/page_with_slideshow" and "/wiki/page_with_slideshow"

Steps to reproduce:
1. install moin as wsgi application with "WSGIScriptAlias /wiki /path_to/moin2wsgi.py"
2. create a page named "Test" with slideshow
3. Save and click "Start slideshow" link
You will be directed to the nonexisting "/+slideshow/Test"
The page with actual slideshow is located under "/wiki/+slideshow/Test"
The exit link in the slideshow directs to the nonexisting "/Test" page

wsgi configuration:
```
WSGIDaemonProcess moin2
WSGIPythonHome /home/storage/moin-venv

WSGIScriptAlias /wiki /home/storage/wiki/moin2wsgi.py

<Directory "/home/storage/wiki">
    Require all granted
</Directory>
```

Software:
```
OS: Fedora Linux 39
Python 3.12.4
python3-mod_wsgi-4.9.4
httpd-2.4.62
moin-2.0.0b1 installed via 'pip install --pre moin'
```

**Comment by UlrichB22** [comment]
Thanks for testing moin2.
