### ISSUE TITLE
Tag pages list each name for a page with multiple names separately

### ISSUE THREAD

**Issue by william42** [moinwiki/moin#1746]
This seems somewhat odd to me given that almost every other part of the site dealing with page names tends to coalesce them, separating with a dot or the like.

**Comment by UlrichB22** [comment]
Page names are grouped together in the page trail or in the history. In lists that are sorted alphabetically, however, the names are displayed separately in the correct order. This is the case in the index, in the tag list and in the output of the TitleIndex() macro.

**Comment by UlrichB22** [comment]
@william42, do you have any comments? Can we close this issue?

**Comment by william42** [comment]
I think it's fine to close now that I understand what's going on
