### ISSUE TITLE
Cannot delete/destroy page from '+index' page

### ISSUE THREAD

**Issue by gvlat** [moinwiki/moin#1753]
I run moin 2.0.0b1 as wsgi application using apache. It is configured to serve wiki from "/wiki" directory. 'Delete; and 'Destroy' actions invoked from wiki index do not work

Steps to reproduce:

1. install moin as wsgi application with "WSGIScriptAlias /wiki /path_to/moin2wsgi.py"
2. create a page named "Test"
3. Go to wiki index ( /wiki/+index/ )
4. mark page 'Test' and press 'Delete' or 'Destroy' button.
    2 popups will be shown
    
* Deleting.." or "Destroying.."
* "Item 'wiki/Test' does not exist"

The page is not actaully deleted.
The error does not occur when WSGIScriptAlias is set to '/'.

wsgi configuration:
'''
WSGIDaemonProcess moin2
WSGIPythonHome /home/storage/moin-venv

WSGIScriptAlias /wiki /home/storage/wiki/moin2wsgi.py

<Directory "/home/storage/wiki">
    Require all granted
</Directory>
'''
Software:
'''
OS: Fedora Linux 39
Python 3.12.4
python3-mod_wsgi-4.9.4
httpd-2.4.62
moin-2.0.0b1 installed via 'pip install --pre moin'
'''

**Comment by UlrichB22** [comment]
Found additional issues while testing:

- namespaces are not handled properly for subitems and aliases
- itemnames with non-ascii characters like German umlaut, the item will be deleted but the entry in the table is still visible until refresh of the index page.
