### ISSUE TITLE
"direct jump to best result" term for search

### ISSUE THREAD

**Issue by ThomasWaldmann** [moinwiki/moin#176]
**[Original report](https://bitbucket.org/thomaswaldmann/moin-2.0/issue/176) by Thomas Waldmann (Bitbucket: [thomaswaldmann](https://bitbucket.org/thomaswaldmann), GitHub: [thomaswaldmann](https://github.com/thomaswaldmann)).**

----------------------------------------

from irc:

Is there a way to get page search to go directly to the matching page, rather than show a list of similar results? Eg, if I want to go directly to "Intro" even if there's an "IntroHelp" page?

...

I was hoping for something like how DuckDuckGo takes you to the first search result if you add "\" (can't remember if it was to the beginning or end).

**Comment by RogerHaase** [comment]
Whoosh search scoring needs to be revisited when adding this feature. When the search term is the exact name of an item, the "best match" is frequently not that item.
