### ISSUE TITLE
Admin Tools to delete Spam users and pages

### ISSUE THREAD

**Issue by sebix** [moinwiki/moin#1803]
Is it correct that there are currently no built-in tools to remove spam user accounts and pages created by them?

Our current workaround is to use command line tools and delete the files in the file system, which is prone to errors because of the high number of manual actions required.
Also, it is hard to find all affected pages, pages created by an account, etc., as the overview is missing.

Can we delete a user account, including all pages created by the user, without keeping a history of those files?

**Comment by UlrichB22** [comment]
Such a tool does not yet exist. What do you think of this idea?

Every new, self-registered user needs approval. The user can create new items, but these are tagged with “approval_needed”. Of course, the user should not be able to remove this flag. Perhaps the global “+index”-view could be enhanced with an option to display only those items requiring approval. There you can then select all entries and click on remove or destroy.

In general, we recommend running public wikis with the option `'registration_only_by_superuser = True'` to avoid spam.

**Comment by RogerHaase** [comment]
dup of #879, close if you agree, leave open if you disagree

**Comment by sebix** [comment]
> In general, we recommend running public wikis with the option `'registration_only_by_superuser = True'` to avoid spam.

That may work for private wikis, but not for public wikis where contributions from the community are welcome.
