### ISSUE TITLE
revisions belonging to multiple namespaces?

### ISSUE THREAD

**Issue by ThomasWaldmann** [moinwiki/moin#194]
**[Original report](https://bitbucket.org/thomaswaldmann/moin-2.0/issue/194) by Thomas Waldmann (Bitbucket: [thomaswaldmann](https://bitbucket.org/thomaswaldmann), GitHub: [thomaswaldmann](https://github.com/thomaswaldmann)).**

----------------------------------------

belongs to: namespace branch in main repo

i just had the idea that we maybe want NAMESPACE to be a list of namespaces (not just one).

one application of that is sharing group items between namespaces (and also other common things). it is somehow similar to NAME being a list, so NAMESPACES could be also a list also.

If more than one name and more than one namespace is present in same metadata, it would mean that ALL names given are present in ALL namespaces given.

**Comment by RogerHaase** [comment]
The above proposal is in conflict with a namespace feature that is not implemented yet. From https://moin-20.readthedocs.io/en/latest/user/namespaces.html

### Namespaces

    MoinMoin supports the use of multiple namespaces where each namespace may have a 
    unique backend or media type. For example, the default namespace could use the OS 
    filesystem for item storage and another namespace could use an SQL database.

        an item in one namespace can readily include or transclude content from an item residing in another namespace.

        it is not possible for an item to have an alias name referencing a different namespace.

        it is not possible to rename an item into a different namespace.

        it is not possible to use a namespace name as an item name in a different namespace.

    See the namespace section within MoinMoin configuration for information on how to configure namespaces.

But then in wikiconfig.py we say it is not implemented yet:

    backends = {
        # maps backend name -> storage
        # the feature to use different storage types for each namespace is not implemented so use None below.
        # the storage type for all backends is set in 'uri' above,
        # all values in `namespace` dict must be defined as keys in `backends` dict

So making namespace a list will create a new problem of where/how to store an item that exists in 2 or more namespaces with unique backends. Creation of an item transcluding an item in a different namespace may be an alternative to making namespace a list.

@ThomasWaldmann OK to close this issue and add a new issue for `the feature to use different storage types for each namespace is not implemented `
