### ISSUE TITLE
tests use currently str type

### ISSUE THREAD

**Issue by ThomasWaldmann** [moinwiki/moin#202]
**[Original report](https://bitbucket.org/thomaswaldmann/moin-2.0/issue/202) by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

We should have unicode type instead of str type in our tests.

The interfaces itselfs rely on unicode type not on str type.

Because of the mapping of the used ascii strings  into unicode the results  will be the same.  We just should use always unicode literals.

**Comment by RogerHaase** [comment]
fixed by py3 conversion
