### ISSUE TITLE
*Draw items can't save metadata on modify

### ISSUE THREAD

**Issue by ThomasWaldmann** [moinwiki/moin#204]
**[Original report](https://bitbucket.org/thomaswaldmann/moin-2.0/issue/204) by xiaq (Bitbucket: [xiaq](https://bitbucket.org/xiaq), GitHub: [xiaq](https://github.com/xiaq)).**

----------------------------------------

These items use applets which do POSTs themselves, which are not aware of the metadata.

I haven't yet figured out a solution that doesn't require patching the applets.

**Comment by RogerHaase** [comment]
see #1467 and #355
