### ISSUE TITLE
ui for ordering search results

### ISSUE THREAD

**Issue by ThomasWaldmann** [moinwiki/moin#209]
**[Original report](https://bitbucket.org/thomaswaldmann/moin-2.0/issue/209) by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

I think I want to have an ui to order search results

e.g. sort by title name

Currently I miss that in 1.9 (guess it is similar in 2.0) for looking at activity in MoinMoinChat/Logs/moin-dev. 
First occurancy of a member there easily to find would be great

**Comment by RogerHaase** [comment]
Alternative method is to add a "name" radio button to Search Options > Sort By column. Now 
there are 4 choices: highest score, oldest, newest, name.

While implementing a sort by item name, discovered Whoosh has trouble sorting items names with slashes. Given item names similar to item/a, item/b, item/c... item/x, item/y, item/z; Whoosh will order item/x, item/y, and item/z after items named xxx; but correctly order item/a, item/b, and item/c.

A workaround was to add a name field without '/' characters.
