### ISSUE TITLE
singular / plural package names

### ISSUE THREAD

**Issue by ThomasWaldmann** [moinwiki/moin#224]
**[Original report](https://bitbucket.org/thomaswaldmann/moin-2.0/issue/224) by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

Just seen that we tend to use plural names too.

some places where we don't

storage(s)
script(s)
macro(s)
auth(s)
util(s)

**Comment by ThomasWaldmann** [comment]
```
apps
auth
config
constants
converter  # -> converters
datastruct  # -> datastructs
i18n
items
macro  # -> macros
mail
script  # -> scripts
search
security
signalling
static
storage
templates
_tests
themes
translations
util  # -> utils
```

How about that?

**Comment by RogerHaase** [comment]
maybe datastructures, or remove a level and have src/moin/backends.

**Comment by ThomasWaldmann** [comment]
yeah, "datastructures". just "backend" is too generic.
