### ISSUE TITLE
tree-like visualisation for Subitems panel

### ISSUE THREAD

**Issue by ThomasWaldmann** [moinwiki/moin#234]
**[Original report](https://bitbucket.org/thomaswaldmann/moin-2.0/issue/234) by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

The original report had attachments: Name for Subitems.png

----------------------------------------

the left sidebar listing all Subitems with the title Subitems on modernized theme could also seen as a Navigation to such items. 

In that case you want to have the word "Subitems" replaced by the current item name.

A tree-like visualization would make it more clear.

    
    Home
    └── Discussions

**Comment by RogerHaase** [comment]
I think Site Map was added/changed since this was opened. Is this still an issue?

**Comment by ThomasWaldmann** [comment]
@ReimarBauer ^^^

**Comment by RogerHaase** [comment]
per the old Bitbucket repo f9bccf2e3d1e on 2014-10-28, fixed #376.

(As a GIT newbie, dk how to track history of moved files.)
