### ISSUE TITLE
show meta information only if requested

### ISSUE THREAD

**Issue by ThomasWaldmann** [moinwiki/moin#239]
**[Original report](https://bitbucket.org/thomaswaldmann/moin-2.0/issue/239) by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

At least on foobar theme the metadata panel is using lots of space.

I think most of its information is currently relevant only for developers. That info maybe should only be shown on request. A way to do this is shown by the following example.

http://tympanus.net/codrops/2009/12/11/fixed-fade-out-menu-a-css-and-jquery-tutorial/

**Comment by RogerHaase** [comment]
Not sure what the foobar (aka basic) theme looked like in 2012 and how the example link could solve the problem. Reopen this issue if there is still a need.
