### ISSUE TITLE
Nicer editing of Extra MetaData (JSON)

### ISSUE THREAD

**Issue by ThomasWaldmann** [moinwiki/moin#280]
**[Original report](https://bitbucket.org/thomaswaldmann/moin-2.0/issue/280) by Tarashish Mishra (Bitbucket: [sunu](https://bitbucket.org/sunu), GitHub: [sunu](https://github.com/sunu)).**

----------------------------------------

Currently the *Extra MetaData (JSON)* field showed while creating or modifying an item is just a text area with a bunch of json.

It should be revamped to make metadata editing easier.

**Comment by RogerHaase** [comment]
closing, see #1067
