### ISSUE TITLE
Wrong contenttype saved on uploaded .gz files

### ISSUE THREAD

**Issue by ThomasWaldmann** [moinwiki/moin#307]
**[Original report](https://bitbucket.org/thomaswaldmann/moin-2.0/issue/307) by RogerHaase (Bitbucket: [RogerHaase](https://bitbucket.org/RogerHaase), GitHub: [RogerHaase](https://github.com/RogerHaase)).**

The original report had attachments: test-tgz.tar.gz

----------------------------------------

When uploading files the fast way:  Global Index > Actions > New Item > Upload Files > (select a file) > Start All; then the wrong contenttype is given to .gz files.

An example is the attached file, test-tgz.tar.gz, which has a single member, sitelutions_dns_update.sh.

After uploading the file to moin2, the contenttype is "application/x-sh" rather than the expected "application/x-tar". (see http://test.moinmo.in/test-tgz.tar.gz).

From idle:

    >>> mimetypes.guess_type('test-tgz.tar.gz')
    ('application/x-tar', 'gzip')
    >>> 

This seems to happen to all .gz files.  The .gz files were created on Windows 7 with 7-Zip.

**Comment by ThomasWaldmann** [comment]
@RogerHaase does this still reproduce? For me it is `application/gzip`.

**Comment by RogerHaase** [comment]
On Windows 10, Uploading a tar.gz file yields:  Content Type: Unknown [application/x-gzip]

Uploading a .tar file yields:  Content Type: TAR [application/x-tar]

Clicking on the .gz file from the global index results in a download dialog, clicking on the .tar file shows the archive contents within a table.

Is that close enough to close issue?

**Comment by ThomasWaldmann** [comment]
sounds good.
