### ISSUE TITLE
Discussion subitems with multiple names

### ISSUE THREAD

**Issue by ThomasWaldmann** [moinwiki/moin#363]
**[Original report](https://bitbucket.org/thomaswaldmann/moin-2.0/issue/363) by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

Currently we create a subitem Discussion of the name of the item.

With different names for one item we create currently different subitems.
This can be wanted. 

I think we should offer an already existing Discussion page or give the user the choice to create a new one or use an existing one. 

If a name becomes removed from the list, what should happen to the Discussion subitem? A notification for further cleanup, a meta entry, e.g. deprecated that helps to cleanup?

**Comment by RogerHaase** [comment]
A few months ago there were several related changes. 

Within Item Views, the discussion link is now shown as related to Subitems. 

When an item is deleted, there is a warning that all subitems will be deleted and the affected names are listed.

 If a deleted item has alias names, there are flash messages after the delete informing the user that the item persists with other names.

If there are other desired changes, a new issue is needed.
