### ISSUE TITLE
Upload text box is not editable

### ISSUE THREAD

**Issue by ThomasWaldmann** [moinwiki/moin#366]
**[Original report](https://bitbucket.org/thomaswaldmann/moin-2.0/issue/366) by Ashutosh Singla (Bitbucket: [ashu1461](https://bitbucket.org/ashu1461), GitHub: [ashu1461](https://github.com/ashu1461)).**

----------------------------------------

Try modifying an item, select a file to upload. Now you cannot remove the upload selection in case you wish to continue editing/save the text written in the text area.
So, we need a editable upload box here, so that the user can remove the file URL manually in case he doesn't want to upload a file.

**Comment by RogerHaase** [comment]
dup of #869.
