### ISSUE TITLE
language attributes missing

### ISSUE THREAD

**Issue by ThomasWaldmann** [moinwiki/moin#39]
**[Original report](https://bitbucket.org/thomaswaldmann/moin-2.0/issue/39) by Thomas Waldmann (Bitbucket: [thomaswaldmann](https://bitbucket.org/thomaswaldmann), GitHub: [thomaswaldmann](https://github.com/thomaswaldmann)).**

----------------------------------------

Warning: The html tag has no language attribute 

Found by: http://validator.w3.org/i18n-checker/

We need to think about how to handle this.

Our internal default language is english, but (assuming that we have a complete xx translation) if the user requests xx, he'll get all user interface texts in xx.

Another thing is the content, which does not need to be in xx also, but could be just any other language. So I guess we need another lang attr for the content (comes from revision metadata).

Inside the content, there could be yet other languages, so we might need more lang attrs and a way to deal with that.

Transclusions must also be considered.

**Comment by RogerHaase** [comment]
A starting premise is that all items should have a `language` attribute defined in metadata. This includes image, audio, video, drawing, binary files, compressed files and PDF items; based upon the theory that the items may have content that is related to a language and no harm will result in specifying a language when the content is agnostic.

The primary source of the language attribute for new items or revisions will be from the User Settings locale selected by a logged in editor. Items or revisions created by anonymous editors or users who have not selected a locale will default to the `locale_default` value specified in wikiconfig.py or /config/default.py.

When editing a text item, it will not be possible to flag a paragraph as being written in another language. Exceptions are:
* tranclusions within moinwiki
* an unknown and undocumented feature of html and markdown-html
* a future feature of parsers within moinwiki {{#!language fr\n...}}

There is no means of correcting a language attribute except by editing and saving a new revision of an item. Exceptions are:
* import19 should continue to process `#language xx` and add the language derived from locale_default for all other items
* a future feature of +modify may support a language selection under General Metadata

The lang and dir attributes will be placed only on the body and header tags and on any div tag having a class="moin-transclusion".
