### ISSUE TITLE
Change `User.is_subscribed_to()` method to accept a list of fqnames

### ISSUE THREAD

**Issue by ThomasWaldmann** [moinwiki/moin#401]
**[Original report](https://bitbucket.org/thomaswaldmann/moin-2.0/issue/401) by ana-balica (Bitbucket: [ana-balica](https://bitbucket.org/ana-balica), GitHub: [ana-balica](https://github.com/ana-balica)).**

----------------------------------------

Make the appropriate changes to the API, such that `User.is_subscribed_to()` accepts as a parameter a list of fqnames.

**Comment by RogerHaase** [comment]
There is no stated reason for needing this change. nor a benefit. One downside in the codereview user.py code within the is_subscribed_to method is this line:

    rev = get_storage_revision(fqname)

e.g. it does a read for every fqname. In the existing code where the item object is passed, there is no extra read.

Closing this issue as unwanted.
