### ISSUE TITLE
Stylus 0.42.3 has partially compressed CSS output

### ISSUE THREAD

**Issue by ThomasWaldmann** [moinwiki/moin#426]
**[Original report](https://bitbucket.org/thomaswaldmann/moin-2.0/issue/426) by RogerHaase (Bitbucket: [RogerHaase](https://bitbucket.org/RogerHaase), GitHub: [RogerHaase](https://github.com/RogerHaase)).**

The original report had attachments: stylus0.42.3.diff

----------------------------------------

Conclusion: stick with stylus 0.42.2 for now.

To reproduce the problem:

1. create a temporary repo
1. install or upgrade to stylus 0.42.2
1. do "./m css" to reveal outstanding foobar, modernized issues (https://codereview.appspot.com/82410043/)
1. commit to isolate unrelated issue from this issue
1. upgrade to stylus 0.42.3
1. do "./m css" again
1. do a diff to see changes, expect it to be same as the attached file named stylus0.42.3

For some unknown reason, both foobar and modernized css output seem to be partially compressed. In some cases, the compression starts while processing an import statement in main.styl, then stops when the next import starts.

Stylus 0.42.3 is about a month old.  No similar problems reported at https://github.com/learnboost/stylus/issues.

Opened an issue:  https://github.com/LearnBoost/stylus/issues/1456

Marking this as minor priority as there is an easy workaround by using 0.42.2.

**Comment by ThomasWaldmann** [comment]
https://github.com/stylus/stylus/issues/1456

**Comment by RogerHaase** [comment]
Stylus was removed 2020-08-06. Modernized theme uses CSS Variables.
