### ISSUE TITLE
destroy item/rev does not give an indication in history

### ISSUE THREAD

**Issue by ThomasWaldmann** [moinwiki/moin#45]
**[Original report](https://bitbucket.org/thomaswaldmann/moin-2.0/issue/45) by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

I think we should show in history that an item was destroyed. Currently this operation removes an item without any signal.

**Comment by RogerHaase** [comment]
Another way is to create an item with a special name ($$DestroyLog?) in the wiki default namespace. The item would be created by the first destroy action and appended to by subsequent destroy actions. 

The item could have an ACL allowing users to read the item, all other actions prohibited. The ACLs could be more restrictive, limit reading to logged-in users or only superusers,

If the item were formatted as a CSV file, then no addition code is required to view the item.

Suggested column headings:

* Name
* Old Name
* Namespace
* Last Modified Time (before destroy)
* Last Modified By (User ID last to modify before destroy)
* Destroyed Time
* Destroy User ID 
* Content Type
* Revision Number
* Size
* Comment (from destroy action)

Probably out of space, but maybe:

* Summary
* Tags
* Comment (from last modified)

**Comment by ThomasWaldmann** [comment]
@RogerHaase yeah, that would work, but I guess I would prefer a different solution without generating special wiki items.

The problem with that is destruction of acl protected pages. If these pages publically show up on that log page for everybody, there can be an information disclosure issue. E.g.:

```
ThomasWaldmann destroyed item "KillBill" with comment "Done. It was a mess."
```

So maybe we rather use the logging system for that (destroy is usually only allowed for admins anyway)?
