### ISSUE TITLE
Edit Preview Feature Missing

### ISSUE THREAD

**Issue by ThomasWaldmann** [moinwiki/moin#461]
**[Original report](https://bitbucket.org/thomaswaldmann/moin-2.0/issue/461) by RogerHaase (Bitbucket: [RogerHaase](https://bitbucket.org/RogerHaase), GitHub: [RogerHaase](https://github.com/RogerHaase)).**

----------------------------------------

In moin 1.9 there is a feature to preview an item before saving it.  This feature is missing from moin 2.

**Comment by RogerHaase** [comment]
TODO

In moim 1.9, edit preview saved a draft copy and provided an option to restore draft if item was not successfully saved. This feature is missing. Need a place to save draft and supporting javascript to save and restore..

In moin 1.9 edit preview, a user could doubleclick in draft preview area and the page would scroll to the corresponding line in the edit textarea.

**Comment by RogerHaase** [comment]
fixed by https://github.com/moinwiki/moin/pull/838
