### ISSUE TITLE
Page Trail lacks visits to reports

### ISSUE THREAD

**Issue by ThomasWaldmann** [moinwiki/moin#481]
**[Original report](https://bitbucket.org/thomaswaldmann/moin-2.0/issue/481) by RogerHaase (Bitbucket: [RogerHaase](https://bitbucket.org/RogerHaase), GitHub: [RogerHaase](https://github.com/RogerHaase)).**

----------------------------------------

Currently the page trail is updated only when a user visits the show (or +meta) view of an item.

If a user clicks on a direct link to different views of an item, such as +history, +modify, +highlight, +sitemap, +similar the page trail is not updated. For example if a user is viewing the moin page and pastes http://localhost:8080/+modify/creole into the url, the page trail is not updated (until the Save button is clicked).

If a user visits a "report" such as Global Index, My Changes, etc. (anything that has a value assigned to title_name in MoinMoin/apps/frontend/views.py) then that event is not added to the page trail.

This presents a confusing UI because it is impossible for a novice user to determine which of the various links and buttons on a wiki page will update the page trail.

----

Additional entries should be added to the page trail:

1. visits to "report" pages should be added so they appear similar to the url, e.g.: +history, +index, +mychanges...

2. visits to views of an item other than the show view will appear similar to the url, e.g.: +modify/moin, +history/moin, +meta/moin...

**Comment by RogerHaase** [comment]
do #1549 instead
