### ISSUE TITLE
wrong js link to item on item itselfs shown

### ISSUE THREAD

**Issue by ThomasWaldmann** [moinwiki/moin#49]
**[Original report](https://bitbucket.org/thomaswaldmann/moin-2.0/issue/49) by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

The original report had attachments: jslink_on_item.png

----------------------------------------

The js link shown on an item itselfs without transclusion is not needed.

The link there is wrong

**Comment by RogerHaase** [comment]
I believe this was fixed long ago. iirc whenever an image was displayed, a mouseover showed a transclusion-like link to the current item.
