### ISSUE TITLE
OpenID 2.0 obsolete, replaced by OpenID Connect

### ISSUE THREAD

**Issue by ThomasWaldmann** [moinwiki/moin#515]
**[Original report](https://bitbucket.org/thomaswaldmann/moin-2.0/issue/515) by RogerHaase (Bitbucket: [RogerHaase](https://bitbucket.org/RogerHaase), GitHub: [RogerHaase](https://github.com/RogerHaase)).**

----------------------------------------

Per https://developers.google.com/accounts/docs/OpenID Google is dropping OpenID 2.0 support on 2015-04-20.

Supporting OpenID Connect will require existing OpenID support (see #345) to be reworked, replacing python-openid with pyoidc or Flask-oidc, etc. See http://pyoidc.readthedocs.org/en/latest/index.html, https://github.com/rohe/pyoidc, https://pypi.python.org/pypi/flask-oidc/0.1.2    

Pyoidc is not available on pypi and does not appear easy to install on Windows.

**Comment by ThomasWaldmann** [comment]
I guess we just drop openid for now. In the past (moin 1.9), it somehow was a troublemaker and didn't get much maintenance either (iirc we ended up with commenting out the code to keep the rest working).

**Comment by cburmeister** [comment]
@ThomasWaldmann are there any plans to add OIDC support in Moin 2?

**Comment by ThomasWaldmann** [comment]
@cburmeister no plans by me.

**Comment by cburmeister** [comment]
@ThomasWaldmann thanks for the reply! Is there an estimated date as to when Moin 2 will be production ready?

We're investigating Moin 1.9 and 2 as possible solutions for a small project and implementing an OIDC authenticator will be necessary. If we were to do this do you think we should focus our efforts around Moin 1.9 or 2? Any advice appreciated, thanks!

**Comment by ThomasWaldmann** [comment]
No estimates, they would be wrong anyway.

If you need something for prod, you'ld still need to use moin 1.9.x. If you use moin2, it is either because you want to help testing or because you could fix issues that pop up yourself anyway.

**Comment by cburmeister** [comment]
@ThomasWaldmann okay thanks for the advice! If we end up rolling our own OIDC authenticator for 1.9 I'll let ya know!
