### ISSUE TITLE
Inconsistent mime type usage for .moin

### ISSUE THREAD

**Issue by ThomasWaldmann** [moinwiki/moin#528]
**[Original report](https://bitbucket.org/thomaswaldmann/moin-2.0/issue/528) by RogerHaase (Bitbucket: [RogerHaase](https://bitbucket.org/RogerHaase), GitHub: [RogerHaase](https://github.com/RogerHaase)).**

----------------------------------------

/util/mimetype.py declares the mimetype for the .moin, creole, and mediawiki suffixes:

    '.moin': 'text/x.moin.wiki',
    '.creole': 'text/x.moin.creole',
    '.mediawiki': 'text/x-mediawiki',

But in moin2, the .moin suffix has been used for binary moin2 backups for several years. See /contrib/serialized/items.moin and the backup/restore commands of make.py.

If the above mimetypes are unused as coded, they should be deleted.

**Comment by RogerHaase** [comment]
not a problem
