### ISSUE TITLE
ACL performance issue

### ISSUE THREAD

**Issue by ThomasWaldmann** [moinwiki/moin#568]
**[Original report](https://bitbucket.org/thomaswaldmann/moin-2.0/issue/568) by RogerHaase (Bitbucket: [RogerHaase](https://bitbucket.org/RogerHaase), GitHub: [RogerHaase](https://github.com/RogerHaase)).**

----------------------------------------

In storage/middleware/protecting.py there is `class ProtectingMiddleware(object):` which uses acl_mapping as a list rather than a dict. When a user chooses to Show a very simple item, the `def _get_configured_acls(self, fqname):` method within the above class is called 40+ times. If the page is more complex, with embedded links, the method is called many more times.

If the wiki has many namepaces, looping through the acl_mapping list may become a performance issue. Given the #567 bugfix, the acl_mapping object should probably be created as a dict rather than a list.

Also the reason for so many calls with the same parameters should be investigated - maybe the namespace ACLs could be attached to the item object early in the processing of a Show transaction.

**Comment by RogerHaase** [comment]
fixed, see #1069
