### ISSUE TITLE
check sdist package contents

### ISSUE THREAD

**Issue by ThomasWaldmann** [moinwiki/moin#609]
#597 changed the way the package contents are determined.

"everything tracked in git" is the default rule implemented by `setuptools_scm`, so we only need to care for exceptions from that in `MANIFEST.in`.

TODO: verify the contents of the sdist, is all we need in there?

esp. translation files, css / js and other web files come to mind.

practically test the usability of the sdist (pip/pypi package) in a clean env.

**Comment by ThomasWaldmann** [comment]
```
python setup.py sdist
# result is in dist/...
```

**Comment by UlrichB22** [comment]
Moin package from test.pypi.org can be installed successfully. Is there anything left to do?

**Comment by ThomasWaldmann** [comment]
MANIFEST.in needs an update (at least .travis.yml should be removed).

Also, the created sdist might have unwanted files in it (files that are git committed, but not wanted in an sdist).

@UlrichB22 If you tested the pypi package and it fully works, guess at least any not-committed but wanted file is contained in there.

**Comment by UlrichB22** [comment]
Except for the 'travis' leftover I did not find any unnecessary files in the sdist.
