### ISSUE TITLE
check commands for users (not: developers)

### ISSUE THREAD

**Issue by ThomasWaldmann** [moinwiki/moin#631]
for developers, we can assume that `.` is the repo root and find stuff from there.

a normal user who just did `pip install moin` will not have the file structure as in the repo, but just whatever we install from the package  (somewhere in sys.path). also, we can not assume anything special in `.` (cwd).

**Comment by RogerHaase** [comment]
Have uploaded moin to testpypi, and installed same into a venv on both windows and ubuntu. Created empty and sample wiki instances. Updated and saved instances. No problems noted. Closing.
