### ISSUE TITLE
use iso datetime formatting

### ISSUE THREAD

**Issue by ThomasWaldmann** [moinwiki/moin#633]
```
 Metadata of 'FooBar'
...
    Modified Time: Sep 1, 2018, 10:14:44 PM
```

**Comment by ThomasWaldmann** [comment]
foo

**Comment by ReimarBauer** [comment]
bar

**Comment by ThomasWaldmann** [comment]
flask-babel injects datetimeformat into the templating env and we use that all over the place.

thus, if the browser request the english (US) lanuage, the formatting is like the locale specifies for the US.
for german, you'ld get the german formatting, etc.

thus, this is a non-issue.
