### ISSUE TITLE
remove autogenerated docs from git?

### ISSUE THREAD

**Issue by ThomasWaldmann** [moinwiki/moin#640]
`docs/devel/api/*.rst` is autogenerated.

not sure why we have it in the repo, but we could remove it.

**Comment by ThomasWaldmann** [comment]
https://moin-20.readthedocs.io/en/latest/devel/api/MoinMoin.html we have the api docs there, check if we can move the autogeneration to there also.

**Comment by RogerHaase** [comment]
We have link to local docs under User on UI which works if user does "m docs", those api files are used in docs generation. If we move "m api" action in make.py to be part of "m docs" then we can remove the api docs from repo.

**Comment by ThomasWaldmann** [comment]
Sounds good, can you make a PR?

**Comment by ThomasWaldmann** [comment]
Fixed by #658.
