### ISSUE TITLE
Output of "m dump-html" displays as plain text in Chrome, Opera, IE11

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#641]
If you create a static dump of a wiki using "m dump-html" the files created have the same names as those in the wiki (Home, creole, moin, etc for the sample wiki). While these display as expected using Firefox and Edge, they now display as plain text using the Chrome, IE11 and Opera browsers. iirc, all browsers displayed these files as html, png, etc. a few years ago.

Renaming these files to have the correct suffixes is hard because all internal links must also change.

Adding `<meta content-type="text/html" />` to `<head>` does not  resolve issue.  

Did not test on *nix.

**Comment by ThomasWaldmann** [comment]
The problem might be the content-type detection in the absence of a wiki server sending apropriate http headers.

We need to check if the file contains:

```
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
```
If we have that, the browser could at least look at that and follow that - then I would consider it a Chrome bug. If we do not have it, we should try to add it.

**Comment by ThomasWaldmann** [comment]
BTW, that is only a problem if one directly points a browser at such a dump.

If the dump is served on the web, using some web server, the web server can be configured to emit appropriate content-type header.

**Comment by ThomasWaldmann** [comment]
@RogerHaase i added some markup to your report, otherwise stuff like `<...>` just vanishes.

**Comment by RogerHaase** [comment]
Current header is:

    <head>
                <meta charset="utf-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <title>creole - My MoinMoin</title>
    <link rel="shortcut icon" href="static/logos/favicon.ico" />
                    <link media="all" rel="stylesheet" href="static/css/normalize.css" />
                    <link media="all" rel="stylesheet" href="+serve/pygments/css/colorful.css" />
                    <link media="all" rel="stylesheet" href="+serve/font_awesome/css/font-awesome.css" />
                    <link media="all" rel="stylesheet" href="static/css/common.css" />
                    <link media="all" rel="stylesheet" href="_themes/topside_cms/css/theme.css" />
                    
    <link rel="alternate" title="creole changes" href="+feed/atom/creole" type="application/atom+xml" />
    

    </head>

Adding the ...http-equiv... manually to one of the disk files did not resolve the issue

**Comment by ThomasWaldmann** [comment]
Hmm, ok, then they do not snoop into the file. Which might be good from a security standpoint, but bad for this usecase. One can still use a web server to solve (or another browser).

**Comment by ThomasWaldmann** [comment]
I tested under Linux and can confirm FF works, Chromium not - and the http-equiv does not help.

So I guess we can not do anything about that, we can just document that one needs to serve the files with a web-server and add a content-type header with that (and even there it can go wrong, as text/html will not be correct for all items).

**Comment by RogerHaase** [comment]
The browser behavior was added to https://moin-20.readthedocs.io/en/latest/admin/serve.html#create-and-serve-a-static-wiki-image several months ago. Closing issue as there is nothing left to do.
