### ISSUE TITLE
openid issues - remove openid support?

### ISSUE THREAD

**Issue by ThomasWaldmann** [moinwiki/moin#646]
is openid as we have it still useful?

see #515 and #345 and https://bitbucket.org/thomaswaldmann/moin-2.0/commits/a6bb853 .

is it still popular enough to have builtin support in moin?

do we use the right library (seems stale) or is `python-openid2` better?

who maintains the openid code?

note: if no-one is interested in maintaining the openid related code, we might just drop it.

**Comment by RogerHaase** [comment]
I was last person to touch parts of the openid code. Openid was working with yahoo and google for a while. Google dropped support for openid(1) soon after it was working, then yahoo followed.  afaik, the present code is completely broken, but possibly useful as a starting point.

Openid 2 is also a dated term, OpenID Connect is the third generation of OpenID technology. https://openid.net/connect/faq/

**Comment by ThomasWaldmann** [comment]
If it is not directly useful, it could be also retrieved from repo history.

**Comment by ThomasWaldmann** [comment]
Hmm, in general, I guess we should research whether there are libraries (flask extensions?) out there that do that stuff for us, so we do not need to maintain such code.

`social-app-flask` and co maybe? it doesn't seem to be as alive as `social-app-django` though.

**Comment by ThomasWaldmann** [comment]
I'll remove openid now...
