### ISSUE TITLE
review summer of code projects

### ISSUE THREAD

**Issue by ThomasWaldmann** [moinwiki/moin#689]
do we still have stuff to merge from them?
- https://moinmo.in/GoogleSoc2012
- https://moinmo.in/GoogleSoc2013
- https://moinmo.in/GoogleSoc2014
- https://moinmo.in/GoogleSoc2015

**Comment by RogerHaase** [comment]
I reviewed the list years ago, the only thing of value was VipulSharma's improvements to the Issue Tracker. This was added to the main repo along with several fixes I made on top of Vipul's code. But adding issues to Issue Tracker still broke wiki main code.  The issue tracker and blog links were removed from the UI, see #576.

The other project from 2015 was YaskSrivastava's port of the modernized theme to Bootstrap.  The result was rather ugly and was not added to the main repo.

All the project repos were on Bitbucket and are no longer available there. I still have a local copy of Yask's repo.
