### ISSUE TITLE
MoinMoin markup - broken nested tags

### ISSUE THREAD

**Issue by steel-ne** [moinwiki/moin#696]
I've made a linkable preview, as it described in docs:
`[[/inner2.png|{{/inner2.png||width=500}}]]`

It generates next HTML:
`<p data-lineno="21" style=""><a href="/wiki/Home/inner2.png">{{/inner2.png</a></p>`

When I remove `||width=500` it generates correct link, but image is full-sized
`<p data-lineno="21" style=""><span class="moin-item-wrapper moin-transclusion"><a href="/wiki/Home/inner2.png"><span class="moin-transclusion" data-href="/wiki/Home/inner2.png"><img alt="wiki/Home/inner2.png" src="/wiki/+get/+543ed488076b4e60b15141a343f631c7/Home/inner2.png"></span></a><a class="moin-item-overlay-ul" href="/wiki/Home/inner2.png">↘</a><a class="moin-item-overlay-lr" href="/wiki/Home/inner2.png">↖</a></span></p>`

**Comment by ThomasWaldmann** [comment]
Can you try this:
```
[[/inner2.png|{{/inner2.png|foo|width=500}}]]
```

**Comment by steel-ne** [comment]
just the same. 
`<p data-lineno="23" style=""><a href="/wiki/Home/inner2.png">{{/inner2.png</a></p>`

**Comment by steel-ne** [comment]
I found a link's regexp in `src/moin/converter/moinwiki_in.py:666`:

```
...
           (
                [|]
                \s*
                (?P<link_text> [^|]*? )
                \s*
            )?
...
```

it means, that **link_text** is "anything without '|'"

**Comment by steel-ne** [comment]
I'v made a dirty hack:
```

    inline_link = r"""
        (?P<link>
            \[\[
            \s*
            (
                (?P<link_url>
                    (%(uri_schemes)s):
                    [^|]+?
                )
                |
                (
                    (?P<link_interwiki_site>[A-Z][a-zA-Z]+)
                    :
                    (?P<link_interwiki_item>[^|]+) # accept any item name; will verify link_interwiki_site below
                )
                |
                (?P<link_item> [^|]+? )
            )
            \s*
            (
                [|]
                \s*
                (?P<link_text> [^|]*?|([^|]*?\{\{.*?\}\}[^|]*?) )
                \s*
            )?
            (
                [|]
                \s*
                (?P<link_args> [^|]*? )
                \s*
            )?
            \]\]
        )

```
