### ISSUE TITLE
import error when wikiconfig_local.py imports wikiconfig_editme.py

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#698]
This happens because the cwd (repo root) is not in sys.path.

Workaround 0c579db0991753b27fb3de4f7e6b2a7fe94470ae applied to src/moin/app.py on 2018-09-28.

**Comment by ThomasWaldmann** [comment]
Here it is like this:
```
(moin-venv-python) tw@tux:~/w/moin$ python
Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path
['', '/home/tw/w/moin-venv-python/lib/python2.7', '/home/tw/w/moin-venv-python/lib/python2.7/plat-x86_64-linux-gnu', '/home/tw/w/moin-venv-python/lib/python2.7/lib-tk', '/home/tw/w/moin-venv-python/lib/python2.7/lib-old', '/home/tw/w/moin-venv-python/lib/python2.7/lib-dynload', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/home/tw/w/moin-venv-python/local/lib/python2.7/site-packages', '/home/tw/w/moin/src', '/home/tw/w/moin-venv-python/lib/python2.7/site-packages']
>>> 
```
The first entry means to import from cwd.

**Comment by ThomasWaldmann** [comment]
About the workaround added: it only checks for the full path of cwd being in sys.path and does not check "" (empty string) being in there.

**Comment by RogerHaase** [comment]
From my reading the '' in sys.path happens when running the python interpreter from the command line or executing "python -m xxx.py". When running "python C:/git/moin-venv-python/Scripts" the first entry in sys.path is C:/git/moin-venv-python/Scripts and the cwd is not in sys.path.

Will change the code to check for '' and close this issue.
