### ISSUE TITLE
How to setup PyCharm run/debug configuration for tox

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#702]
Jetbrains has instructions here: https://www.jetbrains.com/help/pycharm/run-debug-configuration-tox.html

But if the normal virtualenv moin-venv-python is used there is an error on startup, line 8 in _jb_tox_runner.py:

    from tox import config as tox_config, session as tox_session

If the virtualenv under moin/.tox/py27 or moin/.tox/flake8 is used then breakpoints set in moin code do not break. Breakpoints set in vvirtualenv code do break.

**Comment by ThomasWaldmann** [comment]
Guess this might be because we use `pip install -e .` (?) for the main env, while tox might use `pip install .` (?) for the testing env it builds below `.tox`.

**Comment by RogerHaase** [comment]
see http://moinmo.in/MoinMoin2/IdeSetup
