### ISSUE TITLE
.tox/py27, .tox/flake8  virtualenvs do not get updated

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#703]
The first time tests are run after making a new moin clone a new .tox directory is created. There are 2 virtualenv within .tox; one at /.tox/py27/ and another at /.tox/flake8/. These both contain more packages than moin-venv-python, additions include pytest, tox and others.

When m quickinstall is run and updated packages are installed, the /.tox/py27/ and /.tox/flake8/ virtualenvs are not updated. Running tests does not update the installed packages and the tests are run with outdated packages.

**Comment by ThomasWaldmann** [comment]
`tox --recreate ...`
