### ISSUE TITLE
Destroy fails under windows if item has been recently viewed

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#712]
This is an update to the closed issue #197.

If an item is viewed on Windows, then a delete attempt is made via the Global Index, there is a success message and the item name is removed from the current view. Log messages indicate success:

    "POST /+ajaxdestroy HTTP/1.1" 200 -

But when the Global Index is refreshed, the deleted item is present.

The likely cause is the file has been left open and Windows refuses to delete the open file.

There are 2 problems:

* if the delete fails, it should be detected and a failure message should be shown to the user.
* the item file should be closed after an item is viewed (review fixes for #197 issue).

**Comment by ThomasWaldmann** [comment]
We need to check which file is still open / where the conflict is: item storage or whoosh index.

**Comment by RogerHaase** [comment]
Not just a windows issue, will open a new issue
