### ISSUE TITLE
Missing meta tags for keywords, author, description

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#730]
In `/themes/__init__.py` there is:

    self.meta_items = []  # list of (name, content) for html head <meta>

and in /templates/base.html there is:

                {%- for name, content in theme_supp.meta_items -%}
                    <meta name="{{ name }}" content="{{ content }}" />
                {%- endfor %}

but there is no code to populate self.meta_items. 

We probably want"

|Name|Content|
|----|----|
|keywords|item tags|
|description|item summary|
|author|last item editor|

**Comment by ThomasWaldmann** [comment]
I agree about item tags and summary, but imho the last editor should not be put as author, this would in many cases leave a wrong impression and might be unfair to the author(s) putting the most work into a page. just putting all editor in there is maybe more correct, but can be rather messy (e.g. if there are a lot of authors, some anonymous) and still might not reflect the main authors correctly.

I guess it is easier just not to have author meta in html head.
