### ISSUE TITLE
offer templates based on state of user

### ISSUE THREAD

**Issue by ReimarBauer** [moinwiki/moin#746]
Currently a not logged in user can select from templates 
`users/HomePageTemplate`

The creation of that item fails somehow, It can't expand `= @ME@ =` 
Saving the item creates some faulty state of this. The view "create new item" is loaded afterwards. 
Redoing the same template users/HomePageTemplate gives "Item(s) named FooBar already exist."

We have to verify that templates which needs an user object can't be used without.

**Comment by RogerHaase** [comment]
I think this is mostly a namespace issue. The users/HomePageTemplate is in the users namespace and should not be offered as a template when a page is created in the default namespace. 

The result is lots of broken links, etc.

**Comment by RogerHaase** [comment]
Or, maybe the namespace meta data in the template should be overridden with the current namespace. That way there could be namespace of templates if that was wanted. 

(btw, For a non-logged in user, @ME@ is expanded to anonymous)

**Comment by ReimarBauer** [comment]
Those are all user centric

- ME
- USERNAME
- USER
- SIG
- MAILTO
- EMAIL

**Comment by RogerHaase** [comment]
Closing this, with b9ed58e the problem cannot be reproduced; with 17d83e8 the broken Item Views links when viewing the users namespace were corrected; with 89fe9cd the Navigation link text was clarified.

To clarify the original problem report, the item was saved in the users namespace without leaving a clue. Its location would be revealed only if the user knew to do a "+index/users".
