### ISSUE TITLE
handle_variables rules

### ISSUE THREAD

**Issue by ReimarBauer** [moinwiki/moin#747]
We currently search through a revision on saving for replacing variables always if there is one single @ is used

We can speedup this if we are more exact on 
```
 if '@' not in data:
            return data
```
current rules are Variables are in uppercase and starting with @ character and ending witjh @ character

This should maybe replaced by a regex checking for this pattern.

**Comment by sanzcarlos** [comment]
This character can be used to write email addresses or passwords.

Maybe to solve the problem, you could use an scape character when someone wants to write this character on a page

**Comment by ThomasWaldmann** [comment]
@sanzcarlos this is not a problem as it only replaces stuff like `@VARNAME@`.

@ReimarBauer please no premature optimizations. afaik the code works, a ms more or less does not matter, and the root cause for @sanzcarlos problem is not clear yet.
