### ISSUE TITLE
favourite Item Views

### ISSUE THREAD

**Issue by ReimarBauer** [moinwiki/moin#749]
The current list of views on the left hand navigation shows a complex list and needs reading time, to sort of the action I want.

**Item Views**

- Show
- Download
- History
- Modify
- Discussion
- Subitems
- Highlight
- Meta
- Rename
- Convert
- Delete
- Destroy
- Site Map
- Similar

We may want most used on top e.g. favourites?, or a user based order based on what the user regualary calls. Also maybe a short three or four items list

My favourites:
 * Modify
 * Download
 * History
 * Delete

May be all other views where they are

**Comment by RogerHaase** [comment]
How about?

    Show
    Modify
    History
    Download
    Delete
    Add Link
    Subscribe
    Rename
    Subitems
    Discussion
    Highlight
    Meta
    Site Map
    Similar
    Convert
    Destroy
    Comments*
    Transclusions*

where comments and transclusions only appear if there are comments and transclusions on the page.
