### ISSUE TITLE
Global Index file upload Cancel All button fails

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#764]
Drag and drop multiple files to the Global Index file upload area. Then click the Cancel All button. 

The Start All and Cancel All buttons are not removed/hidden. The files that were cancelled cannot be copied to the drag and drop area, but other files can be. The page must be reloaded to upload the files that were cancelled.

If the "Cancel" buttons are used to cancel all of the individual files, the Start All and Cancel All buttons are not removed/hidden and the drag and drop area remains acts as above: the cancelled files cannot be dragged and dropped, but other files work as expected.

The use of the "file_upload_cancel" class in both the Cancel All and Cancel file buttons looks suspect.

From forms.html:

    <button class="moin-button file_upload_cancel" type="button" style="display:none;">{{ _("Cancel All") }}</button>
    ...snip...
    <td class="file_upload_cancel"><button class="moin-button" type="button">{{ _("Cancel") }}</button></td>

Current version of Jquery File Upload from Xstatic is 4.4.2 per specs on setup.py, current version on https://github.com/blueimp/jQuery-File-Upload is 9.27.0, current version from https://pypi.org/project/XStatic-jQuery-File-Upload/ is 9.23.0.1.

**Comment by ThomasWaldmann** [comment]
I updated jfu recently for another project (therefore the quite recent xstatic pkg) and it just worked.
We could try same for moin...

**Comment by RogerHaase** [comment]
dup of #869.
