### ISSUE TITLE
make output of ACL read access-denied consistent

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#791]
In many instances moin 2 silently suppresses item names when the user does not have read access. These include Global Index, PagenameList macro, and probably other places.

In other instances, such as includes and transclusions, users are given an admonition-like error message stating "Access Denied, transcluded content suppressed." Note the error message does not include the name of the missing page. 

For better consistency, should ACL read violations within includes and transclusions fail silently, e.g. no output?

Although the Access Denied message above does not reveal the item name, it can be easily found by clicking the Highlight link.

**Comment by ThomasWaldmann** [comment]
There's a difference between:
- discovering the name of an item you are not allowed to see
- reading the contents of an item for which you know the name already, but you are not allowed to see the contents

I am not sure we should change anything at all here, usually this is a maybe rather a problem of the specific content and acls set on it inconsistently. So an error message might be useful to indicate that there is a fix needed.

**Comment by RogerHaase** [comment]
OK, but we want to be flexible and configurable. At present, the div has a class of "warning" to style the message. We can add a class of "moin-read-denied" so admins that want to suppress the message can use snippets.html to add a bit of CSS hiding the message. 

No change to existing UI.

**Comment by ReimarBauer** [comment]
We had a similiar discussion on some other product scanner. There one of the results was that a name of an item can be a not wanted leak of information e.g. application_for_company_ If that item can be connected to its writer than this is a problem. 
From the discussion we learned that there should be only one obvious way. Any kind of information grabber should on all circumstances behave like configured. If the policy is to show a place holder, always a place holder should be used. 

In our case we may need to think on such place holders also from the option, that a general policy can change. In that case I would expect that the placeholder name ones it was set is kept and shown.
