### ISSUE TITLE
Cannot override default favicon

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#799]
In /apps/frontend/views.py there is:

    @frontend.route('/favicon.ico')
    def favicon():
        # although we tell that favicon.ico is at /static/logos/favicon.ico,
        # some browsers still request it from /favicon.ico...
        return app.send_static_file('logos/favicon.ico')

Which seems to be a backup in case an old browser does not understand the code in /templates/base.html:

   `<link rel="shortcut icon" href="{{ url_for('static', filename='logos/favicon.ico') }}" />`

Note: rel="shortcut icon" is obsolete, for html5 is should be rel="icon".

The base.html code should be moved to snippets.html and enclosed in a macro that may be customized by a wiki admin.

The /apps/frontend/views.py code can probably be left as is assuming all modern browsers support <link rel="icon....

**Comment by RogerHaase** [comment]
Fixed by e22870a and ab81653. Removed code serving favicon.ico from views.py because serving favicon from server root is no longer recommended. Link tag with rel="icon" is preferred approach.

**Comment by ThomasWaldmann** [comment]
Besides what the standards / recommendations say:

Did you test with current browsers, whether they do it like expected or still request `/favicon.ico`?

The main reason why I added that code years ago was that I did not want to have lots of 404 in log output for that.

**Comment by RogerHaase** [comment]
I tested with Chrome, Firefox, Opera, IE 11, and Edge on Windows 10. All
loaded a new favicon except Edge. Edge refused to load the new favicon.

I checked the moin2 server logs, no 404s.

I checked my old moin 1.9.x app server logs - browsers are loading
/favicon.ico as a default when there is no `<link rel="icon"...` .
