### ISSUE TITLE
not possible to "check for uncommitted API doc changes"

### ISSUE THREAD

**Issue by kwatsen** [moinwiki/moin#806]
docs/devel/development.rst says:
```
* check for uncommitted API doc changes
    ./m api  # Windows m api
    git diff  # verify nothing changed
```

But `./m api` returns:
```
Error: unknown menu selection "api"
```

Should the ability to "check for uncommitted API doc changes" be [re-]added, or should this text be removed from the docs?

**Comment by RogerHaase** [comment]
Good catch, the api command was merged into the docs command last November,
but docs were not updated. Push in progress.
