### ISSUE TITLE
store a list of names into meta[NAME]

### ISSUE THREAD

**Issue by ThomasWaldmann** [moinwiki/moin#81]
**[Original report](https://bitbucket.org/thomaswaldmann/moin-2.0/issue/81) by Thomas Waldmann (Bitbucket: [thomaswaldmann](https://bitbucket.org/thomaswaldmann), GitHub: [thomaswaldmann](https://github.com/thomaswaldmann)).**

----------------------------------------

currently, meta[NAME] has a single unicode value (the item name).

it could be changed to be a list of unicode item names.

all these names would be valid names for the item, maybe with some preference on the first one (e.g. if we need to display the name).

like for tags, searching for name_exact:foo would automatically search the list for a member "foo".

practically, this would make the following stuff possible:
* having "alias names" for items
* make same thing show up at multiple places (like hardlinks in file system)
* not needing redirect items if you "rename" an item (== add another name to the list) that is linked from other items or from the outside
* the name list could have zero elements, making the item somehow vanish from the surface (namespace, index) and be "deleted" (but still being there in storage, just not having a name, but still an itemid, revisions, etc.). the name(s) it had before can still be fetched from its parent revision.

**Comment by RogerHaase** [comment]
issue 11 of 13 fixed by commit fixing #580

**Comment by RogerHaase** [comment]
issue 13 of 13 fixed long ago.

issue 12 of 13 not possible, rename form insists the name field has a name. Seems like odd function that would need explanation if implemented.

issue 9 of 13 has admin trash view since long ago

issue 8 of 13 fixed long ago.

opened new issue for 6 of 13, see #1119

issue 5 of 13 tested, found #1118 bug.

Closing this issue.
