### ISSUE TITLE
check user.search_users behaviour

### ISSUE THREAD

**Issue by ThomasWaldmann** [moinwiki/moin#83]
**[Original report](https://bitbucket.org/thomaswaldmann/moin-2.0/issue/83) by Thomas Waldmann (Bitbucket: [thomaswaldmann](https://bitbucket.org/thomaswaldmann), GitHub: [thomaswaldmann](https://github.com/thomaswaldmann)).**

----------------------------------------

some code is expecting it to return whoosh documents and then accessing doc[NAME] for example. this code currently fails as it returns Revisions.

some other code is dealing with it, processes the revisions correctly, e.g. by accessing rev.meta[NAME].

decide on which behaviour is correct, then fix all callers.

also check acl behaviour. access to user items might be prohibited by ACLs in a production configuration.

**Comment by RogerHaase** [comment]
Could not find any problems to fix in user.py, assume this was fixed long ago.

Found problems documented in #1707 while researching this issue.

Closing, nothing left to do.
