### ISSUE TITLE
Are there any trusted authentication methods?

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#835]
https://moin-20.readthedocs.io/en/latest/admin/configure.html?highlight=acls#acls-special-groups  says:  Trusted - a virtual group containing every logged-in user who was logged in by some specific “trusted” authentication method.

But in auth/_ _init_ _.py BaseAuth sets self.trusted=False; there seems to be no code or option to set any auth method to trusted=True. 

Is it intended that for ACL purposes, all logged in users are Known but not Trusted?  To get trusted status, a wiki admin must create/modify an auth method and set it to trusted=True?

**Comment by ThomasWaldmann** [comment]
The idea behind `trusted` was that it could be used e.g. for `http auth` with something on the web server layer authenticating against a database with trusted users (e.g. ldap / active directory in a company).

As this database would have only administered entries (and not entries self-created by the user as we support(ed) it for moin user profiles), these have higher trust than a self-created profile, which should be just `known`.

**Comment by RogerHaase** [comment]
Then in /auth/http.py

    def __init__(self, autocreate=False, realm='MoinMoin', coding='iso-8859-1', **kw):

should be:

    def __init__(self, trusted=true, autocreate=False, realm='MoinMoin', coding='iso-8859-1', **kw):

and in /auth/ldap_login.py

    def __init__(
        self,
        server_uri='ldap://localhost',  # ldap / active directory server URI

should be:

    def __init__(
        self,
        trusted=True,
        server_uri='ldap://localhost',  # ldap / active directory server URI

???
