### ISSUE TITLE
renaming an item back to original name requires rebuilding index

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#840]
If there is an item named A that is renamed to AA, then it cannot be renamed back to A directly. 

Instead there is a flash message : An item named A already exists in the namespace.

If the wiki admin rebuilds the indexes with a "./m index", then the item can be renamed back to A.

**Comment by ThomasWaldmann** [comment]
This sounds like "rename" is not updating the index or not updating it correctly.

After a user is modifying wiki contents, the index should be always in a consistent state and not require manual index update by the admine.

**Comment by RogerHaase** [comment]
Cannot reproduce this issue. The code in `items/__init__.py` `_rename` looks OK.

**Comment by RogerHaase** [comment]
still cannot reproduce, closing
