### ISSUE TITLE
Inquiry into its features 

### ISSUE THREAD

**Issue by DonaldTsang** [moinwiki/moin#848]
1. Does this Wiki have branching/forking for mirrors?
2. Does this Wiki have user permissions and management?
3. Does this Wiki have cross-links for pages to link without URL?
4. Does this Wiki have forum/chats for page discussion?
5. Does this Wiki have page versioning?
6. Does this Wiki have page categorization?

**Comment by RogerHaase** [comment]
https://moin-20.readthedocs.io/en/latest/

Does this Wiki have branching/forking for mirrors? No, but maybe: https://moin-20.readthedocs.io/en/latest/admin/serve.html#create-and-serve-a-static-wiki-image

Does this Wiki have user permissions and management? Yes, https://moin-20.readthedocs.io/en/latest/admin/configure.html#authorization

Does this Wiki have cross-links for pages to link without URL? Yes, https://moin-20.readthedocs.io/en/latest/user/markups.html#markups-supported-by-moinmoin

Does this Wiki have forum/chats for page discussion? Yes

Does this Wiki have page versioning? yes 

Does this Wiki have page categorization? Yes, tags

**Comment by DonaldTsang** [comment]
@RogerHaase question about categorization: Is it possible to create "categories of categories" like Wikipedia does?

**Comment by ThomasWaldmann** [comment]
no git.

you usually put tags on items to categorize them. you can manually add more items (with tags) to build a link structure, but guess no direct support yet categories of categories.

**Comment by DonaldTsang** [comment]
@ThomasWaldmann maybe I am not clear here, for example
https://en.wikipedia.org/wiki/Category:Ranking_functions
has a list of pages and subcategories (Link Analysis),
and also a list of "mother categories" (Information retrieval techniques).

Also with https://moin-20.readthedocs.io/en/latest/admin/serve.html#create-and-serve-a-static-wiki-image
Is there a dump version that dumps Markdown versions instead of HTML?

**Comment by RogerHaase** [comment]
there is a command line: `moin item-get` to dump a single item to a directory. 

https://moin-20.readthedocs.io/en/latest/man/moin.html?highlight=moin%20interface#moin-interface

but nothing that will select a group of files based on content type. Writing a command to dump all markdown files to a directory would not be difficult (depending upon how many other selection criteria are added), but no one is working on that feature. 

There are searching options other than tags, see 

https://moin-20.readthedocs.io/en/latest/user/search.html?highlight=searching%20and%20finding#searching-and-finding

**Comment by renato67** [comment]
Hi,
I saw all the messages that come in this list.
I'm wondering  if I have to update my installation of moin2.

Thank you

Renato

Il giorno mar 16 lug 2019 alle ore 21:28 RogerHaase <
notifications@github.com> ha scritto:

**Comment by RogerHaase** [comment]
If you want to help find new bugs, you should do a "git pull" and "./m
quickinstall" every month or so.

If you are happy with your current feature set, the "If it ain't broke,
don't fix it" rule applies.

In a few weeks/months, the master branch will be converted to require
Python 3.5+, possibly introducing new bugs. So you may want to hurry your
update or delay it.

iirc, since you installed moin there a few changes:
* option for displaying ISO 8601 dates for logged-in users
  * bug fix for inconsistent display of dates
* fix bug edit preview failed when editing user home pages
* edit drafts are saved when doing an edit preview
* edit locking, may need wikiconfig/wikiconfig_editme changes
