### ISSUE TITLE
atom code deprecation?

### ISSUE THREAD

**Issue by ThomasWaldmann** [moinwiki/moin#850]
```
/home/user/w/moin/src/moin/apps/feed/views.py:18:
DeprecationWarning: 'werkzeug.contrib.atom' is deprecated as of version 0.15 and will be removed in version 1.0.
```

Strange, back then I had the impression that atom is the more modern/cleaner approach than rss.

Does anyone know why?

What's the current "state of art" regarding feeds?

**Comment by ThomasWaldmann** [comment]
https://github.com/lkiesow/python-feedgen/ maybe we could use this.

the werkzeug guys recommend using some feed generation library (but don't point to anything specific).

**Comment by sblondon** [comment]
According to the [Changelog](https://werkzeug.palletsprojects.com/en/1.0.x/changes/#version-0-16-1), the removal is not about Atom vs RSS: it 'did not fit in with the rest of Werkzeug, and is better served by a dedicated library in the community'.

python-feedgen seems to fit well (python3, available at pypi.org). I can write a PR if you're interested.

**Comment by RogerHaase** [comment]
Please do a PR, thanks!
