### ISSUE TITLE
flask-theme has issues on python3

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#853]
```
TypeError: '<' not supported between instances of 'bytes' and 'str'
```

Above is bug in flask_theme near line 341.

    def list_templates(self):
        res = []
        ctx = _request_ctx_stack.top
        fmt = '_themes/%s/%s'
        for ident, theme in ctx.app.theme_manager.themes.items():
            # ~ res.extend((fmt % (ident, t)).encode("utf-8")
            res.extend((fmt % (ident, t))
                       for t in theme.jinja_loader.list_templates())
        return res

The bug is commented out line above. The encode creates binary type in python 3. Also seems redundant in python 2.

Opened an issue here: https://github.com/liuliqiang/flask-theme/issues/1

**Comment by ThomasWaldmann** [comment]
There is also this:

https://github.com/maxcountryman/flask-themes

Pros / Cons?

**Comment by ThomasWaldmann** [comment]
https://github.com/liuliqiang/flask-theme/pull/6 PR with fix for this.

**Comment by ThomasWaldmann** [comment]
as soon as we have fixed code on pypi, we need to adjust the minimum requirement there (to 0.3.0):

https://github.com/moinwiki/moin/blob/master/setup.py#L84

also: remove outdated comment right above that.

**Comment by ThomasWaldmann** [comment]
fixed recently by a new flask-theme release and us requiring `flask-theme>0.3.3`.
