### ISSUE TITLE
py3 uid test fails on windows

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#856]
================================== FAILURES ===================================
    _____________________________ TestFuid.testStale ______________________________
    self = <test_filesys.TestFuid object at 0x000001A296D55A48>

        @win32_only
        def testStale(self):
            # is a file with mtime older than max_staleness considered stale?
        
            self.makefile(self.fname, "foo")
            uid1 = filesys.fuid(self.fname)
        
            time.sleep(2)  # thanks for waiting :)
            uid2 = filesys.fuid(self.fname, max_staleness=1)
    >       assert uid2 != uid1  # should be considered stale if platform has no inode support
    E       assert (1564154002.2187822, 202661983233061496, 3, 1564154002) != (1564154002.2187822, 202661983233061496, 3, 1564154002)

    .tox\py37\lib\site-packages\moin\utils\_tests\test_filesys.py:83: AssertionError

**Comment by ThomasWaldmann** [comment]
Where is the difference between these 2 tuples?

**Comment by ThomasWaldmann** [comment]
Maybe a fs timestamp granularity issue. Does it go away with `sleep(2.1)`?

**Comment by ThomasWaldmann** [comment]
Fixed in py3 branch, but not yet merged into master.
