### ISSUE TITLE
fix handle_variables

### ISSUE THREAD

**Issue by ThomasWaldmann** [moinwiki/moin#857]
Currently, the call to handle_variables is disabled, see `moin/items/__init__.py`, ca. line 714.

**Comment by RogerHaase** [comment]
The comments before the disabled code:

        # TODO XXX broken: data can be all sorts of stuff there and handle_variables can't deal with it yet:
        # - non-text binary as bytes
        # - text as bytes? as str? as BytesIO?

The only contenttype that support variables is moinwiki (and the format=1.9 variety) so the incoming data will be STR (after edit and save) or BytesIO (an uploaded file (that may be a template)). 

As there is no 1.9 equivalent that converts variables on an uploaded file, we could just change the docs from:

    Variables
    Variables within the content of a moin wiki item are transformed when the item is saved. 
    An exception is if the item has a tag of ‘’‘template’‘’, then no variables are processed. 
    This makes variables particularly useful within template items. Another frequent use is to 
    add signatures (@SIG@) to a comment within a discussion item.

To:

    Variables
    Variables within the content of a moin wiki item are transformed when the item is saved. 
    This makes variables particularly useful within template items. Another frequent use is to 
    add signatures (@SIG@) to a comment within a discussion item.

    There are two exceptions where the variables are not transformed:
      * if the item has a tag of ‘’‘template’‘’
      * if the saved revision is an uploaded file

Related issues:

In moin 1.9, @DATE@ and @TIME@ were converted to `<<Date(...)>>` and `<<DateTime(...)>>` macros that passed an ISO 8601 date/time. The current moin 2 code passes a *nix timestamp.  This should be changed to pass an ISO 8601 date per the current docs.

The @TIME@ variable seems misnamed, it should have been named @DATETIME@. Add a new @DATETIME@ variable that duplicates @TIME@.

**Comment by RogerHaase** [comment]
It would be be more logical if the `@DATE@, @TIME@, and @DATETIME@` variables mapped directly to the `<<Date()>>, <<Time()>> and <<DateTime()>>` macros. A small change to import19 could be made to convert `@TIME@ to @DATETIME@` when the latest revision of a moinwiki item is converted from 1.9 to 2.0 format.

**Comment by ThomasWaldmann** [comment]
IIRC, the original idea behind @DATE@ and @TIME@ was to produce timestamps (refering to one specific point in time: the current time at the time when the text is expanded/saved) and, depending on which of the both was used, either display only the date or date+time on the wiki page later (it makes no sense to use time without date when referring to one specific point in time).

**Comment by RogerHaase** [comment]
Created new issue for timestamp/ISO 8601 problem. 

Dropping the variables > macro mapping issue.
