### ISSUE TITLE
jquery file upload feature broken, needs update, better documentation

### ISSUE THREAD

**Issue by kwatsen** [moinwiki/moin#869]
On both the "Modify" and the "Subitems/New Item" pages, there's an option to upload file(s). 

By trial and error, I was able to use  "Subitems/New Item/Upload files" to upload a group of image files.  Apparently, both `.png` and `.jpg` suffixes are recognized.

But then I wanted to upload some "MoinMoin" markup files, but no obvious suffix was recognized.  Searching the code, I found that `.moin` should be recognized but, alas, nothing.

In the end, it seems that I don't understand how the upload feature is supposed to work.  For instance, it may be the intention that it can only be used to upload image files.

**Comment by RogerHaase** [comment]
When you create a new text-like item, you must choose the contenttype first, then you will see the Upload button below the edit textarea. Same for modifying an existing text item. Creating a moin-wiki item and then uploading a markdown formatted file will yield poorly formatted results.

Image files are curious in that you can choose the wrong contenttype in some cases and  still get good results. Except for SVG, moin stores the files as binary and serves the files as binary without caring about suffixes. In some cases, your browser will discover the incoming real image type and display it correctly.

It is a good practice to use proper suffixes for all non-text item types. iirc, should you ever do a dump-html to create a static image of your wiki, all browsers will refuse to read and display image files from disk that do not have a proper suffix. Better results may be achieved if the wiki static image is served by a web server.

**Comment by kwatsen** [comment]
Okay, my original description was/is poor.

  - OLD: `On both the "Modify" and the "Subitems/New Item" pages,`
  - NEW: `On the "Subitems/New Item" page,`

The Subitems/New Item page allows for uploading a multiplicity of files without any option to select a content type.  Selecting image files (.jgp, .png) worked, but selecting, e.g., .moin files did not.

Is the contenttype selected via file suffix in this case?

PS: I'm not trying to dump-html.  I was trying to bulk-create a bunch of MoinMoin pages...

**Comment by RogerHaase** [comment]
Jquery file upload must be updated to current/newer version or replaced. Attempts to upload a file now give the following results in the javascript console:

    NotSupportedError: Operation is not supported jquery.fileupload.js:168

Where line 168 is:

                    event.initProgressEvent(
                        'progress',
                        false,
                        false,
                        lengthComputable,
                        loaded,
                        total
                    );

https://developer.mozilla.org/en-US/docs/Web/API/ProgressEvent/initProgressEvent says:

Deprecated
This feature is no longer recommended. Though some browsers might still support it, it may have already been removed from the relevant web standards, may be in the process of being dropped, or may only be kept for compatibility purposes. Avoid using it, and update existing code if possible; see the compatibility table at the bottom of this page to guide your decision. Be aware that this feature may cease to work at any time.

The browser compatibility chart at the bottom of the page shows no browser support except for IE, but uploading a jpg file using IE would not work for me.

**Comment by RogerHaase** [comment]
Closing all these issues #764, #763, #760, #366 as dups.
