### ISSUE TITLE
`<tablestyle>` has undocumented limited effect

### ISSUE THREAD

**Issue by kwatsen** [moinwiki/moin#873]
The `Table Styling` docs state that `<tablestyle>` can be used to add styling to tables.

While that's true (I can see the styling in the rendered HTML), what's not explained is that some stylings won't work due to common.css overriding them.

For instance, I wanted to add `<tablestyle="border:0;">`.  In the end, this failed, and I had to instead add `<style="border:0;">` to every cell in the table.

The reason it didn't work can be traced to `common.css`:
```
/* moin default table styling */
table { margin: 1% 0; }
caption { border: 1px solid #4e7da9; border-bottom: 0; background-color: #C9E2F8; font-size: 1.25em; font-weight: bold; }
tr > th,
tr > td { padding: .3em .4em; vertical-align: middle; text-align: left; }
thead > tr > td,
tr > th { border: 1px solid #4e7da9; background-color: #C9E2F8; text-align: left; color: #000; }
tr > td { border: 1px solid #4e7da9; }
td p { margin: 0; padding: 0; }
#moin-content table > thead { background-color: #C9E2F8; }
#moin-content table > tfoot { background-color: #C9E2F8; }
.moin-thead { background-color: #C9E2F8; } /* creole table headings in left column */
```

At a minimum, the docs should explain the limitation.  

Better, though, maybe, would be to put all this styling under the `moin-wiki-table` class, which is the default class.  That way, a user can override all the styling by first overriding the `<tableclass>`.

That said, and this might be a different issue, I found that one could have only one set of angle-brackets in the first cell.  So, for instance, it s an error to have both `<tableclass>` and `<tablestyle>` set at the same time.  Even with a space character (` `) between the options:

```
2019-08-05 11:55:43,073 ERROR moin.items.content:266 An exception happened in _render_data (error_id = c1f49968-9693-48fb-a657-ce64b626b39a ):
Traceback (most recent call last):
  File "/usr/local/share/moin2/moin/src/moin/items/content.py", line 254, in _render_data
    doc = self.internal_representation(preview=preview)
  File "/usr/local/share/moin2/moin/src/moin/utils/clock.py", line 62, in wrapper
    retval = f(*args, **kw)
  File "/usr/local/share/moin2/moin/src/moin/items/content.py", line 212, in internal_representation
    doc = input_conv(preview or self.rev, self.contenttype, arguments=attributes)
  File "/usr/local/share/moin2/moin/src/moin/converters/moinwiki_in.py", line 148, in __call__
    body = self.parse_block(iter_content, arguments)
  File "/usr/local/share/moin2/moin/src/moin/converters/moinwiki_in.py", line 1049, in parse_block
    self.indent_repl(iter_content, stack, line, **data)
  File "/usr/local/share/moin2/moin/src/moin/converters/moinwiki_in.py", line 492, in indent_repl
    self._apply(match, 'block', it, new_stack)
  File "/usr/local/share/moin2/moin/src/moin/converters/moinwiki_in.py", line 1035, in _apply
    getattr(self, func)(*args, **data)
  File "/usr/local/share/moin2/moin/src/moin/converters/moinwiki_in.py", line 324, in block_table_repl
    self.block_table_row(table, stack, element)
  File "/usr/local/share/moin2/moin/src/moin/converters/moinwiki_in.py", line 346, in block_table_row
    self._apply(match, 'tablerow', stack, table, element)
  File "/usr/local/share/moin2/moin/src/moin/converters/moinwiki_in.py", line 1035, in _apply
    getattr(self, func)(*args, **data)
  File "/usr/local/share/moin2/moin/src/moin/converters/moinwiki_in.py", line 961, in tablerow_cell_repl
    msg1, error, msg2, cell_markup, cell_text)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u201d' in position 11: ordinal not in range(128)
```

**Comment by RogerHaase** [comment]
The traceback will go away with python 3 and be replaced with a different error message. Assuming you did a copy and paste from the docs the " character is not an ascii " but  is a unicode Character 'RIGHT DOUBLE QUOTATION MARK' (U+201D).

I think the \201D can be replaced with a ascii " 

If you want multiple styling elements in a cell, separate with a blank within one set of angle brackets. per the example:

    ||<rowstyle="font-weight: bold;" class="monospaced">monospaced text||bold text||

The tableclass does not replace the default table class, it only adds classes. So the easiest way to create a border-less table (which many users may want to do) is to add some rules to common.css:

    /* alternate table styling with no cell borders */
    .moin-no-cell-borders caption,
    .moin-no-cell-borders th,
    .moin-no-cell-borders td { border-width: 0; }

and add some docs to suggest use of <tableclass="moin-no-cell-borders">

**Comment by RogerHaase** [comment]
The \201D seems to be a Sphinx feature. Quotes are changed to a unicode character based upon the current language. Per https://docs.anaconda.com/restructuredtext/detailed/#smart-quotes-dashes-and-unicode

    Smart quotes, dashes, and Unicode
    Sphinx automatically converts double dashes to unicode dashes, and quotes to smart quotes.

So both ascii single-quotes and double-quotes get changed to unicode smart quotes by default. As a result, anyone doing a copy and paste from Sphinx docs will get invalid characters if the string being copied contains a quote.

There seems to be an option to turn this off by adding "smart_quotes = False" to conf.py. But when I added the option to /docs/conf.py it had no effect

Search for smartquotes in http://www.sphinx-doc.org/en/master/usage/configuration.html
