### ISSUE TITLE
small (<19Kb) pics do not render

### ISSUE THREAD

**Issue by kwatsen** [moinwiki/moin#874]
I created some thumbnail pics.  They uploaded okay, but in trying to view the image page, the browser status bar would spin for awhile and finally give up rendered to the screen one line of text: `Resources/Pictures/icon-50.png`

Note, in this example, the file icon-50.png is actually 2,133 bytes large.  What's vary interesting, is that this very same file image file renders just fine when located in the `wiki_local` directory and served via `snippets.html` via:

```
wiki_local/snippets.html:        <img src="{{ url_for('serve.files', name='wiki_local', filename='icon-50.png') }}" width="12" height="25"/>
```

Playing, I found that image files < ~19 Kb would have problems.  I found that by simply increasing the size of the file by adding EXIF, comments, thumbnail, etc. to push a file size over the 19KB size limit would suddenly enable a thumbnail to show, though the size of the image itself remained the same.

Here's the associated log output:
```
[pid: 67896|app: 0|req: 2359/2359] 10.0.4.6 () {52 vars in 1369 bytes} [Mon Aug  5 12:03:38 2019] GET /Resources/Pictures/icon-50.png => generated 12949 bytes in 603 msecs (HTTP/1.1 200) 4 headers in 521 bytes (5 switches on core 0)
2019-08-05 12:03:39,483 INFO moin.utils.clock:45 timer init(0): 37.28ms
2019-08-05 12:03:39,561 INFO moin.utils.clock:45 timer total(0): 115.24ms
uwsgi_sendfile_do()/read(): Undefined error: 0 [core/sendfile.c line 46]
Mon Aug  5 12:03:39 2019 - uwsgi_response_sendfile_do(): Undefined error: 0 [core/writer.c line 655] during GET /+get/+b99ce6679874474ca71c785db2894bc8/Resources/Pictures/icon-50.png (10.0.4.6)
IOError: write error
[pid: 67896|app: 0|req: 2360/2360] 10.0.4.6 () {50 vars in 1405 bytes} [Mon Aug  5 12:03:39 2019] GET /+get/+b99ce6679874474ca71c785db2894bc8/Resources/Pictures/icon-50.png => generated 0 bytes in 121 msecs via sendfile() (HTTP/1.1 200) 9 headers in 688 bytes (1 switches on core 0)
```

**Comment by RogerHaase** [comment]
Cannot reproduce the error. But if Resources is a namespace, there is #868

When you see "Resources/Pictures/icon-50.png" instead of the image, the browser is showing the image alternate text and there will likely be a 404 in the server log.

**Comment by RogerHaase** [comment]
Cannot reproduce. Attach a failing image if you want to reopen this.
