### ISSUE TITLE
missing `redirect` feature

### ISSUE THREAD

**Issue by kwatsen** [moinwiki/moin#875]
This is a feature request more than a bug, as I don't see anything in the docs claiming that it should work at all.

That said, I noticed that the moin1.9 has both a pragma (`##REDIRECT`) and a macro (JSRedirect.py), so it seems that folks may look for it when moving to moin2...

**Comment by RogerHaase** [comment]
Redirect is not needed.

Delete the obsolete item and give the target item the old name as an alias.

Or, use a transclusion:

{{ShowOtherItem}}

Or for the curious JSRedirect.py, just do a link:

[[GoToSomewhereElse]]

**Comment by kwatsen** [comment]
```
Redirect is not needed.

Delete the obsolete item and give the target item the old name as an alias.
```

This might work, but I can't find any documentation on how to do aliases.  I wonder, do aliases provide the Wikipedia experience whereby there is a flash that states that redirection occurred?


```
Or, use a transclusion:

{{ShowOtherItem}}
```

I thought about this, but it seems to invite problems if/when someone edits the page...



```
Or for the curious JSRedirect.py, just do a link:

[[GoToSomewhereElse]]
```

Not a bad option: drop-dead simple with predictable results.

**Comment by ThomasWaldmann** [comment]
One of the ideas in moin2 was that an item may have multiple names, all being equal.

So it's not a primary names + aliases, but really multiple names.

The approach has proven to cause quite some difficulties though (like e.g. ACL processing).

**Comment by RogerHaase** [comment]
I rewrote the moin 1.9 JSRedirect.py macro and added a bit of javascript code to resolve this, but then decided it was better to use the js code and just add docs for a "redirect" class to the links documentation. See the commit link above.

For the record, here is the JSRedirect.py code never committed:

    # Copyright: 2021 MoinMoin:RogerHaase
    # License: GNU GPL v2 (or any later version), see LICENSE.txt for details.

    """
        JavaScript Redirect Macro; rewrite of Jason Dillon's moin 1.9.x contributed macro.

        Replaces moin 1.9.x #redirect processing instruction. common.js contains
        supporting code, search for moin-js-redirect.

        Usage:
            <<JSRedirect(PageName)>>
        Where PageName is any local itemname, external URL, or interwiki link.

        Hint: once added to an item, the only way to remove or edit the macro
        is to type /+modify/<name> in browser's address bar.

        An alternative to this macro is to use a link similar to:
            [[Target||class="moin-js-redirect]]
    """

    from moin.macros._base import MacroBlockBase
    from moin.i18n import _, L_, N_
    from moin.converters.moinwiki_in import Converter as MOINWIKI_IN_Converter


    moinwiki_in_converter = MOINWIKI_IN_Converter()

    msg = _("This page should be redirected shortly. If not, please click link below:")

    moinwiki = """
    {0}

    [[{1}]]
    """


    class Macro(MacroBlockBase):
        def macro(self, content, arguments, page_url, alternative):
            # creating a link is complex, so we use moinwiki converter to do the job
            link = arguments[0] + '||class="moin-js-redirect"'
            ret = moinwiki_in_converter(moinwiki.format(msg, link))
            return ret
