### ISSUE TITLE
<<ItemPageList>> macro should filter on tags as well

### ISSUE THREAD

**Issue by kwatsen** [moinwiki/moin#876]
I wrote the `ItemPageList` macro and have since found a strong need to be able to filter on tags, thus enabling select lists of child pages to be rendered.

I'd love to add this myself, but a few hints on how to get the tags associated with an item would help...

**Comment by RogerHaase** [comment]
Look at code for +tags in apps\frontend/views.py.

Consider adding 2 parameters: includetags and excludetags and closing #889 

Also consider supporting <<ItemPageList()>> and <<ItemPageList>> which would show children of current item. Currently these show error messages on item preview and <No matching pages were found> after page is saved.

The PageTitle option will be slow as the current revision of every item in the list will have to re read. There is a "Summary" field in the meta data that would be faster.

**Comment by RogerHaase** [comment]
ItemPageList renamed to ItemList
