### ISSUE TITLE
The <<ItemPageList>> macro's "UnCameled" should special-case the letter/word "A"

### ISSUE THREAD

**Issue by kwatsen** [moinwiki/moin#877]
While the "UnCameled" link-rendering style is fast and pretty flexible, it fails to handle the case when the word "a" is in the page's name.

For instance, the page name "ThisIsAPageName" Is rendered as "This Is APage Name", with no separation between the words "A" and the "Page".

**Comment by ThomasWaldmann** [comment]
we should not add language-specific features like that.

moin needs to support (or not support) all languages equal and we can't do that for all.

the whole CamelCase thing was a bad hack right from the beginning, causing lots of issues.

we only still support that for compatibility reasons, but if you want pretty page names, you just need to name the page as you would like it to be displayed.

the multiple names feature might help.
