### ISSUE TITLE
<<ItemPageList>> macro should support rendering the child's "Title" for the link.

### ISSUE THREAD

**Issue by kwatsen** [moinwiki/moin#878]
I wrote the `ItemPageList` macro, and while the "UnCameled" link-rendering style is pretty flexible, it seems that rending the child page's title (e.g., `= Title =`) would be goodness.

Having written the ItemPageList macro, I'd be happy to add this myself, but a few hints on how to get the title associated with an item would help...

**Comment by RogerHaase** [comment]
ItemPageList renamed to ItemList
