### ISSUE TITLE
Document page `rename` feature

### ISSUE THREAD

**Issue by kwatsen** [moinwiki/moin#880]
I previously filed #808 and then subsequently #840 was opened.

As it turns out, I did quite a lot of renaming over the weekend and it seems that some undocumented backend magic is occurring, likely the rebuilding of indexes.  

Regardless, the user-experience is that some things don't seem to work initially and then, a few moments later, they do.

It would be helpful if the "rename" feature could be documented.

**Comment by ThomasWaldmann** [comment]
IIRC, moin does not magically *rebuild* the index (like a full rebuild, as it can be done from the commandline).

What it does (or should do) is an index *update* when needed to keep the index consistent with the wiki contents.
