### ISSUE TITLE
Improve "Load Draft" usability

### ISSUE THREAD

**Issue by kwatsen** [moinwiki/moin#881]
Issue #460 is very good, and I especially appreciate the "Load Draft" button.

However, I accidentally didn't click the "Load Draft" button once (after coming back from a lunch break) and lost about 3-hours of edits on a single page (I was taking notes in a class, and just kept on hitting "preview" without ever saving).

Some suggestions to improve usability:

1) move the "Load Draft" button to the first position.
2) rename the "OK" button to something like "OK (discards previous draft)".

**Comment by RogerHaase** [comment]
* moving Load Draft button to first position on left
* changing button color to red/pink
* if draft available, added title/tooltip warning to OK, Preview, and Cancel buttons
