### ISSUE TITLE
`+orphans` should somehow exclude items that are reached via the <<ItemPageList>> macro

### ISSUE THREAD

**Issue by kwatsen** [moinwiki/moin#884]
Orphaned Items (`+orphans`) currently displays pages that are technically orphaned, but are so on purpose, as they are reached via the `<<ItemPageList>>` macro.

On my system, there are many such pages, thus the signal/noise ratio of this view is very low.  

Ideally the solution would use metadata (e.g., a "tag" called "NotAnOrphan") in order to be more generally useful.

**Comment by RogerHaase** [comment]
I think you need a custom macro to produce the desired output, place the macro on a wiki page and do an "Add Link" to see the link in the Navigation panel.

The feature as you describe it is likely to be useful only for your application.

Close this issue if you agree.

**Comment by kwatsen** [comment]
Not so much "my application" as "all applications using the `<<ItemPageList>>` macro".

That said, I notice that `+orphans` also lists `Home` as well as other "placeholder" pages that I've created and am knowingly okay with that they're not linked to anything.

I view `+orphans` as like an "alarms" panel and, as with any alarm panel, I want to be able to say "this issue is not really an issue, please ignore".

I don't agree this issue should be closed.  I think that this issue should be prioritized down (prio5?) for now.

**Comment by ThomasWaldmann** [comment]
I'ld like that functionality in moin stays as little "magic" as possible.

So if a list of something is created, it is a complete list and not magically excluding some stuff due to criteria that are not visible.

**Comment by RogerHaase** [comment]
#876 could solve this problem, closing as a dup.
