### ISSUE TITLE
Documentation for macros too sparse

### ISSUE THREAD

**Issue by kwatsen** [moinwiki/moin#886]
Looking at `+serve/docs/user/moinwiki.html#macros`, one sees that the documentation is very sparse.

Having written extensive documentation for the `<<ItemPageList()>>` macro, I was hoping to find it linked here but, alas, apparently that documentation is only accessible when loading the "sample" server data...

How can the macro documentation be improved for users?

**Comment by RogerHaase** [comment]
Probably add a new section after Macros with more detail for each macro. Some macros may not need further explanation, the single line in the table is sufficient.

Someone needs to copy and reformat the MoinWikiMacros text into /docs/user/moinwiki.rst
