### ISSUE TITLE
The <<ItemPageList>> should not include templates

### ISSUE THREAD

**Issue by kwatsen** [moinwiki/moin#889]
Templates are just pages that have a tag called "template" but, do to their intended use, they should be excluded from `<<ItemPageList>>` views.

Should this be default behviour?  - if not, then perhaps this issue could be solved by Issue #876 supporting boolean expressions...

**Comment by RogerHaase** [comment]
ItemPageList renamed to ItemList

**Comment by RogerHaase** [comment]
#876 could solve this problem, closing as a dup.
