### ISSUE TITLE
refactor charset extraction from contenttype

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#890]
Place this code (or similar) somewhere in utils and refactor various methods of extracting charset to use the new function:

        if 'charset' in rev.meta['contenttype']:
            charset = rev.meta['contenttype'].split('charset=')[1]

There are places where re is used to extract charset. Since presence of charset in contenttype is an indication of a text file, maybe add a helper function to test whether an item is a text-like file.

See #867

**Comment by ThomasWaldmann** [comment]
Maybe the utility function could even go a bit further:

guess one is mostly interested in the charset (coding) because one wants to run `bytes.decode(coding)`.

so the utility function could be just called like:
```
text = as_text(rev)
or even
text = rev.as_text()
or (best)
text = str(rev)
```

**Comment by RogerHaase** [comment]
Try again with `__str__` code added to the Revision object, not the the ProtectedRevision object

**Comment by RogerHaase** [comment]
closing as duplicate of #920
