### ISSUE TITLE
docs still say "python 2.7"

### ISSUE THREAD

**Issue by ThomasWaldmann** [moinwiki/moin#905]
https://moin-20.readthedocs.io/en/latest/admin/requirements.html

**Comment by ThomasWaldmann** [comment]
Hmm, seems like only the readthedocs.io site is out-of-date, the docs in our repo are ok.

**Comment by RogerHaase** [comment]
Readfthedocs was trying to build with python 2.7, changed to python 3.7. Build passed 2 times in a row.

**Comment by RogerHaase** [comment]
One day later there are no hits when searching for 2.7. I did a local browser reload, so maybe readthedocs has search caching.
