### ISSUE TITLE
import19 chooses wrong "last revision of Moin 1.9" for markup conversion

### ISSUE THREAD

**Issue by ingoha** [moinwiki/moin#928]
In my setup (importing from 1.9.9), the importer chooses arbitrary revisions but not the latest one.
Perhaps this has to do with the usage of revision ids for finding the latest one vs. the revision no (which would be the correct way?)?

**Comment by RogerHaase** [comment]
An alternative solution is to sort the revisions by name** within the iter_revisions method. The current line 249 within import19.py:

    fnames = os.listdir(revisionspath)

should be:

    fnames = sorted(os.listdir(revisionspath))

The advantage of the above is that the metadata PARENTID set in line 258 will be correct.

Will push alternative fix after a bit more testing.

**  os.listdir with python 3.7.4 on Windows seems to consistently do this, contrary to the docs saying the file names are presented in arbitrary order.

**Comment by ThomasWaldmann** [comment]
guess the python docs just want to say that one can not rely on any specific order (so python stdlib does not sort). of course it also depends on the OS / filesystem, whether some ordering is done at that level.
