### ISSUE TITLE
design ideas, guidelines

### ISSUE THREAD

**Issue by ThomasWaldmann** [moinwiki/moin#93]
**[Original report](https://bitbucket.org/thomaswaldmann/moin-2.0/issue/93) by Thomas Waldmann (Bitbucket: [thomaswaldmann](https://bitbucket.org/thomaswaldmann), GitHub: [thomaswaldmann](https://github.com/thomaswaldmann)).**

----------------------------------------

we should have some generic design guidelines for moin2, to make it look better and more consistent.

**Comment by RogerHaase** [comment]
@ThomasWaldmann do you have an example of what this should look like or can this be closed?
