### ISSUE TITLE
stuff found in import19 review

### ISSUE THREAD

**Issue by ThomasWaldmann** [moinwiki/moin#930]
There are / were some comments in import19.py that should be reviewed because they might be still todo / might point to existing issues:

* translate revno numbering into revid parents
* ACLs for attachments

Found in #922 PR review.

**Comment by RogerHaase** [comment]
I think "translate revno numbering into revid parents" was fixed ~2018-12-17 by 

SHA-1: c52a853e08df98d50225aabfef5200c724f60d0f

* import19 should not create metadata parentid key on first revision; addresses #785
