### ISSUE TITLE
Item History is sluggish

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#940]
After a couple of timers to the history procedure of frontend/views.py near line 1316:

    flaskg.clock.start('runrevs')
    for rev in revs:
        entry = dict(rev.meta)
        entry[FQNAME] = rev.fqname
        entry[FQNAMES] = rev.fqnames
        history.append(entry)
        close_file(rev.data)
    flaskg.clock.stop('runrevs')

    history_page = utils.getPageContent(history, offset, results_per_page)
    close_file(item.rev.data)
    trash = item.meta['trash'] if 'trash' in item.meta else False
    
    flaskg.clock.start('renderrevs')
    ret = render_template('history.html',
                          fqname=fqname,
                          item=item,
                          item_name=item_name,
                          history_page=history_page,
                          bookmark_time=bookmark_time,
                          NAME_EXACT=NAME_EXACT,
                          len=len,
                          trash=trash,
    )
    flaskg.clock.stop('renderrevs')
    
    close_file(item.rev.data)
    return ret

and then displaying 20 revisions of an item with many revisions:

    runrevs takes 39682.98ms
    renderrevs takes 5204.00ms

Displaying the second page of revisions yields similar timings.

One reason runrevs is taking a long time is it appears the content of each revision is needlessly read; only a few fields of the metadata are required.  

Is there a way to read only the metadata of a revision?

**Comment by ThomasWaldmann** [comment]
IIRC, there is a bytes- and a file-like API to revisions. The latter one gives an open file still, but might be better than actually reading the data and returning it as bytes (when we do not need it).

**Comment by RogerHaase** [comment]
After implementing the TODO comment within the history method (replace whoosh search with search_page) and removing unnecessary IO within history.html, the time to display 20 revisions of an item with over 600 revisions, the response time was improved (times are in seconds):

| Show 20 revisions      |runrevs     |renderrevs  |
|------------------|-------------:|-----:|
|Before changes |40          |5 |
|After changes   |3            |2 |

To show all 600+ revisions:

| Show all revisions      |runrevs     |renderrevs  |
|------------------|-------------:|-----:|
|Before changes |75          |74 |
|After changes   |52           |2 |


I think item history does use the file-like API to revisions. A potential problem is the revision content is in the metadata, so reading the metadata may result in large amounts of IO when the revision is large. But not sure if there is a substantial difference is asking whoosh for 200 bytes vs 20 kbytes of data.

**Comment by RogerHaase** [comment]
re comments on pull #945

This TODO was in apps/frontend/views.py, it was removed as part of the patch.

    # TODO: due to how getPageContent and the template works, we need to use limit=None -
    # it would be better to use search_page (and an appropriate limit, if needed)

We need to know number of revisions to determine when we are on last page. 

Per https://whoosh.readthedocs.io/en/latest/searching.html#results-object

    Calling len(Results) runs a fast (unscored) version of the query again to figure out the total number of matching documents. 

Per my tests with 600+ revisions, len(..) takes about .2 seconds.

    if results_per_page:
        flaskg.clock.start('len_revs')
        len_revs = flaskg.storage.search_len(query, idx_name=ALL_REVS)
        flaskg.clock.stop('len_revs')
        flaskg.clock.start('search page')
        revs = flaskg.storage.search_page(query, idx_name=ALL_REVS, sortedby=[MTIME], reverse=True, pagenum=page_num, pagelen=results_per_page)
        flaskg.clock.stop('search page')

The server log:

        2020-01-23 10:09:55,055 INFO moin.utils.clock:45 timer init(0): 65.00ms
        2020-01-23 10:09:55,384 INFO moin.utils.clock:45 timer len_revs(0): 208.00ms
        2020-01-23 10:09:55,385 INFO moin.utils.clock:45 timer search page(0): 0.00ms
        2020-01-23 10:10:00,092 INFO moin.utils.clock:45 timer runrevs(0): 4706.97ms
        2020-01-23 10:10:01,159 INFO moin.utils.clock:45 timer navibar(0): 57.97ms
        2020-01-23 10:10:01,923 INFO moin.utils.clock:45 timer renderrevs(0): 1705.03ms
        2020-01-23 10:10:01,925 INFO moin.utils.clock:45 timer total(0): 6936.00ms
        2020-01-23 10:10:01,926 INFO werkzeug:122 127.0.0.1 "GET /+history/ChangeLog HTTP/1.1" 200 -
Somehow, calling flaskg.storage.search and flaskg.storage.search_page always take 0ms per my testing.  Some sort of whoosh black magic? So throwing away the results of
    len_revs = flaskg.storage.search_len(query, idx_name=ALL_REVS)
is not wasteful because redoing the flaskg.storage.search_page with sorting, reversing, page selection, and specifying the pagelen takes 0ms.

More code executed later:

    # get rid of the content value to save potentially big amounts of memory:
    history = []
    flaskg.clock.start('runrevs')
    for rev in revs:
        entry = dict(rev.meta)
        entry[FQNAME] = rev.fqname
        entry[FQNAMES] = rev.fqnames
        history.append(entry)
        close_file(rev.data)
    flaskg.clock.stop('runrevs')

Clock times repeated from above:

        2020-01-23 10:10:00,092 INFO moin.utils.clock:45 timer runrevs(0): 4706.97ms

The above time is the result of running through 50 revisions, or about 100ms per revision. Whoosh searches seem fast, processing the search results are slower.

----

Will change the method name from search_len to search_results_size.
