### ISSUE TITLE
can we use new string formatting using .format() method?

### ISSUE THREAD

**Issue by ThomasWaldmann** [moinwiki/moin#99]
**[Original report](https://bitbucket.org/thomaswaldmann/moin-2.0/issue/99) by Thomas Waldmann (Bitbucket: [thomaswaldmann](https://bitbucket.org/thomaswaldmann), GitHub: [thomaswaldmann](https://github.com/thomaswaldmann)).**

----------------------------------------

moin stil uses "%s %d" % (foo, bar) style string formatting.

some work has already been done on replacing this with .format() new style formatting, but it is not completed yet.

especially, a lot of translatable strings still use old %-style.

maybe this is related to the _() method there, this should be checked (and whether we can / should use .format() there.

this needs to be done before doing translations, because change of original english strings would make the translated string invalid.

if we decide on using some other formatting method than now, the respective refactoring should be done globally in the source.

**Comment by UlrichB22** [comment]
IMO we should use the existing method like `_("Modifying '{item_name}'").format(item_name=fqname.value) `
In the meantime, it has already been used for around 14 strings (e.g. in apps/admin/views.py). Some of them are calling format() before the translation, so the translation does not succeed.

There is nothing new from flask-babel. f-strings would be great, but there is no plan to implement, see https://github.com/python-babel/babel/issues/594.

I can work on changing the %-formatting step by step. Please approve.

**Comment by UlrichB22** [comment]
The migration of %-formatting in connection with translations can be done script-based (95%), including the language "de". Other languages can be prepared, but must be checked and corrected by native speakers if necessary. They have not been updated for a long time. Still waiting for approval to proceed.

For other strings I recommend using f-strings if possible. For example all logging messages could be changed, e.g.: 

```
src/moin/app.py:83
-    logging.debug("info_name: %s cmd_name: %s", info_name, cmd_name)
+    logging.debug(f"info_name: {info_name} cmd_name: {cmd_name}")
```
I look forward to your feedback
